### PR TITLE
Fix jump to recent messages

### PR DESCRIPTION
**Pull request by enahum**
#### Ticket Link
https://mattermost.atlassian.net/browse/MM-11073

#### Device Information
This PR was tested on: 
* IOS 11.4 Simulator (iPhone X)
* Android 7.1.1 Emulator

### CODE REVIEW

**Comment by sudheerDev** [comment]
@enahum One minor thing. When searched in the same channel then `Jump to recent message` does not scroll to the bottom.

**Comment by sudheerDev** [comment]
Dont know if it a regression or should it even be considered a bug.

**Comment by enahum** [comment]
it never has... but I can try and force it

**Comment by enahum** [comment]
@sudheerDev now an event is being emitted to force the scroll to bottom

**Pull request merged**
