### PR TITLE
[Gekidou - MM-45791] Use the same handler for search clear and cancel actions

### PR DESCRIPTION
**Pull request by jfrerich**
#### Summary
This PR shares the same handler for clear and cancelling a search.  The only needed change was that in the results screen, the clear and cancel options should both take the user to the initial search screen. Previously, only the `cancel` option took the user to the initial search screen. Since both options now take the user to the initial search screen there is no need for separate handlers.

- use the same handler for onClose and onClear
- SearchBar component will handle the focussing and blurring
- Keyboard dismissal is handled in the onCancel and onClear functions in
search/index.tsx

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-45791

#### Checklist

- [ ] Added or updated unit tests (required for all new features)
- [ ] Has UI changes
- [ ] Includes text changes and localization file updates
- [ ] Have tested against the 5 core themes to ensure consistency between them.

#### Device Information
This PR was tested on: 

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by avinashlng1080 — APPROVED** [review]

**Review by matthewbirtch — CHANGES_REQUESTED** [review]
@jfrerich so, the search clear and cancel actions shouldn't always behave the exact same way. Here's the desired behavior:

### Initial search view with modifiers and expanded header
1. When search input is focused, but user hasn't typed anything yet:
    - the keyboard shows
    - the clear `x` does not show, 
    - the `cancel` button should reset the view to the default and show the top bar in the expanded state

2. When the search input is focused and the user HAS typed something:
    - the keyboard shows
    - the clear 'x' shows and when tapped it clears the search value, but keeps the search input focused (keeps top bar in collapsed state)
    - the `cancel` button should unfocus the input and reset the view and expand the top bar
----
### When showing search results:
1. When the search input is not focused:
    - the clear 'x' shows and when tapped it clears the search value and resets the view, but keeps the input focused, shows keyboard and the collapsed top bar
    - **can we still show the cancel button in this case?** If so, then cancel would reset the view and return to the expanded header
2. When the input is focused
    - the clear `x` should clear the search value, reset the view to show the modifiers/recent searches, but keep the input focused and the top bar in the collapsed state
    - the cancel button should clear the search value, reset the view to show the modifiers/recent searches, unfocus the input and reset the top bar to the expanded state
----
I _think_ this covers the behavior, but let me know if it's unclear. I may not have been clear in my previous explanations.

**Comment by enahum** [comment]
I would disagree with

> When the input is focused
the clear x should clear the search value, reset the view to show the modifiers/recent searches, but keep the input focused and the top bar in the collapsed state

I'd expect to keep the results and allow the user to input another search, basically do not reset the view as I'm clearing the text not cancelling the search

**Comment by matthewbirtch** [comment]
> I would disagree with
> 
> > When the input is focused
> > the clear x should clear the search value, reset the view to show the modifiers/recent searches, but keep the input focused and the top bar in the collapsed state
> 
> I'd expect to keep the results and allow the user to input another search, basically do not reset the view as I'm clearing the text not canceling the search

Hmmm, interesting. I'm kind of on the fence with this specific case @enahum. I was testing out other Apps and was looking specifically at Apple Music. They do reset the search if you use the clear `x` in this case and it feels pretty good. I'm not 100% convinced on either direction though.

**Comment by enahum** [comment]
> > I would disagree with
> 
> > 
> 
> > > When the input is focused
> 
> > > the clear x should clear the search value, reset the view to show the modifiers/recent searches, but keep the input focused and the top bar in the collapsed state
> 
> > 
> 
> > I'd expect to keep the results and allow the user to input another search, basically do not reset the view as I'm clearing the text not canceling the search
> 
> 
> 
> Hmmm, interesting. I'm kind of on the fence with this specific case @enahum. I was testing out other Apps and was looking specifically at Apple Music. They do reset the search if you use the clear `x` in this case and it feels pretty good. I'm not 100% convinced on either direction though. 

@matthewbirtch we should broader the "research" most apps do not do what apple music does but more importantly in  our case it should make sense for both Android and iOS

**Comment by jfrerich** [comment]
Interesting feedback, @matthewbirtch.  I would have expected the behavior that Elias suggested, but it looks like your case is the most common.

**Comment by enahum** [comment]
@matthewbirtch I'm fine with that, we can always change the behavior based on feedback

**Review by larkox — APPROVED** [review]

**Comment by jfrerich** [comment]
> @jfrerich so, the search clear and cancel actions shouldn't always behave the exact same way. Here's the desired behavior:
> 
> ### Initial search view with modifiers and expanded header
> 1. When search input is focused, but user hasn't typed anything yet:
>    
>    * the keyboard shows
>    * the clear `x` does not show,
>    * the `cancel` button should reset the view to the default and show the top bar in the expanded state
> 2. When the search input is focused and the user HAS typed something:
>    
>    * the keyboard shows
>    * the clear 'x' shows and when tapped it clears the search value, but keeps the search input focused (keeps top bar in collapsed state)
>    * the `cancel` button should unfocus the input and reset the view and expand the top bar
> 
> ### When showing search results:
> 1. When the search input is not focused:
>    
>    * the clear 'x' shows and when tapped it clears the search value and resets the view, but keeps the input focused, shows keyboard and the collapsed top bar
>    * **can we still show the cancel button in this case?** If so, then cancel would reset the view and return to the expanded header
> 2. When the input is focused
>    
>    * the clear `x` should clear the search value, reset the view to show the modifiers/recent searches, but keep the input focused and the top bar in the collapsed state
>    * the cancel button should clear the search value, reset the view to show the modifiers/recent searches, unfocus the input and reset the top bar to the expanded state
> 
> I _think_ this covers the behavior, but let me know if it's unclear. I may not have been clear in my previous explanations.

**Comment by jfrerich** [comment]
I'm adding this to track the needed changes

### Initial search view with modifiers and expanded header
1. When search input is focused, but user hasn't typed anything yet:
    - [ ] the keyboard shows 
      - [ ] iOS (**keyboard not showing**)
      - [ ] Android
    - [ ] the clear `x` does not show,
      - [x] iOS
      - [ ] Android       
    - [ ] the `cancel` button should reset the view to the default and show the top bar in the expanded state
      - [ ] iOS (**reset happens, but header does not expand**)
      - [ ] Android       

2. When the search input is focused and the user HAS typed something:
    - [ ] the keyboard shows
      - [ ] iOS (**keyboard not showing**)
      - [ ] Android       
    - [ ] the clear 'x' shows and when tapped it clears the search value, but keeps the search input focused (keeps top bar in collapsed state)
      - [x] iOS
      - [ ] Android       
    - [ ] the `cancel` button should unfocus the input and reset the view and expand the top bar 
      - [ ] iOS (**unfocus occurs, but top bar does not expand**)
      - [ ] Android       
----
### When showing search results:
1. When the search input is not focused:
    - [ ] the clear 'x' shows and when tapped it clears the search value and resets the view, but keeps the input focused, shows keyboard and the collapsed top bar
      - [ ] iOS (**keyboard not showing, callapsing doesn't happen**)
      - [ ] Android       
    - [ ] **can we still show the cancel button in this case?** If so, then cancel would reset the view and return to the expanded header
      - [ ] iOS (**cancel option not shown in this state**)
      - [ ] Android       
2. When the input is focused
    - [ ] the clear `x` should clear the search value, reset the view to show the modifiers/recent searches, but keep the input focused and the top bar in the collapsed state
      - [ ] iOS (**nav bar gets expanded**)
      - [ ] Android       
    - [ ] the cancel button should clear the search value, reset the view to show the modifiers/recent searches, unfocus the input and reset the top bar to the expanded state
      - [ ] iOS (**nav bar gets expanded**)
      - [ ] Android       
----

**Comment by jfrerich** [comment]
@matthewbirtch, I've checked the conditions mentioned in my previous comment. The only thing that I believe missing are the navigation headers collapsing and uncollapsing.  


I also think the following was stated incorrectly. When the `x` is tapped, the search value should clear and reset the view, but the input was not focused and should remain unfocussed.  I also think the keyboard should not show in this case as the input is not focused.
> When showing search results:
>    1. When the search input is not focused:
>       1. the clear 'x' shows and when tapped it clears the search value and resets the view, but keeps the input focused, shows keyboard and the collapsed top bar

I am going to create a separate ticket to address the heading collapsing/uncollapsing issue. 

If you agree with the change suggested above, I think this is ready to merge.

**Comment by jfrerich** [comment]
Here's the ticket to resolve the collapsing/uncollapsing of the header issue..  I have pushed those issues for later to set priority on getting the functionality PRs added first. I'll address the navigation issues for all cases in one separate PR.

**Comment by avinashlng1080** [comment]
@jfrerich  - I'm going to add the 'Do not merge' label as I'm not sure what's happening here.

However, if this can be merged, please fix the conflicts and let me know.

**Comment by matthewbirtch** [comment]
@jfrerich I'm getting errors and can't test right now. 
image

**Comment by enahum** [comment]
Resolve conflicts

**Comment by jfrerich** [comment]
@elias, @matthewbirtch, conflicts are resolved.

@matthewbirtch, we added a new package and you will need pick it up. 

try running `npm i` then having xcode install the app again.

If that doesn't work, I had to run `pod install --repo-update` in the `ios` directory.

If that fails, let me know and we can debug to get it working again

**Comment by jfrerich** [comment]
@avinashlng1080, I resolved the conflicts. The PR itself only changes the functionality of the `cancel` and `x` buttons, when in the results and intitial view (showing modifiers and recent searches).  Both actions will take the user from the results to the initial screen with this change.

**Review by matthewbirtch — APPROVED** [review]
I think we're good to go with this @jfrerich knowing that you've got anoother ticket to resolve the header collapsing.

**Review by larkox — APPROVED** [review]

**Pull request merged**
