### PR TITLE
MM-9548 - Scroll to top when iOS status bar is pressed

### PR DESCRIPTION
**Pull request by emilioicai**
#### Summary
React Native `ScrollViews` (including `FlatLists`) are flipped upside down when the prop `inverted` is set to `true`. This is the root of many bugs one of them affecting `PostList`: tapping on the status bar in iOS should scroll the `Flatlist` up to the top.

The solution proposed is to detect natively if the ScrollView is inverted, on such case, prevent it from scrolling it to the beginning of the `ScrollView` (as a non-inverted ScrollView would do) and force a scroll to the end of it.

I've been careful not to force the scroll if the user explicitly selected not to do it or if it's happening in a nested `ScrollView`, as it's default in iOS.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/13220
Jira Ticket: https://mattermost.atlassian.net/browse/MM-9548

#### Checklist
- [ ] Has UI changes
- [ ] Includes text changes and localization file updates

#### Device Information
This PR was tested on: iPhone XS (iOS 13.1.3), iPhone 8 (iOS 13.1.3)

#### Screenshots
v

### CODE REVIEW

**Comment by emilioicai** [comment]
Related https://github.com/facebook/react-native/issues/21126
Related https://github.com/facebook/react-native/pull/27574

**Comment by chuttam** [comment]
As a patch, this looks good to me.

The diff for the single `react-native+0.61.2.path` is getting a bit difficult to tease out individual change sets. It seems like `patch-package` doesn't have a way to allow manual organizing of the single patch file contents. Should we consider creating a separate patch file for each identifiable thing/feature/bug? We run all patches in `make post-install` anyway.

**Comment by adamjclarkson** [comment]
Ok, have tested on my iPhone X, iOS 13.3. Working great. My one question is about this caveat in original summary:

> I've been careful not to force the scroll if the user explicitly selected not to do it or if it's happening in a nested ScrollView, as it's default in iOS.

@emilioicai is there a way for me to test this? How would a user explicitly have this turned off?

**Comment by emilioicai** [comment]
@adamjclarkson sorry, by user I meant developer, I sent this PR also to React Native’s repo and copied the description. Developers can disable scrolling to top through a specific parameter.

**Pull request merged**
