### PR TITLE
MM-23739 Empty search state for emoji picker

### PR DESCRIPTION
**Pull request by avasconcelos114**
#### Summary
This PR adds a default empty state for the emoji picker screen

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/14402
JIRA: https://mattermost.atlassian.net/browse/MM-23739

#### Checklist
- [x] Has UI changes
- [x] Includes text changes and localization file updates

#### Device Information
This PR was tested on:
- iPhone 11 (Simulator)
- Pixel 3XL (Simulator)

#### Screenshots
image

### CODE REVIEW

**Comment by enahum** [comment]
@avasconcelos114 I think you could use https://reactnative.dev/docs/flatlist#listemptycomponent instead

**Comment by avasconcelos114** [comment]
@enahum You're 100% correct! I separated that component into its own function and passed it along to the `ListEmptyComponent` prop

Will add the build app label once the build checks pass

**Comment by avasconcelos114** [comment]
@avasconcelos114 Thanks for the review! 

I managed to patch these 4 items (though currently unable to test them on Android)

**Comment by matthewbirtch** [comment]
Looks great on iOS @avasconcelos114. That resolved the items I mentioned. I'll approve once I get to testing on Android a little later

**Comment by avasconcelos114** [comment]
> Android looks good too. Approving with the following change 'No results found for...' title needs to be semibold on android too.

@matthewbirtch 
Ah well, I had set the `fontWeight` to be the exact same on both platforms, but it seems like on android the font looks a bit different (doesn't seem to be any different than regular font weights)

I guess the decision here is whether to keep the `fontWeight` value at **600** (as it is currently):
image

or to increase `fontWeight` to **700** (which bumps it up to look more bold):
image

Let me know which of the two would be best! :)

**Comment by matthewbirtch** [comment]
@avasconcelos114 I think we've run in to this issue before. Let's leave it at 600 then. Thanks!

**Comment by avasconcelos114** [comment]
@matthewbirtch Great! thanks for the review 👍 

@esethna Would it be alright for me to add this to the `v1.35` milestone?

**Pull request merged**
