### PR TITLE
Upgrade Dependencies

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
Upgrade dependencies, held back RN 72 as it showed a performance downgrade on Android 

Note: full app tests are encouraged

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by larkox — APPROVED** [review]

**Comment by lindy65** [comment]
Hey @enahum - please link the related Jira ticket :) Thanks!

**Comment by enahum** [comment]
@lindy65 this is a recurring task, there is never a ticket linked to it

**Comment by lindy65** [comment]
Thanks @enahum - as a full smoke test of the app needs to be done, my concern is that if these PRs aren't tracked in Jira, I will not know to retest after the PR is merged.  I've created a Jira for myself to check the app again once this PR is merged. https://mattermost.atlassian.net/browse/MM-53942

Perhaps the Jira ticket can be cloned for each dependency update going forward?

**Review by lindy65 — APPROVED** [review]
Thanks @enahum - smoke-tested the app on the PR build and did not find any issues.

**Comment by amyblais** [comment]
@enahum There are some conflicts here that need resolving.

**Comment by enahum** [comment]
Yes @amyblais working on it

**Review by cpoile — APPROVED** [review]
Tested and Calls still works on iOs and Android. Thanks Elias!

**Pull request merged**
