### PR TITLE
Removed @babel/polyfill

### PR DESCRIPTION
**Pull request by sergeyzhukov**
#### Summary
Minimum iOS version is 10.3, so @babel/polyfill and check for iOS version < 10.x are no longer needed

### CODE REVIEW

**Comment by enahum** [comment]
@sergeyzhukov this is still needed by Android, or can you confirm otherwise?

**Comment by sergeyzhukov** [comment]
> @sergeyzhukov this is still needed by Android, or can you confirm otherwise?

No need to use babel-polyfill for android because you have updated JSC. Also, babel-polyfill is deprecated. Tested on Android 9.0 emulator and Android 7 device.

**Comment by enahum** [comment]
Hey @sergeyzhukov the PR has some conflicts and for some reason is also including a commit that is not part of the PR.

I also checked that the polyfill is not needed anymore, thanks for this.

**Comment by sergeyzhukov** [comment]
@enahum Updated PR to remove duplicated commit and conflicts, sorry for that

**Pull request merged**
