### PR TITLE
Add vector icons

### PR DESCRIPTION
**Pull request by dmeza**
Added package and followed steps to link native dependencies to both Android and IOs: https://github.com/oblador/react-native-vector-icons

### CODE REVIEW

**Comment by coreyhulen** [comment]
Were did these come from?  We should look at the licensing.

@it33 or @jasonblais

**Comment by coreyhulen** [comment]
Were did these come from?  We should look at the licensing.  I know the github repo is linked, but I don't think he's the original author of the content, but I might be wrong.

@it33 or @jasonblais

**Comment by coreyhulen** [comment]
Found it.  Someone should review the ones we're using.

screen shot 2016-10-19 at 1 43 17 pm

**Comment by jasonblais** [comment]
@dmeza Which of the sets that Corey linked above are we using? 

I can review the licenses to confirm they're okay.

**Comment by dmeza** [comment]
Thank you @jasonblais for the review. MaterialIcons and FontAwesome are the ones that we usually use. We can use any of them that are license friendly.
cc @mfpiccolo

**Comment by jasonblais** [comment]
Thanks @dmeza, both look fine: 
 - [Font Awesome CSS, LESS, and Sass files](https://github.com/FortAwesome/Font-Awesome/) uses the MIT license
 - [MaterialIcons](https://github.com/google/material-design-icons) uses Apache 2.0

If in the future we use other libraries, let me know and I can confirm their licenses are okay

/cc @coreyhulen @it33

**Comment by thomchop** [comment]
@it33, @jasonblais, @coreyhulen: We knew that licensing was important, so I made sure to include this library, and the icon fonts it contained, in the dependencies list in google docs.
I've used all of these icon sets before (mostly outside of react-native). I agree with @dmeza; fontawesome and material icons are the only ones worth using. Or rather, in those two we should be able to find all the icons we need. They're quite extensive. We could even get by with only material icons. They are the most consistently designed.
I suggest that we only include the icon sets we intend to use. If we give contributors the choice between any of them, we'd likely end up depending on more of them than we needed to.
Also I propose that we link these icon font files instead of copying them. That way we avoid bloating the repository and creating large diffs when upgrading to newer versions of the icon sets.

**Comment by thomchop** [comment]
I had no problem with this in the simulator or on device.
I added an icon to the teams list so we have a usage example and a test to see if the icon font is being imported correctly.
select-team-with-icon

**Comment by thomchop** [comment]
@coreyhulen what are your thoughts on the icon sets?
Include all of them for now and remove what we don't end up using?
And would you rather link or copy the font files?

**Comment by coreyhulen** [comment]
@thomchop I think it's fine to include all for now and cull later.  A link is fine since our npm dependency isn't going away in the near future.  Worst case we would checkin node_modules into the release branches or some similar mechanism.

**Comment by thomchop** [comment]
@coreyhulen I may have spoken too soon. Perhaps we should move forward with the font files copied & checked in for now.
For native libs in an RN app, I try to link instead of copying whenever possible. But this is one library we've always copied over on past projects, so I can't say with certainty we won't run into issues there. The safe bet is to merge this as-is. If we later verify that linking will work, we can always purge the files from git history to reduce bloat.

**Pull request merged**
