### PR TITLE
Allow post option modal to close before opening app modal

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

This PR adds a 500ms wait before we open the app form modal, to support the case where the modal was opened from the post option menu. Note that this affects other instances where the modal will be opened, such as from a slash command or the channel header menu.

Some other solutions that would avoid the issue of affecting other components opening the app form:
- the post option can delay its call to `doAppCall`, which would delay the http request to the app
- we can pass an optional param to `doAppCall` to signal that this came from the post option

From a [thread](https://community-daily.mattermost.com/core/pl/jbtk5jge6if68ffp4puzs1imxo) discussing this on community:

> Should this app form be implemented in a different way than a modal to avoid this? Putting a `setTimeout` to handle the case of `post option -> app form` seems hacky, in that I imagine a phone could lag at the same time and possibly require a longer timeout than we set there. Depending on where the timeout is placed in the code, this timeout could also affect other UI components that open the app form, putting an unnecessary wait on opening the form.

#### Ticket Link

Fixes https://mattermost.atlassian.net/browse/MM-34862

#### Device Information

iOS simulator
Version 12.3 (940.20)
SimulatorKit 597.13.0.1
CoreSimulator 732.18.6

and Android Pixel 2

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by DHaussermann** [comment]
@mickmister the build did not appear. Possibly because of failing test in CI?
image

Is this something you're able to look into?

**Comment by DHaussermann** [comment]
@mickmister I have tested 3 different apps and see an unexpected behavior here. 

Trying to open an apps modal via post menu works every-time now. How ever opening a modal from the channel header seems to be failing in this way now. 

Strangely (and I double checked an old build) The header option was not affected by this issue before.

Can you see if you can reproduce this...
1. Add an ngrok tunnel to your local
2. Setup http-hello
3. Install this build on your iOS device
4. Connect via ngrok
5. Open the channel header meny
6. Select `Survey a user`
**Observed** No modal will appear.

**Comment by mickmister** [comment]
@enahum the timeout was causing issues with the channel info screen, so I've removed the timeout and implemented part of the proper solution. The `doAppCall` call is delayed in this case, but it is better than not having the feature working.

**Review by enahum — APPROVED** [review]
Cool.. plase do file a ticket to fix it in its entirety

**Comment by amyblais** [comment]
Yes, it's marked for v1.43 and waiting for @migbot review.

**Pull request merged**
