### PR TITLE
[MM-11997] - Date picker should re-open on previously selected date

### PR DESCRIPTION
**Pull request by mateioprea**
#### Summary

From the original ticket: After selecting a date with the date picker, when the user wants to make an adjustment, the date picker should open on the previously selected date.

react-native-calendars accepts an initial date as ```current```, so I've added this to the state and change it to whatever the selection. I'm also diffing the current date and the selected date to get the ```futureScrollRange``` in months prop. 

There's also a change on the how we manage the currently selected dates. Since ```toDateString()``` was not aware of the timezone, when selecting the first day of a month in the past and reopening the date picker the previous month of the selected date's month was presented. 

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/13223

#### Checklist

- [x] Has UI changes

#### Device Information
This PR was tested on: iPhone 12 Pro, iOS 14.5

#### Screenshots

https://user-images.githubusercontent.com/1246733/130335378-aa5752cb-82de-40cb-a290-1cc624a67122.mov

#### Release Note

```release-note
Fix UI Bug where date picker was jumping back to the current month, after past date selection
```

### CODE REVIEW

**Review by enahum — APPROVED** [review]

**Comment by enahum** [comment]
@josephbaylon done

**Comment by enahum** [comment]
@amyblais in which release version do we include this?

**Comment by amyblais** [comment]
I added v1.49 milestone.

**Pull request merged**
