### PR TITLE
Fixing post draft style to comply with design specs

### PR DESCRIPTION
**Pull request by avasconcelos114**
#### Summary
This PR fixes the UI/UX related concerns raised in the https://github.com/mattermost/mattermost-mobile/pull/3807#pullrequestreview-343639629 by fixing the padding, icon sizes, and opacity colors of some elements in the post draft area

Additional changes include:
- Refactored code to remove repeated logic or styles
- Shortened the `maxHeight` value of the input to `88` when the user is in landscape mode (review required to specify, or remove, this behavior) 

#### Device Information
This PR was tested on: 
- iPhone 11 Simulator
- Pixel 3XL Simulator 
- Galaxy Note9 (Android 9)
#### Screenshots

iOS

Empty draft | Icon disabled | File attachment |
-------|---------------|----------
  |  | 

Android  

Empty draft | Icon disabled | File attachment |
-------|---------------|----------
  |  |

### CODE REVIEW

**Comment by enahum** [comment]
[Android apk](https://pr-builds.mattermost.com/mattermost-mobile/build-pr-3815/Mattermost_Beta.apk)
[iOS ipa](itms-services://?action=download-manifest&url=https://pr-builds.mattermost.com/mattermost-mobile/build-pr-3815/Mattermost_Beta.plist)

**Comment by enahum** [comment]
Thanks @avasconcelos114 I have made further improvements on top of this PR, are you ok if I pushed them to your branch?

**Comment by avasconcelos114** [comment]
You're more than welcome to do so :)

**Comment by chuttam** [comment]
Tremendous work @avasconcelos114 ! Very happy to see these changes coming to life.

I found one edge case issue on an Android device (not 100% sure if this is also an issue on iPhone).

When an error message is displayed and the post is submitted **before** the message auto-disappears, the post box remains open to the larger height and doesn't shrink adjust back to normal.

**Hit error message**
Correct URL 

**Message sent before message disappears**
Correct URL 

**Post box still large**
Correct URL 

@enahum Perhaps best Il go ahead and create a separate bug ticket so as to not hold up the juicy bits from getting to `master`?

**Comment by chuttam** [comment]
Code-wise 👍

**Comment by enahum** [comment]
@chuttam that was introduced with this PR and the animation was done by me. perhaps best to fix it with this one.

Currently held with something else.

**Comment by enahum** [comment]
@chuttam can you please try again before merging.

Thanks.

**Comment by chuttam** [comment]
> @chuttam can you please try again before merging.
> 
> Thanks.

Post box now shrinks back, but in quite a jittery way. Will record a video for this shortly so that we can decide how best to handle.

Also, the most recent permissions handling change in Android isn't bringing up the desired "Just Once/Always" app selector, but is always asking me to pick an app every time I touch the image attachment icon.

**Expected (was working this way at a previous commit)**
Expected 

**Current**
Current

**Comment by chuttam** [comment]
> Post box now shrinks back, but in quite a jittery way. Will record a video for this shortly so that we can decide how best to handle.

Video below:

Jittery close

**Comment by enahum** [comment]
@chuttam video taken on a device running on release mode, sadly the animations are not native as there is no support for height, can you think of an alternative.

As of the Permissions we may look further into that at a different time I guess, definitely not a blocker in my opinion

**Comment by chuttam** [comment]
I took a look at the most recent adjustments to the post box height sizing under error conditions, on a release build. While still a bit of stutter, the movements are much faster and the biggest issue (large space between post list and post box) is gone. The only time there's an unexpected readjustment of sizing and spacing is when the error message disappears, and I guess I can equate this to a similar adjustment when the `so-and-so is typing....` message appears and vanishes.

Opening a new ticket for the "Just Once/Always" Android app selector from the Permissions change.

:shipit:

**Comment by chuttam** [comment]
@avasconcelos114 I'll take care of the cherry-pick issues.

**Pull request merged**
