### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by amyblais**
Are there other pages where the minimum required server version should be updated?

### CODE REVIEW

**Review by enahum — APPROVED** [review]

**Comment by amyblais** [comment]
@enahum Are there any other Github files where the minimum required server version should be updated?

**Comment by enahum** [comment]
@amyblais yes, look in the Fastlane metadara directory

**Review by enahum — APPROVED** [review]

**Comment by enahum** [comment]
Thanks @amyblais

Question not for this PR, but do we want to review an update any other text in those Fastlane files? Not sure if that is actually used in the stores

**Comment by amyblais** [comment]
> Thanks @amyblais
> 
> Question not for this PR, but do we want to review an update any other text in those Fastlane files? Not sure if that is actually used in the stores

We can look into that, not 100% sure who would be the owner.

**Comment by enahum** [comment]
> > Thanks @amyblais
> 
> > 
> 
> > Question not for this PR, but do we want to review an update any other text in those Fastlane files? Not sure if that is actually used in the stores
> 
> 
> 
> We can look into that, not 100% sure who would be the owner.

Marketing maybe?

**Pull request merged**
