### PR TITLE
Gekidou moment locales

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
Fixes: https://github.com/mattermost/mattermost-mobile/issues/6506

```release-note
NONE
```

### CODE REVIEW

**Comment by avinashlng1080** [comment]
I reworked the 'About' screen in this commit - a4e6626e9e281880976855ed50753f17e79d4cb1 

But Github is not showing it in the files changed.

**Comment by enahum** [comment]
Then apply this changes, and I can close this PR and open another one just for the localization stuff

**Comment by enahum** [comment]
@avinashlng1080 what do you want to do here?

**Comment by avinashlng1080** [comment]
@enahum  let's have a PR only for the localization stuff.  I will create a separate PR for the refactored about screen.

**Comment by enahum** [comment]
> @enahum  let's have a PR only for the localization stuff.  I will create a separate PR for the refactored about screen.  

@avinashlng1080 Do you mind removing the code for the about screen on this PR?

**Comment by avinashlng1080** [comment]
> > @enahum  let's have a PR only for the localization stuff.  I will create a separate PR for the refactored about screen.
> 
> @avinashlng1080 Do you mind removing the code for the about screen on this PR?

Sure thing  - sorry I messed that up.  Doing it right away :)

**Comment by enahum** [comment]
Lol @avinashlng1080 this now has way more files than before hehehe

**Comment by avinashlng1080** [comment]
Yes, I know -  weird  - removing them

**Review by avinashlng1080 — APPROVED** [review]

**Comment by avinashlng1080** [comment]
@enahum  it's clean now

**Comment by enahum** [comment]
Thanks @avinashlng1080

**Comment by josephbaylon** [comment]
@enahum This PR fixes the crash issue that shows the modal with the error and restart button. However, I noticed that something is off in the About screen (which I don't see in the latest build 414) even on English locale. Notice the version and build placeholders below (see image).

Not sure if it's introduced in this PR since the latest build 414 doesn't have it. If it's separate issue, I'll go ahead and approve the PR.

about_screen

**Comment by enahum** [comment]
@josephbaylon this PR removed everything that is not the i18n file, thus not part of this PR.

@avinashlng1080 something for you to look in the work you doing

**Pull request merged**
