### PR TITLE
Upgrade to React Native 0.51.0

### PR DESCRIPTION
**Pull request by hmhealey**
Upgrading to RN 0.51 should hopefully fix a random crash that's been affecting a bunch of Android users. It seems like it might have to do with react-native-navigation on RN 0.50 (see discussion of the issue [here](https://github.com/facebook/react-native/issues/16959)), so we're going to upgrade and see if that fixes it like some other users reported.

Nothing in the upgrade affected us except for a naming clash between react-native-linear-gradient and react-native, so that had to be upgraded to fix it.

#### Ticket Link
https://mattermost.atlassian.net/browse/RN-586

#### Device Information
This PR was tested on: iOS Simulator (iPhone 6, iOS 11.2), Nexus 5 (Android 6.0.1)

### CODE REVIEW

**Comment by hmhealey** [comment]
I wanted to upgrade just this dependency to see if it fixed the InterruptedException crash that people were having on Android. We were also thinking of backporting this to 1.5.2 as well so I didn't want to change more than necesasry.

**Comment by enahum** [comment]
Ok I guess we could increase the other dependencies when upgrading to 0.52 which should be in a couple of weeks at most

**Comment by SudoPlz** [comment]
So did the upgrade solve https://github.com/facebook/react-native/issues/16959 ?

**Comment by hmhealey** [comment]
We're not sure yet since we haven't been able to consistently repro the issue. We're hoping to get some better data once this is merged in and these changes have been shipped out later this month.

**Comment by SudoPlz** [comment]
Awesome, I'd love to hear as soon as you find anything out, I've been struggling with that issue for a long time now.

**Pull request merged**
