### PR TITLE
MM-37092 Update Splash Screen to align with new branding

### PR DESCRIPTION
**Pull request by matthewbirtch**
#### Summary
This PR reworks the layout of the splash screen and the image files have been updated to align with new branding.

#### Ticket Link
Jira Ticket: https://mattermost.atlassian.net/browse/MM-37092

#### Checklist
- [ ] Added or updated unit tests (required for all new features)
- [x] Has UI changes
- [ ] Includes text changes and localization file updates

#### Device Information
This PR was tested on: 
- iOS simulator
- iPhone 11 actual device running iOS 14.6
- Google Pixel device running Android 11

#### Screenshots
**iOS - Light**

**iOS - Dark**

**Android - Light**

**Android - Dark**

#### Release Note
<!--
Add a release note for each of the following conditions:
```release-note
Updated the layout and logo used in the splash screen
```

### CODE REVIEW

**Comment by enahum** [comment]
Are we expecting this to include dark mode too?

**Comment by matthewbirtch** [comment]
> Are we expecting this to include dark mode too?

@enahum do we currently support dark mode? It doesn't look like it. I was just looking to update the splash screen with the new branding colors. To be honest this was much more complicated than I expected it to be already. Adding dark mode support for this might be out of my depth, but I can try to look in to it

**Comment by enahum** [comment]
Quedtion is, do we want to include it with this Pr or not.. I could help during the week if that is the case. Gekidou branch does has support for it

**Comment by matthewbirtch** [comment]
I wouldn't see it as a high priority right now since the rest of the app doesn't yet support it, but I say let's go for it if it's easy to do

**Review by enahum — CHANGES_REQUESTED** [review]
I see some files added in this PR that I really doubt if we need them, going to have to take a deeper look at this.

Now for our discussion about dark mode, will the color of the logo remain as in this PR or will it need to be modified for that?

**Comment by matthewbirtch** [comment]
> I see some files added in this PR that I really doubt if we need them, going to have to take a deeper look at this.

Ya, that's entirely possible. Working out the Android splash screen was way more complicated than I imagined. I could have just swapped out the images, but I wanted to see if we could do just the transparent logo cantered in the middle instead of what we had previously. This might help us for dark mode too.
> 
> Now for our discussion about dark mode, will the color of the logo remain as in this PR or will it need to be modified for that?

The logo will need to be white for dark mode, so I'll need to provide the assets for that

**Comment by matthewbirtch** [comment]
@enahum just a heads up that I simplified everything and reduced the number of files changed here.

**Comment by enahum** [comment]
Awesome @matthewbirtch I'll be reviewing some time this week. Do we need to add the file changes into the release assets as well?

**Comment by matthewbirtch** [comment]
> Awesome @matthewbirtch I'll be reviewing some time this week. Do we need to add the file changes into the release assets as well?

I don't really know. Do those automatically get updated some other way? I assumed they needed to be updated manually, but I don't recall know how that works

**Comment by enahum** [comment]
> > Awesome @matthewbirtch I'll be reviewing some time this week. Do we need to add the file changes into the release assets as well?
> 
> I don't really know. Do those automatically get updated some other way? I assumed they needed to be updated manually, but I don't recall know how that works

The files under the aseets folder

**Comment by matthewbirtch** [comment]
> The files under the aseets folder

Is there more to this statement? I'm not sure what you're saying :)

**Review by enahum — APPROVED** [review]
Awesome work @matthewbirtch I've added the missing pieces. We should add this work to Gekidou once this PR is merged

**Comment by matthewbirtch** [comment]
> Awesome work @matthewbirtch I've added the missing pieces. We should add this work to Gekidou once this PR is merged

Thanks @enahum. I guess we should get this reviewed by QA and PM

**Comment by enahum** [comment]
PM if you want in case there is feedback around the designs.. QA is not really needed as they won't be able to test the splash screen for release builds, which I did.

**Review by esethna — APPROVED** [review]
Nice work @matthewbirtch! Stoked to have a dark mode launch screen

**Comment by esethna** [comment]
Removing QA as per Elias's comments

**Pull request merged**
