### PR TITLE
[MM-27354] Progressive image loading

### PR DESCRIPTION
**Pull request by bhargav50**
#### Summary
This PR first loads very tiny preview of an image in the post. Once the post comes into the viewport, the high resolution image is loaded  

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/15644

#### Device Information
This PR was tested on: Poco F1, Android 9

### CODE REVIEW

**Comment by enahum** [comment]
Reminder to test this with and without servers that have the mini-preview available. Also test other images like md inline images, open graph and link previews, not sure if those also have a mini_preview (base64 images)

One thing I noted is that this PR is not making use of the inView to render the previous version of the thumbnail and then load the full image, according to the description looks out of scope but it would be nice to have.

**Comment by enahum** [comment]
@bhargav50 some test seem tl be failing

**Comment by bhargav50** [comment]
There is something messed up while rebasing this branch. I am closing this PR and will reopen again with a new branch.

**Comment by jasonblais** [comment]
@bhargav50 no worries, let us know if you need any help when resubmitting your changes

**Pull request closed without merging**
