### PR TITLE
Invalidate versions for iOS

### PR DESCRIPTION
**Pull request by enahum**
Same as 1.29

### CODE REVIEW

**Comment by enahum** [comment]
@josephbaylon
> User is logged out when upgrading from v1.31.0 and v1.31.1. User is not logged out when upgrading from v1.30 and v1.32.

I guess this is not true for Android, right?

**Comment by josephbaylon** [comment]
@enahum Yes, the behavior is iOS only. Android does not get logged out when upgrading from v1.31.0 and v1.31.1.

**Comment by enahum** [comment]
thanks.

**Pull request merged**
