### PR TITLE
Revert "[MM-21310] Use file URL over preview URL for GIFs"

### PR DESCRIPTION
**Pull request by enahum**
Reverts mattermost/mattermost-mobile#3981

### CODE REVIEW

**Comment by enahum** [comment]
@josephbaylon built!

**Comment by enahum** [comment]
@josephbaylon Wait what!? it should not animate the gifs in the center channel if they were posted from a different client. can you confirm?

**Comment by josephbaylon** [comment]
> @josephbaylon Wait what!? it should not animate the gifs in the center channel if they were posted from a different client. can you confirm?

@enahum GIF does not animate right away is what I meant. I updated the comment above.

**Comment by enahum** [comment]
@josephbaylon ok THANKS!!

**Pull request merged**
