### PR TITLE
Update mmjstool commit with fix on newline to end of file

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
PR build fails on `make i18n-extract-ci` due to mmjstool not adding `\n` when generating en.json.
This PR updates mmjstool to latest commit with fix on newline to end of file.

Actual fix is at https://github.com/mattermost/mattermost-utilities/commit/89543752e9c3b7fe4ad41d3af3821d3923198c20

#### Ticket Link
none

### CODE REVIEW

**Comment by saturninoabril** [comment]
@cpanato I know you're busy at the moment but just like to asked why above comment didn't reflected the correct links both for Android and iOS.  I'm expecting those to be:
- https://releases.mattermost.com/mattermost-mobile-pr/PR-2814/Mattermost_Beta.apk
- https://releases.mattermost.com/mattermost-mobile-pr/PR-2814/Mattermost_Beta.plist

I made the change here - https://github.com/mattermost/platform-private/pull/180/files#diff-7da7f1a6facf88aa11c248e489eb7f05R116.  Maybe something needs to restart to take effect?  Thanks!

**Comment by cpanato** [comment]
@saturninoabril did something change?

**Comment by saturninoabril** [comment]
Yes, I've made the following:
- moved i18n check from shared pipelines to makefile as `i18n-extract-ci` - https://github.com/mattermost/mattermost-mobile/pull/2808
- removed from shared pipelines - https://github.com/mattermost/mattermost-shared-pipelines/pull/14
- updated GH done message - https://github.com/mattermost/platform-private/pull/180

**Comment by saturninoabril** [comment]
@enahum Yes, that's how it used to be and I thought it's handy.  0/5 if it should be explicitly specify in package.json?  Let me know if need to update.

**Comment by saturninoabril** [comment]
@enahum Added to package.json

**Pull request merged**
