### PR TITLE
[MM-49006] Handle Plugin related events

### PR DESCRIPTION
**Pull request by javaguirre**
#### Summary

Plugin WS events that don't need to do any logic, but need to be handled. :-)

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-49006

#### Checklist

- [ ] Added or updated unit tests (required for all new features)
- [ ] Has UI changes
- [ ] Includes text changes and localization file updates
- [ ] Have tested against the 5 core themes to ensure consistency between them.

#### Device Information
This PR was tested on: 

#### Release Note

```release-note
Handle Plugin related events
```

### CODE REVIEW

**Comment by larkox** [comment]
CI is failing because missing definitions.

**Comment by javaguirre** [comment]
> CI is failing because missing definitions.

humm, didn't expect that, I'll check it out.

**Comment by javaguirre** [comment]
@larkox Fixed, sorry about that!

**Comment by javaguirre** [comment]
Are we merging this @larkox ? 👼

**Comment by javaguirre** [comment]
I think I misunderstood, I'll check what's in the webapp and add the same events here. 👍

**Review by larkox — APPROVED** [review]

**Comment by larkox** [comment]
I'm going to skip the QA Review since there is nothing to test.

**Pull request merged**
