### PR TITLE
MM-18901 Update commit hash of mattermost-redux and cleanup initial state of requests.preferences

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
This is a follow up PR to https://github.com/mattermost/mattermost-redux/pull/1027#discussion_r368868492 so the cleanup is not forgotten.

#### Ticket Link
Jira ticket - [MM-18901](https://mattermost.atlassian.net/browse/MM-18901)

### CODE REVIEW

**Comment by saturninoabril** [comment]
@josephbaylon Do you have screenshot of the error? Probably related to https://github.com/mattermost/mattermost-mobile/pull/3837.  Did update to master, please take a look again.

**Comment by josephbaylon** [comment]
> @josephbaylon Do you have screenshot of the error? Probably related to and fixed by #3837. Did update to master, please take a look again.

Screen Shot 2020-01-21 at 10 47 23 AM

**Comment by saturninoabril** [comment]
Works for me now on the updated commit.  Please try a new build.

**Comment by josephbaylon** [comment]
> Works for me now on the updated commit. Please try a new build.

@saturninoabril  It now works for me only on Android emulator/physical device. However, it still crashes on iOS device
IMG_0001

**Comment by saturninoabril** [comment]
@josephbaylon I installed [this build](https://community-release.mattermost.com/core/pl/7gmomi3ojiytm8ua3j7fabedww) and works for me.  Same case on iOS simulator. We can connect in a DM to figure it out.

**Pull request merged**
