### PR TITLE
Parse + merge nested response headers to fix content-type checking

### PR DESCRIPTION
**Pull request by csduarte**

### CODE REVIEW

**Comment by enahum** [comment]
@thomchop take a look when you can

**Comment by thomchop** [comment]
@enahum Sorry, didn't see this yesterday. What do you mean by that? Disable json parsing for the login response? I was aware that we'll eventually need to do that for all those endpoints that return a non-json response yet have a content-type of application/json. I agree that we'll need that logic soon, but I wasn't trying to solve for that right now. We should create a ticket for that so we don't forget.

**Comment by thomchop** [comment]
@enahum, @hmhealey How do you propose that we detect these false json responses? Initially we can disable them on a per-action/endpoint basis with an option arg (`doFetchWithResponse(parseJson: false)`), but it would be great if we could correct the `content-type` in api v4.

**Comment by hmhealey** [comment]
I like that idea, but maybe call it `parseHeaders` just so that it won't be mixed up with the fact that we automatically parse the json in the body

**Comment by thomchop** [comment]
@enahum Ok I removed the previous hack for nested headers. This should be ready now. Do you wanna merge it or should I?

**Comment by enahum** [comment]
@thomchop the repo is set so at least one person has to review to be able to merge, so in this case I'll merge it :)

**Pull request merged**
