### PR TITLE
Introduce react-native-web

### PR DESCRIPTION
**Pull request by oli-ver**
Introduce react-native-web following the steps from this blogpost: https://arry.medium.com/how-to-add-react-native-web-to-an-existing-react-native-project-eb98c952c12f
All platform dependend classes have been duplicated from the android implementation for now (simply to allow building for now)

### CODE REVIEW

**Comment by enahum** [comment]
Hi @oli-ver I've seen your post here https://github.com/mattermost/mattermost-mobile/issues/5124 but I wonder why would this go in the mobile app and not in the webapp?

For this approach maybe it would make more sense to have some sort of component library that could be used in both  projects... In my opinion having this rn-web components here does not make much sense.

Thoughts ?

**Comment by enahum** [comment]
@deanwhillier FYI

**Comment by oli-ver** [comment]
@enahum that's actually a good point. I'll have a closer look at the web app. To be honest I did not think this would be the same (but now that you say it I am not so sure anymore 😀 ).

I thought the app experience could be better if react-native-web was used. If not, why at all care to develop native apps? Wouldn't the Webapp also work for iOS and Android?

**Comment by enahum** [comment]
@oli-ver we do actually have the Mattermost classic apps that are a webview, now the user experience is definitely not as good as with native apps even written in RN

**Comment by oli-ver** [comment]
Ok, this is why I thought this could be different when using react-native-web. Unfortunately it does not yet work. I am not very experienced with webpack and react, but at least it's building now. 

Right now I simply package the web address of my mattermost instance as web App locally on the phone. There is an app to do that for Ubuntu touch, so this use case is somehow covered.

Would still be interesting to get the "real thing" in the OpenStore. And after this is ready I supposed it could be used on other platforms as well.

**Comment by enahum** [comment]
I still fail to see how this is work fits in the mobile app repo, if what you want to accomplish is to run MM in Ubuntu Mobile and have it listed in the store, perhaps you are better of building a shim with a webview that renders the webapp

**Comment by oli-ver** [comment]
Well, in this case one can do that using the app I mentioned (https://github.com/timsueberkrueb/webber/), input the mattermost instance's URL and is done.

If on the other hand packaging as react-native-web one would package and provide the app in the OpenStore and possibly provide more features to the user (like push messages for example, but not yet sure how this works in Ubuntu Touch).

Still: why did you switch from the mattermost-classic approach to a native app? I fail to grasp the reason why packaging and installing an app that provides (nearly) all features of the native app would not benefit from all the reasons you created it for ios and android. Is this really so different?

**Comment by oli-ver** [comment]
@enahum Should I close the PR?
Just again a summary of what my proposal:

- Build mattermost-mobile as web package with react-native-web
- Package web package content for Ubuntu Touch with [clickable's local html](https://clickable-ut.dev/en/latest/app-templates.html#html) mode
- Publish package to open-store.io

If you think one should just use the mattermost webapp, I'll just keep on using Mattermost in the browser / web app or perhaps I'll try to switch to a Matrix bridge solution.

**Comment by enahum** [comment]
Yup lets close this PR, react-native-web would be something to use in the webapp instead.

**Pull request closed without merging**
