### PR TITLE
[Gekidou] bug fixes

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
* Add space to bottom of channel content
* Clicking username/avatar in channel crashes app
* Loading state of server item button is misaligned
* user is typing shows on channel rather than thread and styling

#### Ticket Link
* https://mattermost.atlassian.net/browse/MM-44005
* https://mattermost.atlassian.net/browse/MM-43998
* https://mattermost.atlassian.net/browse/MM-44033
* https://mattermost.atlassian.net/browse/MM-44035

```release-note
NONE
```

### CODE REVIEW

**Review by larkox — APPROVED** [review]

**Comment by matthewbirtch** [comment]
> Add space to bottom of channel content

✅ Looks good

> Clicking username/avatar in channel crashes app

✅ No crash now - just the temp alert dialog which is better

> Loading state of server item button is misaligned

✅ Alignment fixed now

> user is typing shows on channel rather than thread and styling

❎ I am not seeing the indicator at all now when another user is typing in either the channel or the thread view

**Comment by enahum** [comment]
>  I am not seeing the indicator at all now when another user is typing in either the channel or the thread view

yeah, me neither,.. let me check what happened

**Comment by matthewbirtch** [comment]
> @matthewbirtch maybe test on a channel that does not have a lot of users I believe there is a restriction that does not send the WS when there are a lot of users IIRC

I was testing on a cloud test server of mine which only has a couple users. For some reason it seems the WS evens were not firing properly

**Comment by enahum** [comment]
@matthewbirtch if you open the server list, does it show an alert that the Server is unreachable ?

**Comment by matthewbirtch** [comment]
> @matthewbirtch if you open the server list, does it show an alert that the Server is unreachable ?

no, it's showing normal

**Review by matthewbirtch — APPROVED** [review]
Approving this. After discussion with @enahum, there are issues with cloud websocket and he needs to reach out to SRE team. This is not related to this PR specifically though and is more of a general issue with cloud servers and the mobile app WS events

**Pull request merged**
