### PR TITLE
[MM-25780] Pass device ID as query params 

### PR DESCRIPTION
**Pull request by hahmadia**
#### Summary

Pass Device ID to query params of SSO login 

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-25780

### CODE REVIEW

**Comment by hahmadia** [comment]
> I dont see a need for this, to me the session length should be handled all server side

@enahum 
It is being handled server side? I just need the device ID because a function `DoLogin` gets called and it takes in a device ID to set the session length and device ID on that session length.

https://github.com/mattermost/mattermost-server/blob/master/app/login.go#L113

Currently we are always passing a empty string to DoLogin when we login via SAML or OAUTH because we aren't taking into account mobile (https://github.com/mattermost/mattermost-server/blob/master/web/saml.go#L145) so I just take the device ID query parameter and pass it into that function in my new server PR. If the device ID param doesn't exist, it simply passes a empty string.

**Comment by enahum** [comment]
I mean is fine to include, but it is error prone, so the better approach would be to mark the session as a mobile regardless of the deviceId token being sent

**Comment by hahmadia** [comment]
> I mean is fine to include, but it is error prone, so the better approach would be to mark the session as a mobile regardless of the deviceId token being sent

I see. Out of curiosity, how would it be error prone?

**Comment by enahum** [comment]
> how would it be error prone?

The deviceId may not be set at this point either cause of an issue requesting the id from apple/firebase or you may have notifications turned off

**Comment by hahmadia** [comment]
> > how would it be error prone?
> 
> The deviceId may not be set at this point either cause of an issue requesting the id from apple/firebase or you may have notifications turned off

Ah ok glad you brought that up because I assumed device ID was always set as long as you used Mattermost mobile app. Wasn't aware it was related to notifications. I guess I can close this ticket then.

**Pull request closed without merging**
