### PR TITLE
[MM-14593] Add password type for Interactive Dialogs

### PR DESCRIPTION
**Pull request by goku321**
#### Summary
Added password type for Interactive Dialogs by passing `secureTextEntry` prop

#### Ticket Link
[#10460](https://github.com/mattermost/mattermost-server/issues/10460)

#### Checklist
- [x] Added or updated unit tests (required for all new features)
- [x] Has UI changes
#### Device Information
This PR was tested on: App version 1.21.1 (Build 209) built for this PR on Android 9 and iOS 12

#### Screenshots
2998Android
2998iOS

### CODE REVIEW

**Comment by prapti** [comment]
@enahum Can someone from the Apps team help build the APK for me? The one I tried using the `Build Apps for PR` label failed. Thanks!

**Comment by enahum** [comment]
@prapti will do soon.. I'll ping you once is done

**Comment by hanzei** [comment]
Can this be merged?

**Comment by prapti** [comment]
@hanzei Yes! Please merge it :)

**Comment by hanzei** [comment]
For some reason I can't merge the PR.
@jwilander @ali-farooq0 Would you please take care of this?

**Comment by enahum** [comment]
Merged

**Pull request merged**
