### PR TITLE
[Gekidou] bug fixes found with e2e tests

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
* Fixes search users in Create Direct Message
* Fixes the style when  user row is pressed (underlayColor on iOS)
* Prevent the modals Create Direct Message & Browse Channels from being dismissed with a swipe as scrolling the list was causing the screen to be dismissed on iOS
* With the option `Set Header` in the channel intro, we now only allow the header to be edited.
* ThreadFollowButton did not have the `t` function surrounding the `id`

```release-note
NONE
```

### CODE REVIEW

**Review by josephbaylon — APPROVED** [review]
LGTM. I tested the fixes and they work fine.

@enahum I wonder if we should also prevent the Create Channel modal from being dismissed when swiped down or is that still intended behavior.

**Comment by enahum** [comment]
> LGTM. I tested the fixes and they work fine.
> 
> @enahum I wonder if we should also prevent the Create Channel modal from being dismissed when swiped down or is that still intended behavior.

We could, any reason why to do it ?

**Comment by josephbaylon** [comment]
@enahum I think that view is a scroll view as well and user might need to scroll on a small screen. Perhaps not necessary on bigger screens.

**Comment by enahum** [comment]
done

**Comment by josephbaylon** [comment]
LGTM. Verified Create Channel is not dismissed when swiped down.

**Review by anurag6713 — APPROVED** [review]

**Review by larkox — APPROVED** [review]

**Pull request merged**
