### PR TITLE
[Gekidou MM-46847] allow wrapping long channel text in autocomplete

### PR DESCRIPTION
**Pull request by jfrerich**
#### Summary
This PR allows wrapping long channel name text into two lines. @matthewbirtch, if the two lines are not desired, the only other option is to use one line, but none of the slug will be shown with long channel names.

It also removes an unused, but defined styling object

##### Tablet 
image

##### Mobile
image

#### Checklist

- [ ] Added or updated unit tests (required for all new features)
- [ ] Has UI changes
- [ ] Includes text changes and localization file updates
- [ ] Have tested against the 5 core themes to ensure consistency between them.

#### Device Information
This PR was tested on: 

#### Release Note

```release-note

```

### CODE REVIEW

**Comment by enahum** [comment]
I think the idea is to add an ellipsis not wrap into multiple lines.

@matthewbirtch to confirm

**Comment by jfrerich** [comment]
Simple change if that is desired.  

image

**Comment by matthewbirtch** [comment]
> I think the idea is to add an ellipsis not wrap into multiple lines.
> 
> @matthewbirtch to confirm

Yes, you're right @enahum. The intent is to truncate channels to one line so we can show as many rows as possible in a small space. The slug will certainly be truncated when channel names are long, but I'm ok with that since it's secondary information anyway.

**Comment by jfrerich** [comment]
Updated to restrict to one line per channel.

**Review by larkox — APPROVED** [review]
LGTM. Just a note, in other places, if I remember correctly, we have opted for showing a bit of both (if both fill the whole thing, it would use the space something like 70/30).

Is this more desirable, or do we prefer to show the full display name without showing the `~` name? CC @matthewbirtch

**Comment by matthewbirtch** [comment]
> LGTM. Just a note, in other places, if I remember correctly, we have opted for showing a bit of both (if both fill the whole thing, it would use the space something like 70/30).
> 
> Is this more desirable, or do we prefer to show the full display name without showing the `~` name? CC @matthewbirtch

I think it feels odd to show two •••. Personally, I think it's better to favor the display name.

**Review by matthewbirtch — APPROVED** [review]
LGTM

**Review by jgilliam17 — APPROVED** [review]
Thanks @jfrerich 
Tested, looks good to merge.
Verified long channel names are truncated on the autocomplete.

**Review by AshishDhama — APPROVED** [review]

**Pull request merged**
