### PR TITLE
Upgrade react-native-device-info dependency

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
Affected Areas:
- Permission dialogs to display the app name
- App build number and version should be available: Easier to see it in the About screen or Report a Problem
- Detect if the device is a phone or tablet

Upgrade changelog does not report any breaking changes.

### CODE REVIEW

**Comment by enahum** [comment]
@josephbaylon 👓 ??

image

**Comment by josephbaylon** [comment]
@enahum Looks like that already exists in the current release builds (that's `app info`). I thought `device info` would be info about the actual device. If not, I'll go ahead approve the PR.

**Comment by enahum** [comment]
Yes, I made a mistake in the description, is about the app.

Thanks for double checking

**Pull request merged**
