### PR TITLE
1.44 fixes

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
fixes get status as soon as appstate is in the foreground and re-render post list when theme changes

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-36360
https://mattermost.atlassian.net/browse/MM-36361

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by anurag6713 — APPROVED** [review]
LGTM 👍

**Comment by amyblais** [comment]
@avinashlng1080 @josephbaylon Please help prioritize this PR review.

**Comment by avinashlng1080** [comment]
This PR looks good to me @amyblais

**Review by josephbaylon — CHANGES_REQUESTED** [review]
@enahum The theme issue looks fixed. However, the status issue still persists

Steps,
1. Change status from Online to Away,
2. Slide app halfway before closing app
3. Close and re-open app

Expected:
2. Status remains as Away
3. Status remains as Away

Actual:
2. Status becomes Offline
3. Status remains Offline

**Comment by enahum** [comment]
@josephbaylon for the status

Expected: 
* Status becomes offline
* Status comes back to away


https://user-images.githubusercontent.com/6757047/121713808-3c9be480-caab-11eb-986b-8f835bce1ef8.MP4

**Comment by josephbaylon** [comment]
@enahum I'm getting a different behavior and the status stays Offline for me. Maybe @amyblais can also test it to see if she gets the right behavior.

**Comment by enahum** [comment]
@josephbaylon can you share a similar video so I can see what you are seeing ?

**Comment by josephbaylon** [comment]
@enahum Here's the video
https://user-images.githubusercontent.com/487991/121716708-326eeb80-ca95-11eb-8852-21320edad11e.MOV

**Comment by enahum** [comment]
@josephbaylon yes is not reproducing for me,.. How long does it take for you to get the away status?

**Comment by josephbaylon** [comment]
@enahum When I switch from Online to Away, it happens immediately. But when I slide up the app halfway, the status switches from Away to Offline. When I close the app and the re-open, the status stays Offline.

I can approve this PR if I'm the only one experiencing it. But I wanted to have Amy test it first to make sure.

**Comment by amyblais** [comment]
@enahum How do I test it?

**Comment by josephbaylon** [comment]
@enahum @amyblais I asked other QA to repro the issue and @ogi-m was able to repro what I'm seeing. Also, note that only mobile gets stuck in Offline status while web switches to Away correctly.

**Comment by josephbaylon** [comment]
@enahum Here's more data:
|Tester|iOS version|Can repro|
|:---|:---|:---|
|@ogi-m|14.6|yes|
|@prapti|14.4.1|no|
|@stevemudie|14.6|yes|

I'm also on 14.6. May have something to do with iOS version?

**Comment by enahum** [comment]
is reproing for me on the build published in the channel and I'm on 14.5.1, but it should have absolutely nothing to do with the OS version.. wondering why, going to check again with my local branch and see if here was an issue while building this PR

**Comment by enahum** [comment]
@josephbaylon ok I've pin pointed the issue.. there are some who have (don't ask me why)  some user's registered without an empty ID in the statuses reducer, then the empty string is being sent to the server when retrieving the statuses and that makes the server to respond with an error code causing the status not to update properly. <- this was an existing issue

I've pushed a commit that filters the empty userIds from the request and now it should work fine.

Thanks for testing.. now let's do another round just to be sure (I've triggered the build)

**Comment by enahum** [comment]
We should also improve on the server to discard those invalid ids and return the valid ones. @amyblais perhaps you want to create a ticket for that? 0/5

**Comment by amyblais** [comment]
I opened a ticket here: https://mattermost.atlassian.net/browse/MM-36398.

**Review by josephbaylon — APPROVED** [review]
LGTM. Status now remains to whatever the user switches it to.

**Pull request merged**
