### PR TITLE
Add gradle lockfile

### PR DESCRIPTION
**Pull request by larkox**
#### Summary
Add gradle lockfile.

There are two ways to write the lock file:
- Passing an argument to the android build (`npm run android -- --extra-params --write-locks`)
- Running the dependencies task on gradle with write locks (`android/gradlew app:dependencies --write-locks`)

To update all current locks we can run the depdencies task with update locks:
`android/gradlew app:dependencies --update-locks "*:*"`

#### Ticket Link
Fix https://mattermost.atlassian.net/browse/MM-57196

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by enahum** [comment]
Lgtm but please document how to update it when adding/updating dependencies both direct and those included in RN libraries

**Comment by larkox** [comment]
@enahum Where do you think is the best place to document this?

**Comment by enahum** [comment]
> @enahum Where do you think is the best place to document this?

@larkox Maybe the dev docs? And perhaps also in the description of the PR?

**Comment by esarafianou** [comment]
@jupenur can you review the PR for Security?

**Review by jupenur — APPROVED** [review]

**Review by enahum — APPROVED** [review]

**Pull request merged**
