### PR TITLE
Fix reply from permalink

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
When opening the reply screen from a permalink, keep the current channel unless the team changes.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-54969

#### Release Note
```release-note
Fixed remain in current channel when replying a post from the permalink view
```

### CODE REVIEW

**Review by larkox — APPROVED** [review]
LGTM, but I wonder if this will break anything in the thread view (or further down) that may rely on current channel id. Not sure if there is anything, but would be great to check.

**Comment by enahum** [comment]
As far as I can tell there is nothing, nut a round of proper QA should be good

**Comment by lindy65** [comment]
Hi @enahum - is there a Jira ticket for this PR or should I create one? (I couldn't find one....)

**Comment by enahum** [comment]
> Hi @enahum - is there a Jira ticket for this PR or should I create one? (I couldn't find one....)

No Lindy, I ffound the bug and just fixed it

**Review by lindy65 — APPROVED** [review]
Thanks @enahum - looks good to me 👍

**Pull request merged**
