### PR TITLE
MM-21342 Fix leading zero on post by using react-intl by default and fallback to moment-timezone for unsupported locale

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
- fixes leading zero by rendering post time with react-intl as default and moment-timezone as fallback (for those unsupported timezone of react-intl)
- add [@testing-library/react-native](https://github.com/testing-library/native-testing-library#readme) to better test component rendering.  It offers APIs which are aligned with [testing-library](https://testing-library.com/) - growing adoption in testing due to its better philosophies and practices. With enzyme, this component (FormattedTime) is untestable since `mount` is not supported and react-intl does not generate formatting/localization. 

Note: this renders the same as the webapp - https://github.com/mattermost/mattermost-webapp/pull/4661

#### Ticket Link
Jira ticket: https://mattermost.atlassian.net/browse/MM-21342

#### Device Information
This PR was tested on: iOS simulator and Android emulator 

#### Screenshots
Post time for __de, en, fr, it, pl, pt-BR, ru__
en

Post time for __es__
es

Post time for __nl, ro__
nl

Post time for __tr__
tr

Post time for __uk__
uk

Post time for __ko__
ko

Post time for __zh-CN, zh-TW__
zh-CN

Post time for __ja__
ja

### CODE REVIEW

**Comment by saturninoabril** [comment]
I'm convince that the approach here is better to take advantage of localization which react-intl offers. The issue with react-intl will have fallback with moment-timezone, so it's taken care of.
re: unrelated changes - If you're referring to updates in other snapshot like from `ScrollViewMock` to `ScrollView`, it's due to new package introduce which I think represents correctly than what we currently have.

I'm okay with your recommendation if that's final.  Let me know once again and I'll update accordingly.

**Comment by enahum** [comment]
@saturninoabril can you confirm different timezones are applied successfully on both android and ios? I recall having to use moment as timezones were not working correctly

**Comment by saturninoabril** [comment]
@enahum Thanks for checking. Unfortunately, I don't have the opportunity to fully verify this in actual devices.  I've requested additional reviews/verification from other QA to test per your suggestion.

**Comment by josephbaylon** [comment]
I built the PR using
git checkout -b saturninoabril-MM-21342 master
git pull git://github.com/saturninoabril/mattermost-mobile.git MM-21342

make pre-run
make run-ios

1. When I change the language to non-english, e.g. french, I get his error
`console.error: "[React Intl] Missing message: "intro_messages.creatorPrivate" for locale: "fr", using default message as fallback."`

**Comment by enahum** [comment]
@josephbaylon that is because the string is not yet present in french. You can tap on dismiss there

**Comment by josephbaylon** [comment]
LGTM

**Comment by enahum** [comment]
@josephbaylon does this look good on the actual devices in release mode?????

**Comment by josephbaylon** [comment]
@enahum I only have Android personal device. I don't have iOS device. I tried to build the apk using `make build-android` and installed Mattermost_Beta.apk onto my Android device. Once installed, I tried to load the app but it's just stuck on logo splash screen. I tried reinstalling it several times but still the same result.

**Comment by enahum** [comment]
@josephbaylon to build the app with that command you need to follow the docs on `how to build your own`

Recommendation do the following:
* make clean
* make pre-run
* react-native run-android --variant=Release

Also you should talk with your lead and get yourself an iOS device ;)

**Comment by josephbaylon** [comment]
@enahum This is the one I followed last time --> https://developers.mattermost.com/contribute/mobile/build-your-own/android/

Can you point me to the docs for How to build your own?

I've already requested the devices last week. They just approved today so will have to wait for them to arrive.

I followed your steps and I get this error after `react-native run-android --variant=Release`,

`
BUILD FAILED in 2s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installRelease -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Task 'installRelease' not found in project ':app'. Some candidates are: 'uninstallRelease'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

    at checkExecSyncError (child_process.js:616:11)
    at execFileSync (child_process.js:634:13)
    at runOnAllDevices (/Users/joseph.baylon/Projects/mattermost/original/mattermost-mobile/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:39)
    at buildAndRun (/Users/joseph.baylon/Projects/mattermost/original/mattermost-mobile/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:158:41)
    at then.result (/Users/joseph.baylon/Projects/mattermost/original/mattermost-mobile/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:125:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
`

**Comment by enahum** [comment]
@josephbaylon I'm building the PR and the links will get published in the QA channel

**Comment by enahum** [comment]
Tested on the devices for Both Android and iOS and is working as expected. merging.

**Comment by josephbaylon** [comment]
@enahum I was able to test using the Circle build APK and looks fine.

**Pull request merged**
