### PR TITLE
RN-74 Added updated markdown code block view

### PR DESCRIPTION
**Pull request by hmhealey**
Some small notes:
1. The line numbers are centred if they're only 1 digit or right-aligned when there's 2 or more digits. I tried having them all right-aligned as per spec, but it didn't look quite right
2. Language names are only displayed when they would be displayed by the web app (ie when the web app supports them for syntax highlighting).

Waiting on the PR to change `makeStyleSheetFromTheme`. The important changes for this PR are here: https://github.com/mattermost/mattermost-mobile/commit/50f0f9a892c8851ff0f199bed1278febedc68b6d

#### Ticket Link
https://mattermost.atlassian.net/browse/RN-73

#### Checklist
- Has UI changes
- Includes text changes and localization file updates

#### Device Information
This PR was tested on: iOS Simulator (iOS 10.3), Nexus 5 (Android 6.0.1)

### CODE REVIEW

**Comment by enahum** [comment]
@hmhealey just merged the other PR

**Comment by hmhealey** [comment]
I just noticed the line numbers aren't lined up with the code on Android, so I'll need to fix that

**Comment by hmhealey** [comment]
Line heights fixed

**Comment by enahum** [comment]
@hmhealey needs rebase

**Pull request merged**
