### PR TITLE
WIP: MM-16263 Post draft improvement

### PR DESCRIPTION
**Pull request by avasconcelos114**
#### Summary
This PR would replace the `+` attachment button in the post draft with several quick-action buttons instead

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/12617

#### Checklist
- [x] Added or updated unit tests (required for all new features)
- [x] Has UI changes

#### Device Information
This PR was tested on: 
- Samsung Galaxy Note9 (Android 9)

#### Screenshots
image

### CODE REVIEW

**Comment by avasconcelos114** [comment]
Thank you for the help patching some things up!

I went ahead and fixed an incorrect import I had for the `DocumentPicker`. 

Ideally, the basic functionality should be there, but the implementation will look quite funky because all I did was to separate the `+` attachment button into a bunch of separate buttons, each with little bits of functionality spread around.

This likely will be needing a lot of refactoring, separating some common functionality that each new button component has (like the `uploadFile` function that both image and file upload are using), and possibly dismantling the old attachment button given that it's only going to be used by the `profile_picture_button` component

**Comment by jasonblais** [comment]
Thanks @avasconcelos114 for the contribution! Let me know if you have any questions about next steps :)

**Comment by avasconcelos114** [comment]
Ah yep, for now the PR is at a point where most of the functionality is in there.

As I discussed privately with Elias, I may need a bit of help getting the `mediaType` setting for the camera to work with the `mixed` option, so that users can both take pictures and video by hitting the camera icon at the bottom.

I'll give it another shot at figuring out what's wrong, as well as trying to test things on an iOS device to see if the camera options work in there

**Comment by enahum** [comment]
There are a bunch of follow up tickets in the mobile kanban board

**Comment by avasconcelos114** [comment]
Ah just managed to find all the related tickets, I see a couple that are reasonably easy to fix.

Will go ahead and patch those up first

**Comment by enahum** [comment]
We are using this as the base branch

**Comment by avasconcelos114** [comment]
Just to clarify things on my end, does that mean you'd like me to create new branches and submit separate PRs against this branch for each of those tickets?

**Comment by enahum** [comment]
Closing this PR in favor a the post-draft feature branch https://github.com/mattermost/mattermost-mobile/tree/post-draft

**Pull request closed without merging**
