### PR TITLE
Fix race condition when showing the turorial

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
Fix race condition when showing the tutorials for user lists and server list

#### Ticket Link
Jira ticket: https://mattermost.atlassian.net/browse/MM-54575

#### Release Note
```release-note
Fixed the app becoming unresponsive when a tutorial for the user or server list is partially showed
```

### CODE REVIEW

**Review by larkox — APPROVED** [review]
LGTM

**Comment by larkox** [comment]
Does this fix https://mattermost.atlassian.net/browse/MM-54575 ? Or do you think the reason may be different?

**Comment by enahum** [comment]
> Does this fix https://mattermost.atlassian.net/browse/MM-54575 ? Or do you think the reason may be different?

It definitely should fix it

**Comment by lindalumitchell** [comment]
Rebuilding the apps as I needed to have a new UDID added to the list.

**Comment by lindy65** [comment]
Thanks for picking this one up for me @lindalumitchell 🤗

**Comment by lindalumitchell** [comment]
Still not able to install the PR build of the app; trying to rebuild one more time in case I tried it too soon last time.

**Review by lindalumitchell — APPROVED** [review]
Verified on iPhone 13 that the issue did not repro for me on iOS 16, then did repro on iOS 17 as expected. Then verified issue is fixed after installing the PR build. 👍

**Pull request merged**
