### PR TITLE
Fix file attachment limited to one file

### LINKED ISSUE #7273: Bug? Can't attach multiple documents simultaneously
Per Mattermost guidelines, GitHub issues are for bug reports: <http://www.mattermost.org/filing-issues/>.

For troubleshooting see: http://forum.mattermost.org/.
For feature proposals see: http://www.mattermost.org/feature-requests/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://about.mattermost.com/report-security-issue/).
3. [File a new issue](https://github.com/mattermost/mattermost-mobile/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed.

#### Summary
I'm able to attach multiple image files in one go. But, I'm not able to do the same for attaching documents. 

### Environment Information
  - Device Name: ?
  - OS Version: Ubuntu (Cloudron)
  - Mattermost App Version: 2.2.0
  - Mattermost Server Version: 7.9.1

#### Steps to reproduce
Try for any chat, using the latest Android app.

#### Expected behavior
I expected to be able to attach multiple files simultaneously, to any chat.

This is actually one of the features due to which I'm switching over to Mattermost, as users often need to share multiple files and our previous chat app didn't allow attaching multiple files in one message.

This functionality is quite necessary.

### PR DESCRIPTION
**Pull request by larkox**
#### Summary
Fix file attachment only allowing for one file, instead of many files.

#### Ticket Link
Fix https://mattermost.atlassian.net/browse/MM-52145
Fix #7273 

#### Release Note
```release-note
Now you can select several files when attaching files to a message.
```

### CODE REVIEW

**Comment by enahum** [comment]
Please make sure the UX is correct when trying to attach more than the allowed (qty)

Have not tested, but this differs from images as for images you set a limit.

Anyway, see you tomorrow :)

**Comment by larkox** [comment]
@enahum The `addFiles` function has a safeguard for that. If you try to upload more files than permitted, it will not upload them, and show an error stating that you can only upload X number of files.

Would be better UX to limit the amount of files to upload from the beginning, but the library does not offer that option (not sure if the OS even offers the option).

**Comment by enahum** [comment]
I guess the safeguard is fine

**Review by devinbinnie — APPROVED** [review]

**Comment by arladmin** [comment]
I just updated my Mattermost android app and tried to select multiple documents to attach.
Doesn't work.
Still able to select only 1 document at a time.

**Comment by enahum** [comment]
> I just updated my Mattermost android app and tried to select multiple documents to attach.
> Doesn't work.
> Still able to select only 1 document at a time.

This is set to ship with the 2.4 release, not the one released today.

You could use the beta app to try it out as it should have been included

**Comment by arladmin** [comment]
Thanks for the info!

Will keep an eye out for the next release.

**Pull request merged**
