### PR TITLE
Add commit buttons in form instead of on navigation

### PR DESCRIPTION
**Pull request by larkox**
#### Summary
When a form defines several submit buttons, we used to put them in the navigation bar. Due to the limited space, this was not a good idea.

The solution was to add the buttons at the end of the form. This is the first iteration towards that. Programming logic is in place, the only missing parts are design tweaks.

Right now if no custom buttons are defined, the submit button will appear in the navigation bar. If custom buttons are defined, they will be at the bottom.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-33360

#### Screenshots
Screenshot from 2021-06-04 11-28-01

#### Release Note
```release-note
None
```

### CODE REVIEW

**Review by jfrerich — APPROVED** [review]
LGTM!

**Review by enahum — COMMENTED** [review]
Will this PR conflict with https://github.com/mattermost/mattermost-mobile/pull/5394 ?

**Comment by larkox** [comment]
@enahum Yes, it will.

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- `button1` - `button4` submit the modal succesfully
- Buttons layout is vertical in RN
- No submit button at the top of the modal Cancel `x` is functional
- Regression tested convention submit (Using ServiceNow) with no issues
- Tested on Android and iOS

LGTM!

**Review by enahum — APPROVED** [review]

**Pull request merged**
