### PR TITLE
MM-37517 Thread permalink

### PR DESCRIPTION
**Pull request by anurag6713**
#### Summary
* For Thread posts permalink, when CRT is enabled we need to show thread messages instead of channel messages.
* Link previews disappear when the thread is followed as the thread object might not contain all post data.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-37517
https://mattermost.atlassian.net/browse/MM-39525

#### Device Information
This PR was tested on: iPhone 12, iOS 15.0

#### Screenshots

Simulator Screen Shot - iPhone 12 - 2021-10-18 at 17 55 14

https://user-images.githubusercontent.com/3680799/137735923-75106772-2368-49ae-b6c5-6737873aee67.mp4

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by Willyfrog** [comment]
friendly ping @enahum

**Review by enahum — APPROVED** [review]
yay, so much better.

**Comment by jgilliam17** [comment]
Thanks @anurag6713 seeing one issue

1. Link previews no longer disappear when starting a thread, but will disappear after user turns CRT off, then back on.

**Comment by jgilliam17** [comment]
@anurag6713 Did you have a chance to look at my comment [here](https://github.com/mattermost/mattermost-mobile/pull/5758#issuecomment-984140136). Let me know if this was also fixed. Thanks. 🙂

**Comment by anurag6713** [comment]
> @anurag6713 Did you have a chance to look at my comment [here](https://github.com/mattermost/mattermost-mobile/pull/5758#issuecomment-984140136). Let me know if this was also fixed. Thanks. 🙂

I missed your comment and forgot to come back to it after my PTO ... looking into it. Thank you @jgilliam17

**Comment by jgilliam17** [comment]
@anurag6713 Here is the video for the issue I am seeing
Video starts with CRT on and link previews displaying on the post after thread is started 
at 12sec CRT is turned off by user (not sysadmin) -link previews are still available 
at 33sec CRT is turned back on - link previews are no longer available

https://user-images.githubusercontent.com/52937121/150002687-14759f1e-2737-4eb0-aaa1-e3d039fe6f4f.MP4

**Comment by anurag6713** [comment]
@jgilliam17 Thank you. Will fix it ASAP

**Comment by enahum** [comment]
@jgilliam17 is this PR to be included in 1.49? is been sitting here since Oct 2021.

cc: @Willyfrog @amyblais

**Comment by jgilliam17** [comment]
@enahum When ready, this PR can be included in v1.49 - no objections from QA.

**Comment by enahum** [comment]
@amyblais are you ok to include this in 1.49 ?

**Pull request merged**
