### PR TITLE
[MM-29381] Show an indicator if channel is still loading after 10 seconds

### PR DESCRIPTION
**Pull request by migbot**
#### Summary
Added an `Animated.View` in the `ChannelLoader` that is similar to that in the `NetworkIndicator` component, which is displayed 10 seconds after the `ChannelLoader` is mounted. At that time, and every 10 seconds after that, `retryLoadChannels` is called until the `ChannelLoader` component unmounts.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-29381

#### Checklist
- [x] Added or updated unit tests (required for all new features)
- [x] Has UI changes
- [x] Includes text changes and localization file updates

#### Device Information
This PR was tested on:
* iPhone 11 simulator

#### Screenshots
still_loading

### CODE REVIEW

**Review by enahum — CHANGES_REQUESTED** [review]
The UI looks ok but I don't see anything that triggers the fetch from the server, so data won't get loaded and user will remain in this screen forever

**Review by enahum — COMMENTED** [review]
what if teams failed to load? in that case loading channels from an undefined team won't work

**Comment by enahum** [comment]
Also build is failing

**Review by enahum — APPROVED** [review]

**Review by josephbaylon — APPROVED** [review]
LGTM. Verified banner `Still trying to load your content...` shows if app is still loading after 10 secs. Verified banner does not display before 10 seconds.

Tested on iPhone X (14.2) and Pixel 3 XL (11) devices.

**Review by matthewbirtch — APPROVED** [review]
Looks good to me as well. Works as expected.

**Pull request merged**
