### PR TITLE
Bump app build number to  351

### PR DESCRIPTION
**Pull request by enahum**

### CODE REVIEW

**Comment by amyblais** [comment]
@enahum Perhaps we can actually wait for Carlos to cherry-pick this https://github.com/mattermost/mattermost-mobile/pull/5307.

**Comment by enahum** [comment]
@amyblais since when we started to cherry pick translation PR's again?

**Comment by amyblais** [comment]
@enahum I thought they were cherry-picked. We can then proceed with this PR without the translations PR.

**Comment by enahum** [comment]
@amyblais the reason I asked is cause I'm not sure if the translation process changed. There used to be a PR for master and another one for the branch, so not sure.

Can you confirm so we can proceed?

**Comment by amyblais** [comment]
@enahum They are cherry-picked these days, e.g. the previous translations PR was cherry-picked to v1.42 https://github.com/mattermost/mattermost-mobile/pull/5275.

**Pull request merged**
