### PR TITLE
[MM-47384] Make openid, google, office365 oauth free

### PR DESCRIPTION
**Pull request by plant99**
#### Summary

OpenId-Connect options are to be made freely available in an upcoming release. This PR removes license and license field checks from when they are rendered.
Server-PR: https://github.com/mattermost/mattermost-server/pull/21556

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-47384
#### Checklist

- [ ] Added or updated unit tests (required for all new features)
- [ ] Has UI changes
- [ ] Includes text changes and localization file updates
- [ ] Have tested against the 5 core themes to ensure consistency between them.

#### Device Information
This PR was tested on: 

#### Release Note

```release-note
Moved OpenId, Google, Office365 OAuth to free tier.
```

### CODE REVIEW

**Review by enahum — APPROVED** [review]

**Review by BenCookie95 — APPROVED** [review]

**Comment by enahum** [comment]
> Thanks @plant99 
> 
> 
> 
> I am able to see only `Gitlab` login 
> 
> `Google`, `Office365` and `OpenId` is not showing up 
> 

@furqanmlk You need to test against a 7.6 server, anything lower than that should only show those options on licensed servers

**Comment by plant99** [comment]
Agree with Elias, @furqanmlk . 

The corresponding server branch has `7.5.0` as version name. Now luckily, we have `7.6.0` on master now so a simple `/update-branch` which I've done in the server PR will make it work. Please make sure to pull recent server changes.

I was able to verify that with 7.6.0 I could see OpenId options showing up.

**Review by furqanmlk — COMMENTED** [review]
Thanks @plant99 for the updates.
Google, Office365 and Gitlab look good, however, icon is missing for OpenID.

OpenID - Google
image

OpenID - Office365
image

OpenID - OpenID ( Icon is missing )
image

**Comment by enahum** [comment]
@furqanmlk when was the openId icon image added? That looks new to me, can you please confirm and share that info?

**Comment by furqanmlk** [comment]
> @furqanmlk when was the openId icon image added? That looks new to me, can you please confirm and share that info?

@enahum sure let me confirm.

**Comment by furqanmlk** [comment]
> @furqanmlk when was the openId icon image added? That looks new to me, can you please confirm and share that info?

@enahum I confirm in master, there is no icon for `OpenID`

**Review by furqanmlk — APPROVED** [review]

**Comment by enahum** [comment]
> > @furqanmlk when was the openId icon image added? That looks new to me, can you please confirm and share that info?
> 
> 
> 
> @enahum I confirm in master, there is no icon for `OpenID`

But should it be added? It is available since what server version? Should it be part of this PR?

**Comment by furqanmlk** [comment]
> > > @furqanmlk when was the openId icon image added? That looks new to me, can you please confirm and share that info?
> > 
> > 
> > @enahum I confirm in master, there is no icon for `OpenID`
> 
> But should it be added? It is available since what server version? Should it be part of this PR?

according to @plant99 if icon is not in master, we will not add in this branch.

**Comment by enahum** [comment]
When we talk about master, in which repo are we talking about?

Master on this repo no longer exists, and if the ixon is available ln web I see no reason why not to add it for supported servers

**Comment by plant99** [comment]
> When we talk about master, in which repo are we talking about?
> 
> Master on this repo no longer exists, and if the ixon is available ln web I see no reason why not to add it for supported servers

I agree and it should be added @enahum , however I propose we should make a different ticket for the same. This feature change is to go with 7.6 release and there isn't enough time to build/QA for icon before feature complete. I'll create a new PR when these features are merged :)

**Comment by enahum** [comment]
Merging

**Pull request merged**
