### PR TITLE
Fix: Show admin on channel members

### PR DESCRIPTION
**Pull request by panoramix360**
#### Summary
This PR fixes the label that shows Admin/Member when the managing members are on the Members screen of a channel.

The label was showing just `Member` for all users and now is differentiating between Admin and Member users.

#### Ticket Link

[Reported Issue](https://github.com/mattermost/mattermost/issues/23864)

#### Checklist

- [X] Has UI changes
- [X] Have tested against the 5 core themes to ensure consistency between them.

#### Device Information
This PR was tested on: 

- iOS Simulator, iOS 16.4
- Android Emulator, Nexus 5 API 31

#### Screenshots

# iOS - With Sections
image

# iOS - With Search
image

# Android - With Sections
image

# Android - With Search
image

#### Release Note

```release-note
Shows correctly the Member/Admin label on a UserRow inside the Members Screen when managing users
```

### CODE REVIEW

**Review by larkox — APPROVED** [review]

**Comment by yasserfaraazkhan** [comment]
hi @panoramix360 , 
I tried building and running it on iPhone, the dropdown had `member` and not `systemadmin`. Can you check this once?

9C9E7A6C-2642-4E02-8BA0-7C00F766F937

AB86E484-31BC-4B7D-8C1A-CED55F939256

**Comment by larkox** [comment]
@panoramix360 Before diving into this, I would like to hear @matthewbirtch opinion on whether this should show sysadmin or not, and whether sysadmins should be considered channel admins or not. Just want to make sure this is the expected behavior. If I am not mistaken, on web, only channel admins show as admins (sysadmins do not).

**Comment by matthewbirtch** [comment]
> @panoramix360 Before diving into this, I would like to hear @matthewbirtch opinion on whether this should show sysadmin or not, and whether sysadmins should be considered channel admins or not. Just want to make sure this is the expected behavior. If I am not mistaken, on web, only channel admins show as admins (sysadmins do not).

I think it's fine to show the SYSTEM ADMIN badge in the user bottom sheet, but I don't think we want to add them as a channel admin in the list. Technically they do have permission to admin the channel as system admins, but we don't show them as such in the channel members list - otherwise the system admin would show as a channel admin for every channel.

**Comment by larkox** [comment]
@yasserfaraazkhan According to Matt's comments, this would be ok as it is, right? Could you verify?

**Review by yasserfaraazkhan — APPROVED** [review]
thank you for the changes @panoramix360 
596EDD0E-2732-4908-9E9F-F46D6B231056
C1715A16-DC3C-431B-9A7D-0D94D3B0BBE1

**Comment by larkox** [comment]
Thank you for the contribution @panoramix360 !

**Pull request merged**
