### PR TITLE
Add feature flag

### PR DESCRIPTION
**Pull request by larkox**
#### Summary
Use the right feature flag when checking if apps are enabled or not.

DISCLAIMER: Since the server PR is not yet merged, this will render apps unusable on the client until that PR gets merged. After that, only server initialized with the feature flag set to true will show apps related code in the client.

#### Ticket Link
None

#### Related Pull Requests
Server: https://github.com/mattermost/mattermost-server/pull/16851
Webapp: https://github.com/mattermost/mattermost-webapp/pull/7643

### CODE REVIEW

**Comment by enahum** [comment]
@larkox haven't looked at the code, but going with the description, what happens when this lands on-prem? Feature flags are for cloud only right?

**Review by mickmister — APPROVED** [review]

**Comment by larkox** [comment]
@enahum On prem also allows feature flags, but unless you are actively setting them up, the average user will see only the defaults. The default for enabling apps features is false. That means that average on prem user will not be able to use the apps (neither from mobile nor webapp). This is intended.

When the feature is battletested enough in cloud, we will remove the feature flag, and will be available on-prem.

Either way, any on prem user can setup the correct environment variable when running the server and start using the apps on their instance.

**Comment by enahum** [comment]
@larkox sounds good  to me, do we also need to check for a minimum server version as well? either now or after it has been battle tested?

**Comment by larkox** [comment]
That is a great question. CC @catalintomai for visibility.

I feel there is no need for minimum server version. The only requirement is to have the apps proxy plugin installed/enabled. We could implement that.

If the apps proxy plugin is not installed, the only "overhead" is that we will be calling the fetchbinding call every time needed (mainly on channel navigation), but it will return error, and therefore, the system will consider no bindings available. If there are no bindings, no other "apps related" calls will get to the server.

From my perspective, adding this check for the plugin status is a nice to have, but not needed for the first release.

**Comment by enahum** [comment]
Agree is not **really** needed, but on the other habd is not a very good practice to perform a request if you already know is going to fail for some reason, mobile device = limited resources :)

what is the extent of complexity to add that check? I don’t want to deviate you guys from your work, so if you guys consider is OK for now and have a ticket to improve on it, I’ll let it slide :p

**Comment by larkox** [comment]
There are methods on the server side to make sure that when the apps are enabled, the proxy plugin is also installed, enabled and running (we want to make this as if part of the server code).

The complexity depends. Doing it is almost trivial. Doing it right is the thing that may get complicated.
- Doing it: on apps enabled make a call to get the plugin status from the server and check. Result? Way more calls to the server, since now apps enabled (which is used all around the code) will make a server call.
- Doing it right: fetch on startup (and similar) the plugin statuses, and react to plugin related websocket events to keep redux state up to date, so apps enabled can look into the redux state. Result? 1 extra call to the server on startup, unless we find a way to piggyback this into the slash commands requests.

I will leave the decision to @catalintomai , but I would create a ticket, and defer this for later.

**Review by enahum — APPROVED** [review]

**Review by catalintomai — APPROVED** [review]

**Comment by DHaussermann** [comment]
Tested and passed 
Tested with `http-hello` which grabs bindings to ass post options.
- Build works fine on servers that predate the flag
- MM app work normally to get the bindings and add UI elements when the server has the feature on
- MM app will remove the elements from the UI when the feature is tuned off
- No requests for binding are ever made to the server when the feature flag is disabled
- Tested on both iOS and Android clients

LGTM!

**Pull request merged**
