### PR TITLE
RN-113/RN-114 Updated markdown styles for lists and code

### PR DESCRIPTION
**Pull request by hmhealey**
@asaadmahmood For the code style, we can't apply padding or margin to inline text, so those stayed the same, but I updated font on iOS. There's not many selections for font on Android, so it's the same as it was before.

#### Ticket Link
https://mattermost.atlassian.net/browse/RN-113
https://mattermost.atlassian.net/browse/RN-114

#### Checklist
- Has UI changes

#### Device Information
This PR was tested on: iOS Simulator

#### Screenshots
screen shot 2017-08-11 at 4 41 18 pm

### CODE REVIEW

**Comment by hmhealey** [comment]
Also, some testing on Android is needed, but my phone keeps crashing so I don't have time to do it tonight

**Comment by enahum** [comment]
@hmhealey haven't checked this yet but by reading the description I have to ask, have you tried installing the desired font for android? we did it for [Open Sans](https://github.com/mattermost/mattermost-mobile/tree/master/android/app/src/main/assets/fonts)

**Comment by hmhealey** [comment]
Good point. I hadn't thought of that. I'll take a look at adding that today

**Comment by hmhealey** [comment]
Actually @enahum, I'll submit the font change in a separate PR once this and https://github.com/mattermost/mattermost-mobile/pull/855 are merged so that I can change it in both places

**Pull request merged**
