### PR TITLE
 [MM-12599] Implement assets for Adaptive icons

### PR DESCRIPTION
**Pull request by kmandagie**
#### Summary
Android introduces a new app icon format: adaptive icons. Adaptive icons can make devices more coherent by unifying the shape of all app icons and opening the door to interesting visual effects.

#### Ticket Link
[MM-12599](https://mattermost.atlassian.net/browse/MM-12599)

#### Checklist
- [x] Added Beta Icon
- [x] Added Normal Icon Without Beta

#### Device Information
This PR was tested on: Android Studio Simulator,  Android Pie

### CODE REVIEW

**Comment by enahum** [comment]
@migbot lets test this on Android 7 8 and 9, I will test it on a device as well with a couple of different launchers

**Comment by enahum** [comment]
@kmandagie do we need the file `android/app/src/main/ic_launcher-web.png` without the beta as well and have it replaced when building for release?

**Comment by kmandagie** [comment]
@enahum hmm sorry, my bad about that. base on this https://stackoverflow.com/questions/13895390/what-does-the-ic-launcher-web-png-in-my-project-root-do/13895410. the post says it's safe to remove. I will make new commit as soon as I can

**Comment by enahum** [comment]
@kmandagie if you want you can wait for the rest of the feedback that I'm gathering just now

**Comment by enahum** [comment]
Alright @kmandagie this is what I've found on an Android Oreo using the Samsung Home Experience and Evie launchers by testing both beta and non-beta icons.

Mattermost beta

Samsung launcher home screen looks good
samsung-beta-home

Samsung launcher apps screen looks good
samsung-beta

Evie launcher home screen looks good
evie-beta-home

Evie launcher apps screen is showing the icon as squared (which I believe is wrong)
evie-beta

Mattermost with the release app icon
Samsung launcher home screen looks good
samsung-home

Samsung launcher apps screen looks good
samsung

Evie launcher home screen looks good
evie-home

Evie launcher apps screen is showing the wrong icon with the right shape
evie

**Comment by enahum** [comment]
@kmandagie do you think we can have an update for this soon? The only way this can ship in the next 1.18 release is if this PR gets merged by Tuesday 26th, if not we are going to have to push it until the 1.20 release

**Comment by enahum** [comment]
@asaadmahmood  thoughts?

**Comment by asaadmahmood** [comment]
@migbot Updated the icons slightly, attached the files to the Jira ticket again.
https://mattermost.atlassian.net/browse/MM-12599

**Comment by enahum** [comment]
@kmandagie any updates on this? is the feedback provided enough?

**Comment by jasonblais** [comment]
Hey @kmandagie - and thanks for your contribution! This will be a great improvement for Android devices.

Would you be open to sharing if you have any questions about the above? We'd be happy to help clarify.

**Comment by kmandagie** [comment]
Really sorry about the delay. I just done my uni project so maybe tomorrow I will start work for the revision

**Comment by jasonblais** [comment]
Oh, got it! Thanks for the heads up @kmandagie, really appreciate your help here. If you have final exams coming up for uni as well, let us know, totally understand.

**Comment by kmandagie** [comment]
@enahum can I get the logo like before? the logo and the background separate like before? thank you

**Comment by enahum** [comment]
@asaadmahmood can you help @kmandagie?

**Comment by asaadmahmood** [comment]
@enahum @kmandagie  Added `beta-new.zip` on the Jira ticket.
Let me know if we need anything else.

Jira ticket: https://mattermost.atlassian.net/browse/MM-12599

**Comment by kmandagie** [comment]
This result using AdaptiveIconPlayground
Screen Shot 2019-04-18 at 12 49 50
Screen Shot 2019-04-18 at 12 50 09
Screen Shot 2019-04-18 at 12 50 20
Screen Shot 2019-04-18 at 12 50 30

**Comment by enahum** [comment]
@kmandagie can you please rebase this PR

**Comment by enahum** [comment]
@migbot please take a look when you can

**Pull request merged**
