### PR TITLE
[MM-23755] Add nickname as searchable property

### PR DESCRIPTION
**Pull request by shred86**
#### Summary

Adds the ability to find users by nickname when searching using @. Also displays the users nickname, if set, in parenthesis next to the users display name. Matches functionality of the web app.

Added `nickname` property to `profiles` in autocomplete.test.js.

#### Ticket Link

[MM-23755](https://mattermost.atlassian.net/browse/MM-23755)

#### Checklist

- [ ] Added or updated unit tests (required for all new features)
- [ ] All new/modified APIs include changes to [mattermost-redux](https://github.com/mattermost/mattermost-redux) (please link)
- [x] Has UI changes
- [ ] Includes text changes and localization file updates

#### Device Information
This PR was tested on:  
- iPhone 11, iOS 13.4 (simulator)
- Pixel 3, Android 9 (simulator)

#### Screenshots

- [iPhone 11, iOS 13.4 (simulator)](https://i.imgur.com/tS19VjV.png)
- [Pixel 3, Android 9 (simulator)](https://i.imgur.com/sKa4CeR.png)

### CODE REVIEW

**Comment by enahum** [comment]
@esethna please check this out!

**Comment by esethna** [comment]
Thanks @shred86! Can you help attach any screenshots of the UI updates?

**Comment by enahum** [comment]
@esethna there are screenshot links in the description

**Comment by esethna** [comment]
Thanks @shred86! Screenshots look good. @josephbaylon can we make sure when testing that if the full name, username and nickname cannot fit in the autocomplete horizontally, truncate it with ...

**Comment by esethna** [comment]
Opened a ticket here: https://mattermost.atlassian.net/browse/MM-23755

**Comment by enahum** [comment]
@esethna I think this needs a UX pass first unless the ellipsis is the desired UI/UX

**Comment by esethna** [comment]
@enahum @shred86 truncation with ellipses is fine (as we do on webapp). ^

Thanks for finding @josephbaylon

**Comment by shred86** [comment]
I'm new to JavaScript and React Native so I apologize in advance if this isn't the best solution. After doing a little research, `numberOfLines={1}` seems to be the recommended solution with the style property of `flex: 1` set. I just created a new `<Text>` tag around the first/last name and nickname `<Text>` tag to cover both cases (long full name or long nickname) and to reduce some repeated code.

iPhone8_iOS13_fullname
iPhone8_iOS13_nickname

Pixel3_Android8_fullname
Pixel3_Android8_nickname

**Comment by enahum** [comment]
@shred86 is quite alright to be new to the tech, I'll be suggesting some changes in the morning for you to learn an implement.

**Comment by enahum** [comment]
to be included in the 1.32 release

**Pull request merged**
