### PR TITLE
Allow unselecting users by tapping again on the row or the chips

### PR DESCRIPTION
**Pull request by niklabh**
#### Summary
Allow unselecting users by tapping again on the row or the chips

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/12246

#### Checklist
- [x] Added or updated unit tests (required for all new features)

#### Device Information
This PR was tested on: [iphone 10X, ios 12.3.1]

### CODE REVIEW

**Comment by niklabh** [comment]
Chips are already there.

**Comment by saturninoabril** [comment]
@niklabh Yes for `MoreDirectMessages` screen but I believe those missing currently are in "Manage Members" and "Add Members" screens.  Please take a look, thanks

**Comment by enahum** [comment]
@niklabh any questions about the above feedback?

**Comment by jasonblais** [comment]
Hey @niklabh, big thanks for your contribution. Let us know if you have any questions about the feedback above, we'd be glad to help :)

**Comment by enahum** [comment]
@niklabh will you be able to address the feedback given?

**Comment by niklabh** [comment]
Very sorry for the late reply. Will check the issue and get back to you

**Comment by niklabh** [comment]
Have pushed the required changes. But on running updatesnapshot tool getting error:

 FAIL  app/actions/views/root.test.js
  ● Test suite failed to run

    Cannot find module '../../dist/assets/config' from 'segment.js'

    However, Jest was able to find:
    	'../../utils/segment.js'

    You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['js', 'json', 'jsx', 'ts', 'tsx', 'node'].

    See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string

    However, Jest was able to find:
    	'./root.js'
    	'./root.test.js'

    You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['js', 'json', 'jsx', 'ts', 'tsx', 'node'].

    See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string

       6 | import {Dimensions} from 'react-native';
       7 | 
    >  8 | import Config from 'assets/config';
         | ^
       9 | 
      10 | import tracker from './time_tracker';
      11 | 

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:259:17)
      at Object.<anonymous> (app/utils/segment.js:8:1)

**Comment by hanzei** [comment]
Hey @niklabh,

The CI reports:
```         
 FAIL  app/screens/channel_members/channel_members.test.js
  ● ChannelMembers › should match snapshot

    expect(received).toMatchSnapshot()

    Snapshot name: `ChannelMembers should match snapshot 1`

    - Snapshot
    + Received

    @@ -38,10 +38,16 @@
            tintColorDelete="rgba(61,60,64,0.5)"
            tintColorSearch="rgba(61,60,64,0.5)"
            titleCancelColor="#3d3c40"
            value=""
          />
    +     <Connect(SelectedUsers)
    +       maxCount={7}
    +       onRemove={[Function]}
    +       selectedIds={Object {}}
    +       warnCount={5}
    +     />
        </View>
        <CustomList
          data={Array []}
          extraData={Object {}}
          isLandscape={false}

      30 |         );
      31 | 
    > 32 |         expect(wrapper.getElement()).toMatchSnapshot();
         |                                      ^
      33 |     });
      34 | 
      35 |     test('should use renderUnselectableItem when canManagerUsers is false', () => {

      at Object.toMatchSnapshot (app/screens/channel_members/channel_members.test.js:32:38)
```

Please let uns know if you need help resolving this

**Comment by enahum** [comment]
@niklabh do you have any questions about the feedback? will you continue working on this PR?

**Comment by enahum** [comment]
@niklabh would you be open to resolve the conflicts and fix the tests on this one?

**Comment by teresa-novoa** [comment]
@sudheerDev friendly reminder to review this PR, thanks!

**Comment by hanzei** [comment]
This PR has become orphaned and will be closed. Still, thanks for your contribution @niklabh. Let me know if you want to work on this PR agian.

**Pull request closed without merging**
