### PR TITLE
Fastlane update to include new build process

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
Updated fastlane build script so it adapts to the new process (branching and release).

This PR simplifies a lot of the env vars used to build the app and also combines the ios and android lanes to build both apps in sequence with the command **make build**

I will be updating the docs as soon as possible, but first will tackle other priority tickets

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-12394

### CODE REVIEW

**Comment by enahum** [comment]
@cpanato is out so I'm going to merge this, the fact that I added him as a reviewer is so he can have an idea of what to do in the pipeline

**Comment by enahum** [comment]
cherry-picked 1.13

**Comment by stephanfriedrich** [comment]
@enahum 
hi i can't build my mattermost-mobile app anymore. 
it seems that since your commit, the config-file ".env" is no longer read.

i tested it before (10a1e93e7d766d2a4ba36dab4c68b4bc84b5341b) and with your commit, and before it worked without problems.

what do you think?

**Comment by enahum** [comment]
Hi @stephanfriedrich we did change how the app is being built now (changes on the env vars) and you should take a look at the updated documentation https://developers.mattermost.com/contribute/mobile/build-your-own/ but the `.env` file under the fastlane folder should work just fine.

you can always set the env vars by sourcing them in your bash

**Comment by stephanfriedrich** [comment]
hi, thanks for your answer.
that's weird, imho i already considered the new documentation.

here is an example of my configuration
**.env :**
```
############ COMMON ############
export LC_ALL="en_US.UTF-8"

############ ANDROID ############

# Should we submit the app to be rollout in Google Play, use along with SUPPLY_TRACK
export SUBMIT_ANDROID_TO_GOOGLE_PLAY=false

# Defines if the Android app should be built in release mode
export ANDROID_BUILD_FOR_RELEASE=true

# Should we use the assets found in assets/release/icons/android
export ANDROID_REPLACE_ASSETS=false
[....]
```

**Comment by stephanfriedrich** [comment]
@enahum Ok thx for your feedback, everything works now.

it might not be a bad idea to update the template ```fastlane/env_vars_example``` to match the documentation and the new adjustments

**Pull request merged**
