### PR TITLE
Corrects SemiBold to Semibold

### PR DESCRIPTION
**Pull request by shazm**
#### Summary
Android specific case-sensitivity issue; this corrects all instances of `{fontName}-SemiBold` to `{fontName}-Semibold` to match the file name.

#### Ticket Link

No ticket, see https://github.com/mattermost/mattermost-mobile/pull/5868#discussion_r766043984

#### Checklist

- [ ] Added or updated unit tests (required for all new features)
- [X] Has UI changes
- [ ] Includes text changes and localization file updates
- [ ] Have tested against the 5 core themes to ensure consistency between them.

#### Device Information
This PR was tested on: 

- [SIM] Pixel 5 / API30

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by larkox — APPROVED** [review]

**Comment by enahum** [comment]
@shazm how is this change affecting Metropolis? IIRC Metropolis wants it as `SemiBold`

**Comment by shazm** [comment]
> @shazm how is this change affecting Metropolis? IIRC Metropolis wants it as `SemiBold`

There seems to be both a `Metropolis-Semibold` and `Metropolis-SemiBold` font file under assets (so this PR should be fine); I think we can probably remove the `SemiBold` one: https://github.com/mattermost/mattermost-mobile/tree/gekidou/assets/fonts ?

**Comment by enahum** [comment]
> > @shazm how is this change affecting Metropolis? IIRC Metropolis wants it as `SemiBold`
> 
> 
> 
> There seems to be both a `Metropolis-Semibold` and `Metropolis-SemiBold` font file under assets (so this PR should be fine); I think we can probably remove the `SemiBold` one: https://github.com/mattermost/mattermost-mobile/tree/gekidou/assets/fonts ?

Actually there is only one SemiBold, the one in the assets folder should be removed.

https://github.com/mattermost/mattermost-mobile/tree/gekidou/android/app/src/main/assets/fonts

**Comment by enahum** [comment]
I think is best if you share screenshots for ios and android with both fonts

**Review by enahum — CHANGES_REQUESTED** [review]
Needs validation of fonts on Android and iOS for metropolis and opensans

**Comment by shazm** [comment]
Screen Shot 2022-01-20 at 4 53 25 pm
Screen Shot 2022-01-20 at 4 42 00 pm

I think it's now resolved - fonts are now `CamelCased`, screenshots above - seems to be working fine on both Android and iOS.

**Review by enahum — APPROVED** [review]

**Pull request merged**
