### PR TITLE
Use more verbose message on archive and don't make help link lowercase

### LINKED ISSUE #4482: Android app converts help URL to all lowercase
#### Summary
In the Android app, Mattermost converts help URLs to all lowercase.

#### Environment Information

- Device Name: Huawei Honor 10
- OS Version: Android
- Mattermost App Version: 1.32.0
- Mattermost Server Version: 5.23.0

#### Steps to reproduce
Set the help URL in a Mattermost instance to include upper and lower case characters. Visit the URL from android.

#### Expected behavior
The URL should not be converted to all lower case.

#### Observed behavior
User is sent to a lowercase version of the URL.

### LINKED ISSUE #4806: Warning message to archive a channel is too weaker compared to the web version
#### Summary

Warning message to archive a channel is too weaker compared to the web version. It doesn't mention to the fact that the channel will be inaccessible for everyone.

#### Environment Information

- OS Version: Android 10
- Mattermost App Version: 1.34.1
- Mattermost Server Version: 5.23.0

#### Steps to reproduce
Open a channel and select the archive option with an admin right of the channel.

#### Expected behavior

Give enough warning like Web version:
```
Confirm ARCHIVE Channel
This will archive the channel from the team and make its contents inaccessible for all users.

Are you sure you wish to archive the XYZ channel?
```

#### Observed behavior

Mobile version doesn't mention to the risk that everyone will lose the access.
```
Archive Public Channel

Are you sure you want to archive the public channel XYZ?
```

#### Possible fixes

https://github.com/mattermost/mattermost-mobile/blob/55cfce9b8958637d3180da88283361412e4b5b64/app/screens/channel_info/archive/archive.tsx#L69-L72

### PR DESCRIPTION
**Pull request by larkox**
#### Summary
Minor fixes regarding the help link not being lowercase and the archive channel warning not being verbose enough.

#### Ticket Link
Fix #4806
Fix #4482

#### Release Note
```release-note
Help link now is not converted to lowercase
Archive channel shows a more detailed warning
```

### CODE REVIEW

**Review by enahum — APPROVED** [review]

**Comment by enahum** [comment]
Are we cherry picking?

**Comment by jgilliam17** [comment]
@larkox Can you point me to where I can configure the help link url? Thanks

**Comment by larkox** [comment]
@jgilliam17 It should be in System Console -> Site Configuration -> Customization -> Help Link

**Comment by jgilliam17** [comment]
Thanks @larkox 
Tested, looks good to merge.

**Review by jgilliam17 — APPROVED** [review]

**Pull request merged**
