### PR TITLE
[MM-29132] Update upload item styling

### PR DESCRIPTION
**Pull request by migbot**
#### Summary
Reduced font size of progress text and fixed close icon position.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-29132

#### Checklist
- [x] Has UI changes

#### Device Information
This PR was tested on:
* iPhone SE, iOS 14
* Mi A3, Android 10

#### Screenshots
iOS:
ios

Android:
android

### CODE REVIEW

**Review by hahmadia — APPROVED** [review]
Code looks good.  I'm no UX person but the font for IOS looks like it isn't centered properly. Feels a little too close to the left side. Android looks good though.

**Review by ashishbhate — APPROVED** [review]
LGTM, same observation as Hossein - the centring looks off to me too.

**Comment by enahum** [comment]
🤔 #4837 ?

**Review by matthewbirtch — APPROVED** [review]
Looks good. Font-size 9 should be fine. If you could just confirm that it's centered properly, that would be good.

Eventually, I'd like to move toward this style below (I think this is what Elias is getting at), but at least for now, the percentage won't wrap. Thanks!
image

**Review by josephbaylon — APPROVED** [review]
LGTM. Upload item styling has been updated.
Tested on both iPhone X (14) and Pixel 3 XL (11) devices.

Ticket for tests: https://mattermost.atlassian.net/browse/MM-29024

**Pull request merged**
