### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Weblate](https://translate.mattermost.com/projects/mattermost/mattermost-mobile_master/) for mattermost-languages-shipped/mattermost-mobile.

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by enahum** [comment]
@metanerd now this PR needs the work done in the previous one by the contributor

**Comment by metanerd** [comment]
@enahum Yep, already clarified that we have to again create another PR. Not really a smooth approach, but doesn't happen too often.

**Review by enahum — APPROVED** [review]

**Comment by amyblais** [comment]
@metanerd This can be cherry-picked to v1.39 as we're expecting another build.

**Comment by enahum** [comment]
@amyblais two things.
1. This PR is adding to new languages, are thise languages available in 5.31? If not, it should not be cherry-picked, also there is another PR in that case that enable these languages
2. Translations are submitted against the release branch if needed.

**Pull request merged**
