### PR TITLE
[MM-26318] Improve cold start and channel switching times

### PR DESCRIPTION
**Pull request by migbot**
#### Summary
* No longer encrypting MMKV storage
* Commented out react-native-keychain warm up per https://github.com/oblador/react-native-keychain/issues/314#issuecomment-630466066

#### Device Information
This PR was tested on:
* Pixel 2, OnePlus 5T

Fixes: #4449

### CODE REVIEW

**Comment by amyblais** [comment]
Jira ticket: https://mattermost.atlassian.net/browse/MM-26318.

**Comment by enahum** [comment]
@josephbaylon can you compare with v1.31.2??

Times seem acceptable, I would expect ~3-7 or ~3-8 for cold start.

**Comment by prapti** [comment]
Adding what I'd seen earlier with build https://github.com/mattermost/mattermost-mobile/commit/c07da609
- Reinstall: splash screen to app load 3 seconds
- Channel switch:  ~1 second
- Closing and reopening: 2 seconds
- Clean install: everything except app load was similar; app fully loaded in 2 seconds.

**Comment by josephbaylon** [comment]
> @josephbaylon can you compare with v1.31.2??
> 
> Times seem acceptable, I would expect ~3-7 or ~3-8 for cold start.

@enahum for v1.31.2
1. cold start - 3 to 4 seconds
2. close/open - 2 to 3 seconds
3. switching channels - immediate to 1 second
4. clearing data then close/open - 2 to 3 seconds

The big difference at least on my device is on scenario 4 where user clears data before closing and re-opening. For PR build it's about 5-6 seconds but for v1.31.2 it's about 2-3 seconds only.

**Comment by enahum** [comment]
not perfect but way better than the current release.. I don't think we'll spend much time digging further

**Comment by esethna** [comment]
@migbot @enahum is this also addressing the issues of "freezing" phones due to notifications?

**Comment by enahum** [comment]
@esethna do you know what that means????? freezing with in-app notifications? what is it about ?

**Comment by sreekanthgs** [comment]
Some feedback on Device: OnePlus 5T, Android Version: 10.0

1. cold start - 10 to 18 seconds (not much improvement from current play store beta/stable)
2. close/open - 1 to 2 seconds
3. switching channels - immediate to 1 second
4. clearing data then close/open - 2 to 3 seconds

Cold start was done after clearing all running apps from the device.

**Comment by enahum** [comment]
@migbot lets try and find out why @sreekanthgs still has issues with this build...

@sreekanthgs question, do you refer to cold start from the moment you open the app until the splash screen gets removed or until all messages show on screen?

**Comment by sreekanthgs** [comment]
Cold start is from app start (when not in memory, and all memory apps cleared) to the first appearance of any screen other than startup splash screen.

This does not include loading of messages.

**Comment by sreekanthgs** [comment]
> @sreekanthgs Could you share logcat output during app launch?

```shell
06-19 21:02:24.166  1521  4677 D OemSceneCallBlock: isCallBlockedWithUidIntent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.mattermost.rnbeta/.MainActivity bnds=[32,1085][235,1396] }, ResolveInfo{90af648 com.mattermost.rnbeta/.MainActivity m=0x0}, false
06-19 21:02:24.167  1521  4677 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.mattermost.rnbeta/.MainActivity bnds=[32,1085][235,1396]} from uid 10028 pid 15980
06-19 21:02:24.179 15980 15980 D BaseDraggingActivity: startActivity bookkeeping intent = Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.mattermost.rnbeta/.MainActivity bnds=[32,1085][235,1396] }
06-19 21:02:24.179 15980 15980 D Stats   : Intent.getPackage() is null. therefore try to get package name from componentName.getPackageName(): com.mattermost.rnbeta
06-19 21:02:24.180 15980 15980 D Stats   : Intent.getPackage() is null. therefore try to get package name from componentName.getPackageName(): com.mattermost.rnbeta
06-19 21:02:24.186 15980 15980 D ItemClickHandler: onClick app, allappsTransProgress = 0.0, tag = AppInfo(id=-1 type=APP container=-1 screen=-1 cell(-1,-1) span(1,1) minSpan(1,1) rank=0 user=UserHandle{0} title=Mattermost Beta hidden=false dirty = false newInstallTag=null componentName=ComponentInfo{com.mattermost.rnbeta/com.mattermost.rnbeta.MainActivity} searchResult=null suggestionApp=null)
06-19 21:02:24.207  1521  1567 D OpRestartProcessManager: updateSelf :  com.mattermost.rnbeta, size : 25
06-19 21:02:24.211  1521  1578 I ActivityManager: Start proc 16724:com.mattermost.rnbeta/u0a420 for activity {com.mattermost.rnbeta/com.mattermost.rnbeta.MainActivity}
06-19 21:02:24.279  1521  5714 D OpQuickReply: setQuickReplyResumed focusedApp AppWindowToken{9c928c7 token=Token{b126a06 ActivityRecord{464fce1 u0 com.mattermost.rnbeta/.MainActivity t49760}}} pkgName com.mattermost.rnbeta
06-19 21:02:24.286  1521  1567 D Foreground_io: TOP_APP is ProcessRecord{29a0790 16724:com.mattermost.rnbeta/u0a420} uid is 10420
06-19 21:02:24.302 15980 31764 D RecentTasksList: dumpTasks# id=49760, cmp=ComponentInfo{com.mattermost.rnbeta/com.mattermost.rnbeta.MainActivity}, uid=0, locked=false, isAppLocked=false
06-19 21:02:24.328 16724 16724 D SoLoader: adding application source: com.facebook.soloader.DirectorySoSource[root = /data/app/com.mattermost.rnbeta-Om90UKz6bOBhEY9sMgzx0g==/lib/arm64 flags = 0]
06-19 21:02:24.329 16724 16724 D SoLoader: adding backup source from : com.facebook.soloader.ApkSoSource[root = /data/data/com.mattermost.rnbeta/lib-main flags = 1]
06-19 21:02:24.333 16724 16724 D SoLoader: Preparing SO source: com.facebook.soloader.DirectorySoSource[root = /data/app/com.mattermost.rnbeta-Om90UKz6bOBhEY9sMgzx0g==/lib/arm64 flags = 0]
06-19 21:02:24.333 16724 16724 D SoLoader: Preparing SO source: com.facebook.soloader.ApkSoSource[root = /data/data/com.mattermost.rnbeta/lib-main flags = 1]
06-19 21:02:24.333 16724 16724 V fb-UnpackingSoSource: locked dso store /data/user/0/com.mattermost.rnbeta/lib-main
06-19 21:02:24.334 16724 16724 I fb-UnpackingSoSource: dso store is up-to-date: /data/user/0/com.mattermost.rnbeta/lib-main
06-19 21:02:24.334 16724 16724 V fb-UnpackingSoSource: releasing dso store lock for /data/user/0/com.mattermost.rnbeta/lib-main
06-19 21:02:24.339 16724 16724 I ReactNative: Cleaning temp cache /data/user/0/com.mattermost.rnbeta/cache/mmShare
06-19 21:02:24.420 16724 16813 D SoLoader: libv8executor.so not found on /data/data/com.mattermost.rnbeta/lib-main
06-19 21:02:24.420 16724 16813 D SoLoader: libv8executor.so found on /data/app/com.mattermost.rnbeta-Om90UKz6bOBhEY9sMgzx0g==/lib/arm64
06-19 21:02:24.459 16724 16813 D SoLoader: libfbjni.so not found on /data/data/com.mattermost.rnbeta/lib-main
06-19 21:02:24.460 16724 16813 D SoLoader: libfbjni.so found on /data/app/com.mattermost.rnbeta-Om90UKz6bOBhEY9sMgzx0g==/lib/arm64
06-19 21:02:24.587 16724 16813 D SoLoader: libreactnativejni.so not found on /data/data/com.mattermost.rnbeta/lib-main
06-19 21:02:24.587 16724 16813 D SoLoader: libreactnativejni.so found on /data/app/com.mattermost.rnbeta-Om90UKz6bOBhEY9sMgzx0g==/lib/arm64
06-19 21:02:24.587  1521  1576 I ActivityTaskManager: Displayed com.mattermost.rnbeta/.MainActivity: +360ms
06-19 21:02:24.596 16724 16813 I MMKV    : <MMKV.cpp:156::initializeMMKV> root dir: /data/user/0/com.mattermost.rnbeta/files/mmkv
06-19 21:02:24.743 16724 16901 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.mattermost.rnbeta.RNPasteableTextInputManager
06-19 21:02:25.984  1521  1578 I ActivityManager: Start proc 17235:com.google.android.webview:sandboxed_process1:org.chromium.content.app.SandboxedProcessService1:0/u0i452 for  {com.mattermost.rnbeta/org.chromium.content.app.SandboxedProcessService1:0}
06-19 21:02:26.017  1521  1578 I ActivityManager: Start proc 17268:com.google.android.webview:sandboxed_process1:org.chromium.content.app.SandboxedProcessService1:0/u0i453 for  {com.mattermost.rnbeta/org.chromium.content.app.SandboxedProcessService1:0}
06-19 21:02:32.533 16724 16724 D SoLoader: libyoga.so not found on /data/data/com.mattermost.rnbeta/lib-main
06-19 21:02:32.533 16724 16724 D SoLoader: libyoga.so found on /data/app/com.mattermost.rnbeta-Om90UKz6bOBhEY9sMgzx0g==/lib/arm64
06-19 21:02:32.554  1521  5718 D ActivityTaskManager: setRequestedOrientation() to -1 for ActivityRecord{464fce1 u0 com.mattermost.rnbeta/.MainActivity t49760} from pid=16724, uid=10420
06-19 21:02:32.555  1521  4747 D ActivityTaskManager: setRequestedOrientation() to -1 for ActivityRecord{464fce1 u0 com.mattermost.rnbeta/.MainActivity t49760} from pid=16724, uid=10420
06-19 21:02:32.556  1521  4743 D ActivityTaskManager: setRequestedOrientation() to -1 for ActivityRecord{464fce1 u0 com.mattermost.rnbeta/.MainActivity t49760} from pid=16724, uid=10420
06-19 21:02:32.558  1521  4743 D ActivityTaskManager: setRequestedOrientation() to -1 for ActivityRecord{464fce1 u0 com.mattermost.rnbeta/.MainActivity t49760} from pid=16724, uid=10420
06-19 21:02:32.559  1521  5718 D ActivityTaskManager: setRequestedOrientation() to -1 for ActivityRecord{464fce1 u0 com.mattermost.rnbeta/.MainActivity t49760} from pid=16724, uid=10420
06-19 21:02:32.557 16724 16724 I chatty  : uid=10420(com.mattermost.rnbeta) identical 2 lines
06-19 21:02:33.067 16724 17595 D SoLoader: libimagepipeline.so not found on /data/data/com.mattermost.rnbeta/lib-main
06-19 21:02:33.067 16724 17595 D SoLoader: libimagepipeline.so found on /data/app/com.mattermost.rnbeta-Om90UKz6bOBhEY9sMgzx0g==/lib/arm64
06-19 21:02:34.870  1521  1567 W ProcessStats: Tracking association SourceState{6428509 com.mattermost.rnbeta/10420 Top #327861} whose proc state 1 is better than process ProcessState{d7012e0 com.google.android.gms.persistent/10033 pkg=com.google.android.gms} proc state 2 (17 skipped)
06-19 21:02:35.145 16724 16900 D SoLoader: libreactnativeblob.so not found on /data/data/com.mattermost.rnbeta/lib-main
06-19 21:02:35.145 16724 16900 D SoLoader: libreactnativeblob.so found on /data/app/com.mattermost.rnbeta-Om90UKz6bOBhEY9sMgzx0g==/lib/arm64
06-19 21:02:36.305 16724 16766 I chatty  : uid=10420(com.mattermost.rnbeta) FinalizerDaemon identical 1 line
```
Hope this'd do. Thank you.

**Comment by sreekanthgs** [comment]
With the above build, I'm getting a consistent cold start time of 3 seconds. Have tried around twenty repeated attempts, each time with no app in memory.

This is some great work! Cheers. 👍

**Comment by amyblais** [comment]
@migbot Is this good to merge or is there any other investigation ongoing?

**Pull request merged**
