### PR TITLE
Add setup for ENV config and submodule instructions

### PR DESCRIPTION
**Pull request by mfpiccolo**

### CODE REVIEW

**Comment by mfpiccolo** [comment]
Good call @hmhealey.  I will work on setting up defaults and a template.

**Comment by mfpiccolo** [comment]
I added more detail here and included a template for the config.json.  I think the part about git submodules will likely only be relevant to the core team so it probably would be better to put this in the wiki instead of in the Readme. 

I tried for a bit to do some dynamic requiring here for the defaults but it is difficult to do while still git ignoring secrets.  The only thing you have to do to get spun up is `cp -r secrets_example/ secrets/`.  Is that simple enough @hmhealey or do you think it would be worthwhile to figure out how to make this work without it.  We could use an npm command to check for this dir or something like that.

**Comment by hmhealey** [comment]
Yeah, that should work, but I'll add it to `make run` so that it's completely automatic. That'll also fix the build since the tests are failing without the config file. I also tried to make it work like `configureStore.js`, but the React Native compiler seems to require that all files exist even when the `require` statement doesn't get run.

Also, I'm going to submit a PR onto your branch that'll just move the config file into `config/config.json` and rename the one field in it to match the style of our other repos. I'm a bit picky with naming conventions since we're so early in this project, but I don't want to be too much of a hassle with them.

**Comment by thomchop** [comment]
@hmhealey We decided that gitignoring the submodule directory (`secrets`) defeats the purpose of using git submodules. Instead we can just clone the secrets repo into the gitignored directory and work with it as a detached nested repo.
Instead of `git submodule foreach git pull origin master`, we can just run `cd secrets && git pull origin master`. Git doesn't seem to be complaining about this arrangement.

**Comment by hmhealey** [comment]
Going to close this since we discussed doing this a different way

**Pull request closed without merging**
