### PR TITLE
Added iOS top landscape padding to match that of thread header

### PR DESCRIPTION
**Pull request by imisshtml**
#### Summary
Added padding for ios top landscape to match that of the thread header.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-19599

#### Checklist
- [x] Has UI changes

#### Device Information
This PR was tested on: iPhone X 12.2

### CODE REVIEW

**Comment by imisshtml** [comment]
> @imisshtml Could you please check again? Looks good to me on portrait but not on landscape (iPhone 11, iOS13.3).
> 
> Screen Shot 2020-01-25 at 3 41 35 AM
> 
> While here, you might wanna look at an issue I've observed in this branch which probably not related but worth looking. I'm getting error after logging in to community server.
> 
> ```
> TypeError: Cannot read property 'locale' of undefined
>     at http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:129744:30
>     …
>     at Object.getMyFirstChannelForTeams (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:118809:27)
>     at exports.getRedirectChannelNameForTeam (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:129782:41)
> ```

@saturninoabril was this on an emulator? I want to recreate on what you saw.

**Comment by saturninoabril** [comment]
Yes, it is. Let me know what you see.  Thanks

**Comment by jasonblais** [comment]
cc @migbot @saturninoabril on next steps,

**Comment by amyblais** [comment]
Pushing this from v1.29 as this didn't make it to code complete. This is not a regression.

**Comment by saturninoabril** [comment]
Hello @migbot, let me know if there's action item with the comment I posted - https://github.com/mattermost/mattermost-mobile/pull/3856#pullrequestreview-348184339, thanks

**Comment by saturninoabril** [comment]
Yup, tested and found to be fixed on master with the said PR. Recommending to close this PR.  Corresponding Jira ticket is moved to resolve state to further test on v1.30 build.
Thanks @migbot, feel free to close.

**Pull request closed without merging**
