### PR TITLE
updated threads illustration SVG to align with new branding

### PR DESCRIPTION
**Pull request by matthewbirtch**
#### Summary
Updates the threads empty state illustration to the new branding style. The SVG respects the themes as per design.

#### Ticket Link
[Jira Ticket](https://mattermost.atlassian.net/browse/MM-37803)

#### Checklist
- [ ] Added or updated unit tests (required for all new features)
- [x] Has UI changes
- [ ] Includes text changes and localization file updates

#### Device Information
This PR was tested on iOS Simulator

#### Screenshots
**Light theme**

**Dark theme**

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by esethna — APPROVED** [review]
Thanks Matt!

**Review by enahum — APPROVED** [review]

**Review by jgilliam17 — APPROVED** [review]
Thanks @matthewbirtch 
Tested, looks good to merge.
- Verified new threads illustrations for mobile.

**Comment by matthewbirtch** [comment]
@anurag6713 gentle nudge to review this PR

**Comment by matthewbirtch** [comment]
@enahum I think this can be merged

**Comment by anurag6713** [comment]
@matthewbirtch Sorry! I missed this one as I was OOO. This looks great by the way 😄

**Pull request merged**
