### PR TITLE
Allow interaction when the in-app notification is shown

### PR DESCRIPTION
**Pull request by enahum**
#### Ticket Link
https://mattermost.atlassian.net/browse/MM-25145

### CODE REVIEW

**Comment by esethna** [comment]
@enahum doesn't work for me (taps still unresponsive after the in-app notification appears). @josephbaylon can you help do a test pass on this PR? (assuming you are able to repro the original issue)

**Comment by enahum** [comment]
@esethna this was just a quick trial, that is why it does not have a dev review, etc.. I did not even test it heheheh, we'll keep the ticket open and work for it to include it in 1.33

**Comment by josephbaylon** [comment]
@migbot @enahum I retested with latest build and the issue on iOS looks fixed. But I still see `Work In Progress` label. Let me know if I can go ahead and approve this PR.

**Comment by josephbaylon** [comment]
@enahum @migbot Sorry I spoke too soon. I retested on Android and the issue is still there. I'm still not able to tap and interact when in-app notification is shown.

**Comment by enahum** [comment]
@josephbaylon try it now

**Comment by enahum** [comment]
@josephbaylon yes, is working for me locally.. I'm able to dismiss the notification, tap it and interact with the rest of the screen

**Comment by enahum** [comment]
@josephbaylon the one thing it wont work is opening a thread.

**Comment by josephbaylon** [comment]
@enahum I'm testing it without dismissing the in-app notification. I thought the original issue was it should allow user to interact even when in-app notification is NOT dismissed. Did I not understand it correctly?

**Comment by enahum** [comment]
@josephbaylon yes.. you should be able to interact.. say.. switch a channel / team.. long press on a post.

Taping on a post to go to the thread will fail until dismissal.. that is because there is a conflict because of the way the navigation library works. (as far as I know that should be the only issue)

**Pull request merged**
