### PR TITLE
Added Intl polyfill for platforms that don't support it

### PR DESCRIPTION
**Pull request by hmhealey**
@dmeza Do you mind pulling this branch and confirming that it works for you? I've only got an iOS environment set up and it has `Intl` predefined in it.

### CODE REVIEW

**Comment by dmeza** [comment]
@hmhealey sure testing

**Comment by dmeza** [comment]
@hmhealey tested and it's working using "DefaultLocale": "es". On both Ubuntu 14 with Genymotion and Mac OS X El Capitan V 10.11.

**Comment by thomchop** [comment]
@dmeza, @hmhealey, @mfpiccolo Have we tested this on a device? We should do that before merging it. I didn't run into the missing polyfill issue until I ran it on device (android).

**Comment by thomchop** [comment]
I'll go ahead and test this on a device.

**Pull request merged**
