### PR TITLE
[MM-31177] Use png over Compass icon for logo

### PR DESCRIPTION
**Pull request by migbot**
#### Summary
Use `Image` over `CompassIcon` for the in-app logo so that it can be replaced when white-labeling the app.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-31177

#### Checklist
- [x] Added or updated unit tests (required for all new features)
- [x] Has UI changes

#### Device Information
This PR was tested on:
* iPhone SE, iOS 14
* Android 10 emulator

#### Screenshots
iOS:
Simulator Screen Shot - iPhone 11 - 2020-12-08 at 11 03 49

Android:
Screenshot_1607450836

### CODE REVIEW

**Review by enahum — APPROVED** [review]

**Comment by enahum** [comment]
@Migbot why did you update that image in the first place? Please revert that change.

Also it needs to update the layouts as well not only the images... regardless do revert the changes for the splash screen

**Review by enahum — CHANGES_REQUESTED** [review]
Revert splash screen changes

**Comment by matthewbirtch** [comment]
> Revert splash screen changes

The splash screen was updated to match the color update on the new logo image used on the server screen

**Comment by enahum** [comment]
> The splash screen was updated to match the color update on the new logo image used on the server screen. The only difference with the new splash screen images is the color of the logo. And the one for iOS is slightly larger for crisper resolution, but it's scaled down to the exact same size as the current app.

@matthewbirtch then change the logo in the screens, as far I my understanding goes, the splash screen is using the logo based on the [Branding guidelines](https://handbook.mattermost.com/operations/operations/company-processes/publishing/publishing-guidelines/brand-and-visual-design-guidelines)

**Comment by matthewbirtch** [comment]
> as far as my understanding goes, the splash screen is using the logo based on the [Branding guidelines](https://handbook.mattermost.com/operations/operations/company-processes/publishing/publishing-guidelines/brand-and-visual-design-guidelines)

It doesn't anymore. It seems to follow old out-of-date guidelines. The current logo on the splash screen uses a blue that is not used for the brand anymore.

Having said that, the blue I used for the logo in the new images for the splash screen and server screen that Miguel added is based on blue from the default theme - which is again a slightly different blue. But, it seems more important to match the default theme rather than the brand guidelines....otherwise you get different blue logos within the app on the first 2 screens

**Comment by enahum** [comment]
If they are outdated that is a worry as they are on our website... regardless is failing on this PR and I'd day we should revert it at this point until we figure out what needs to be there + the brand guidelines and everywhere else...

**Review by enahum — APPROVED** [review]

**Comment by matthewbirtch** [comment]
> If they are outdated that is a worry as they are on our website... regardless is failing on this PR and I'd day we should revert it at this point until we figure out what needs to be there + the brand guidelines and everywhere else...

The brand guidelines are not outdated....the logo color used in the mobile app is outdated and doesn't match the current brand guidelines you linked to

**Comment by matthewbirtch** [comment]
> @enahum @matthewbirtch Since the main purpose of this PR is to allow changing the logo in the server/login screens when white-labeling, can we push any color and splash screen changes to another ticket? If so, @matthewbirtch can you provide a `logo.png` with the old color but the new crispness?

Yes, that's totally fine @migbot. However, I actually don't have the old logo anywhere. Wouldn't that be in our historical files prior to the icon overhaul?

**Review by josephbaylon — APPROVED** [review]
LGTM. Default logo shows when no changes are made. New logo shows up as well when local changes are made.

Tested default logo on iPhone X (14.2) and Pixel 3 XL (11) devices.
Tested logo replacement using Android emulator and iOS simulator.

**Pull request merged**
