### PR TITLE
MM-23636: Default 'canPost' to true.

### PR DESCRIPTION
**Pull request by mkraft**
#### Summary

Default `canPost` to true.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-23636

### CODE REVIEW

**Comment by enahum** [comment]
@mkraft is `haveIPermission...` defaulting to true as well ?

**Comment by mkraft** [comment]
> @mkraft is `haveIPermission...` defaulting to true as well ?

Not really, [the `haveIChannelPermission` function](https://github.com/mattermost/mattermost-redux/blob/master/src/selectors/entities/roles.ts#L178), but it hasn't really changed in 2 years.

**Comment by svelle** [comment]
Installed the build. I'll test it over the weekend and see if it comes up again. Unfortunately I have no concrete repro steps apart from go out of the house and see if it happens again :(

**Comment by mkraft** [comment]
> Installed the build. I'll test it over the weekend and see if it comes up again. Unfortunately I have no concrete repro steps apart from go out of the house and see if it happens again :(

Be careful leaving the house!

**Comment by svelle** [comment]
@mkraft of course. I only leave for running and grocery shopping. No contact with other people as much as possible. ;)

**Comment by svelle** [comment]
not seeing it anymore on the app version I'm running. only the other issues I ran by elias but they're unrelated to this one :)

**Comment by enahum** [comment]
@mkraft this PR has been merged but I would encourage you to investigate why `canPost` was being undefined at times and needed this default value

**Comment by mkraft** [comment]
> @mkraft this PR has been merged but I would encourage you to investigate why `canPost` was being undefined at times and needed this default value

The [original pull request](https://github.com/mattermost/mattermost-mobile/pull/3904) that uses this permission check has very little code. It does a call to `haveIChannelPermission` and then passes that value to 5 existing branching statements, 1 existing component parameter, and 1 totally new branching statement (for the post options, which didn't see the issue). Things that could go wrong include:

1. `PostTextbox` doesn't get a `currentChannel` from [`const currentChannel = getCurrentChannel(state);`](https://github.com/mattermost/mattermost-mobile/pull/3904/files#diff-70f2c5b643ae72e5e121e1c528a9f526R37)
1. Some websocket connection was missed so the Redux state didn't get updated.

That's all I can think of...

I'm thinking #2 is likely the case because there was a migrations *for that particular permission* and @svelle did not have a stable connection when he experienced the issue.

**Pull request merged**
