### PR TITLE
MM-54936 fix: render latex in messages

### PR DESCRIPTION
**Pull request by jannikbertram**
#### Summary

Update `commonmark-react-renderer` package to the latest version. This will fix the following issues:

- Show LaTex in the "Channels" view
- Avoid error when clicking on "Threads" when a message contains LaTex
- Show the max nodes warning for messages with too many nodes

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-54936
Fixes https://github.com/mattermost/mattermost/issues/24982

#### Checklist

- [ ] Added or updated unit tests (required for all new features)
- [x] Has UI changes
- [ ] Includes text changes and localization file updates
- [ ] Have tested against the 5 core themes to ensure consistency between them.

#### Device Information
This PR was tested on: IPhone SE, iOS 16.2

#### Screenshots

|  before  |  after  |
|----|----|
| Screenshot 2023-10-24 at 22 58 50 | Screenshot 2023-10-24 at 22 59 50 
| Screenshot 2023-10-24 at 22 58 25 | Screenshot 2023-10-24 at 22 58 35 
| Screenshot 2023-10-24 at 22 54 41 | Screenshot 2023-10-24 at 22 54 59 |

#### Release Note

```release-note
* Fix rendering of LaTex messages
```

### CODE REVIEW

**Comment by jannikbertram** [comment]
@hmhealey here is the PR to update the library version :)

**Comment by hmhealey** [comment]
Thanks for updating to the new version too! I'm going to quickly test this locally, but it looks like it should be good to go

**Review by hmhealey — APPROVED** [review]
Looks good to me!

I found it odd that we don't actually render the Latex in the Threads list, but since we don't render other Markdown there either, that seems intentional

**Comment by enahum** [comment]
@amyblais 2.10 cherry pick?

**Review by larkox — APPROVED** [review]

**Comment by jannikbertram** [comment]
> I found it odd that we don't actually render the Latex in the Threads list, but since we don't render other Markdown there either, that seems intentional

I thought the same. It's a bit surprising to me that the Threads screen uses a different message rendering method than the Channels screen. This will just make it work like it used to be, but perhaps we should create a follow-up issue to unify the message rendering

**Comment by hmhealey** [comment]
This is the commonmark-react-renderer PR so we can find it later if needed: https://github.com/mattermost/commonmark-react-renderer/pull/6

**Review by yasserfaraazkhan — APPROVED** [review]
tested this on the android app.
In the [test the channel ](https://community.mattermost.com/core/pl/543iporiei8odprtgte7iax8zc) by posting messages within threads. Opening threads view, and permalink of the latex message on mobile, the app did not crash.
the messages were shows as expected.
rn_image_picker_lib_temp_f8c6d486-7083-46c1-8be6-847fdc161c34

**Comment by marianunez** [comment]
> tested this on the android app. In the [test the channel ](https://community.mattermost.com/core/pl/543iporiei8odprtgte7iax8zc) by posting messages within threads. Opening threads view, and permalink of the latex message on mobile, the app did not crash. the messages were shows as expected. rn_image_picker_lib_temp_f8c6d486-7083-46c1-8be6-847fdc161c34

@yasserfaraazkhan can you double check adding the latex on the root post? It's seems the issue was with the root post having that markdown in the Threads view

**Comment by yasserfaraazkhan** [comment]
Sure@marianunez
I [used this](https://community.mattermost.com/core/pl/que5jwqkjp81mpquktojs897yo)
root post in thread view.

Should I try some more examples?
rn_image_picker_lib_temp_fbbaed3e-6d74-4087-801e-127ccf85b497

**Review by yasserfaraazkhan — APPROVED** [review]

**Pull request merged**
