### PR TITLE
Optimize png image with zopflipng lossless compression

### PR DESCRIPTION
**Pull request by PeterDaveHello**
#### Summary
Recompress the PNG images losslessly via Google's [zopflipng](http://github.com/google/zopfli) to reduce the application size without losing quality!

The parameters used in this optimization were: `zopflipng --iterations=600 --keepchunks=iCCP --lossy_transparent --splitting=3` 

153 images optimized as below:
```
 android/app/src/main/res/drawable-hdpi/ic_notif_action_reply.png       | Bin 630 -> 413 bytes
 android/app/src/main/res/drawable-hdpi/splash.png                      | Bin 10072 -> 7424 bytes
 android/app/src/main/res/drawable-mdpi/ic_notif_action_reply.png       | Bin 508 -> 348 bytes
 android/app/src/main/res/drawable-mdpi/splash.png                      | Bin 5500 -> 4026 bytes
 android/app/src/main/res/drawable-xhdpi/ic_notif_action_reply.png      | Bin 925 -> 610 bytes
 android/app/src/main/res/drawable-xhdpi/splash.png                     | Bin 18276 -> 13697 bytes
 android/app/src/main/res/drawable-xxhdpi/ic_notif_action_reply.png     | Bin 1377 -> 833 bytes
 android/app/src/main/res/drawable-xxhdpi/splash.png                    | Bin 25187 -> 18942 bytes
 android/app/src/main/res/drawable-xxxhdpi/ic_notif_action_reply.png    | Bin 2075 -> 1261 bytes
 android/app/src/main/res/drawable-xxxhdpi/splash.png                   | Bin 34015 -> 25646 bytes
 android/app/src/main/res/mipmap-hdpi/ic_launcher.png                   | Bin 3380 -> 2261 bytes
 android/app/src/main/res/mipmap-hdpi/ic_notification.png               | Bin 1220 -> 1035 bytes
 android/app/src/main/res/mipmap-mdpi/ic_launcher.png                   | Bin 2049 -> 1461 bytes
 android/app/src/main/res/mipmap-mdpi/ic_notification.png               | Bin 971 -> 847 bytes
 android/app/src/main/res/mipmap-xhdpi/ic_launcher.png                  | Bin 4501 -> 3010 bytes
 android/app/src/main/res/mipmap-xhdpi/ic_notification.png              | Bin 1519 -> 1225 bytes
 android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png                 | Bin 6993 -> 4525 bytes
 android/app/src/main/res/mipmap-xxhdpi/ic_notification.png             | Bin 2141 -> 1659 bytes
 android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png                | Bin 9824 -> 6186 bytes
 android/app/src/main/res/mipmap-xxxhdpi/ic_notification.png            | Bin 2825 -> 2052 bytes
 assets/base/images/channel_info/pin.png                                | Bin 328 -> 304 bytes
 assets/base/images/channel_info/pin@2x.png                             | Bin 900 -> 642 bytes
 assets/base/images/channel_info/pin@3x.png                             | Bin 1334 -> 925 bytes
 assets/base/images/gitlab.png                                          | Bin 665 -> 509 bytes
 assets/base/images/icon.png                                            | Bin 472719 -> 8285 bytes
 assets/base/images/icons/brokenimage.png                               | Bin 534 -> 492 bytes
 assets/base/images/icons/code.png                                      | Bin 1393 -> 1382 bytes
 assets/base/images/icons/excel.png                                     | Bin 477 -> 472 bytes
 assets/base/images/icons/generic.png                                   | Bin 2262 -> 2256 bytes
 assets/base/images/icons/image.png                                     | Bin 1012 -> 1006 bytes
 assets/base/images/icons/patch.png                                     | Bin 1506 -> 1504 bytes
 assets/base/images/icons/pdf.png                                       | Bin 2301 -> 2289 bytes
 assets/base/images/icons/ppt.png                                       | Bin 2018 -> 2015 bytes
 assets/base/images/icons/reaction.png                                  | Bin 1633 -> 929 bytes
 assets/base/images/icons/video.png                                     | Bin 662 -> 659 bytes
 assets/base/images/icons/word.png                                      | Bin 617 -> 615 bytes
 assets/base/images/icons/youtube-play-icon.png                         | Bin 1573 -> 1304 bytes
 assets/base/images/logo.png                                            | Bin 16885 -> 1517 bytes
 assets/base/images/menu.png                                            | Bin 738 -> 339 bytes
 assets/base/images/no_results/pin.png                                  | Bin 907 -> 656 bytes
 assets/base/images/no_results/pin@2x.png                               | Bin 1959 -> 1274 bytes
 assets/base/images/no_results/pin@3x.png                               | Bin 2650 -> 1923 bytes
 assets/base/images/post_header/flag.png                                | Bin 186 -> 129 bytes
 assets/base/images/post_header/flag@2x.png                             | Bin 257 -> 166 bytes
 assets/base/images/post_header/flag@3x.png                             | Bin 321 -> 200 bytes
 assets/base/images/post_header/pin.png                                 | Bin 245 -> 190 bytes
 assets/base/images/post_header/pin@2x.png                              | Bin 425 -> 306 bytes
 assets/base/images/post_header/pin@3x.png                              | Bin 647 -> 404 bytes
 assets/base/images/post_menu/copy.png                                  | Bin 293 -> 191 bytes
 assets/base/images/post_menu/copy@2x.png                               | Bin 493 -> 273 bytes
 assets/base/images/post_menu/copy@3x.png                               | Bin 719 -> 385 bytes
 assets/base/images/post_menu/edit.png                                  | Bin 399 -> 300 bytes
 assets/base/images/post_menu/edit@2x.png                               | Bin 851 -> 602 bytes
 assets/base/images/post_menu/edit@3x.png                               | Bin 1278 -> 836 bytes
 assets/base/images/post_menu/emoji.png                                 | Bin 400 -> 299 bytes
 assets/base/images/post_menu/emoji@2x.png                              | Bin 883 -> 573 bytes
 assets/base/images/post_menu/emoji@3x.png                              | Bin 1558 -> 915 bytes
 assets/base/images/post_menu/flag.png                                  | Bin 365 -> 238 bytes
 assets/base/images/post_menu/flag@2x.png                               | Bin 612 -> 367 bytes
 assets/base/images/post_menu/flag@3x.png                               | Bin 878 -> 502 bytes
 assets/base/images/post_menu/link.png                                  | Bin 441 -> 330 bytes
 assets/base/images/post_menu/link@2x.png                               | Bin 945 -> 683 bytes
 assets/base/images/post_menu/link@3x.png                               | Bin 1471 -> 1015 bytes
 assets/base/images/post_menu/pin.png                                   | Bin 448 -> 333 bytes
 assets/base/images/post_menu/pin@2x.png                                | Bin 920 -> 649 bytes
 assets/base/images/post_menu/pin@3x.png                                | Bin 1414 -> 953 bytes
 assets/base/images/post_menu/reply.png                                 | Bin 380 -> 275 bytes
 assets/base/images/post_menu/reply@2x.png                              | Bin 737 -> 489 bytes
 assets/base/images/post_menu/reply@3x.png                              | Bin 1046 -> 693 bytes
 assets/base/images/post_menu/trash.png                                 | Bin 511 -> 393 bytes
 assets/base/images/post_menu/trash@2x.png                              | Bin 952 -> 663 bytes
 assets/base/images/post_menu/trash@3x.png                              | Bin 1435 -> 982 bytes
 assets/base/images/send.png                                            | Bin 1289 -> 792 bytes
 assets/base/images/status/archive_avatar.png                           | Bin 325 -> 205 bytes
 assets/base/images/status/away.png                                     | Bin 979 -> 520 bytes
 assets/base/images/status/away_avatar.png                              | Bin 675 -> 438 bytes
 assets/base/images/status/dnd.png                                      | Bin 818 -> 430 bytes
 assets/base/images/status/dnd_avatar.png                               | Bin 553 -> 367 bytes
 assets/base/images/status/offline.png                                  | Bin 1162 -> 543 bytes
 assets/base/images/status/offline_avatar.png                           | Bin 727 -> 468 bytes
 assets/base/images/status/online.png                                   | Bin 1092 -> 547 bytes
 assets/base/images/status/online_avatar.png                            | Bin 664 -> 438 bytes
 assets/base/images/themes/check.png                                    | Bin 571 -> 568 bytes
 assets/base/images/themes/mattermost.png                               | Bin 994 -> 988 bytes
 assets/base/images/themes/mattermost@2x.png                            | Bin 2095 -> 2084 bytes
 assets/base/images/themes/mattermost@3x.png                            | Bin 3529 -> 3524 bytes
 assets/base/images/themes/mattermost_dark.png                          | Bin 910 -> 899 bytes
 assets/base/images/themes/mattermost_dark@2x.png                       | Bin 1976 -> 1957 bytes
 assets/base/images/themes/mattermost_dark@3x.png                       | Bin 3375 -> 3344 bytes
 assets/base/images/themes/organization.png                             | Bin 996 -> 988 bytes
 assets/base/images/themes/organization@2x.png                          | Bin 2109 -> 2094 bytes
 assets/base/images/themes/organization@3x.png                          | Bin 3529 -> 3524 bytes
 assets/base/images/themes/windows_dark.png                             | Bin 905 -> 895 bytes
 assets/base/images/themes/windows_dark@2x.png                          | Bin 1961 -> 1936 bytes
 assets/base/images/themes/windows_dark@3x.png                          | Bin 3354 -> 3345 bytes
 assets/base/images/thumb.png                                           | Bin 1102 -> 884 bytes
 assets/base/images/thumb@2x.png                                        | Bin 1845 -> 1352 bytes
 assets/base/images/thumb@3x.png                                        | Bin 2589 -> 1833 bytes
 assets/base/images/video_player/fullscreen@2x.png                      | Bin 469 -> 212 bytes
 assets/base/images/video_player/fullscreen@3x.png                      | Bin 696 -> 277 bytes
 assets/base/images/video_player/pause@2x.png                           | Bin 284 -> 156 bytes
 assets/base/images/video_player/pause@3x.png                           | Bin 367 -> 179 bytes
 assets/base/images/video_player/play@2x.png                            | Bin 934 -> 460 bytes
 assets/base/images/video_player/play@3x.png                            | Bin 1442 -> 677 bytes
 assets/base/images/video_player/replay@2x.png                          | Bin 1875 -> 936 bytes
 assets/base/images/video_player/replay@3x.png                          | Bin 2856 -> 1349 bytes
 assets/base/release/icons/android/mipmap-hdpi/ic_launcher.png          | Bin 3196 -> 1963 bytes
 assets/base/release/icons/android/mipmap-mdpi/ic_launcher.png          | Bin 1987 -> 1292 bytes
 assets/base/release/icons/android/mipmap-xhdpi/ic_launcher.png         | Bin 4251 -> 2574 bytes
 assets/base/release/icons/android/mipmap-xxhdpi/ic_launcher.png        | Bin 6708 -> 3883 bytes
 assets/base/release/icons/android/mipmap-xxxhdpi/ic_launcher.png       | Bin 9627 -> 5366 bytes
 assets/base/release/icons/ios/20.png                                   | Bin 596451 -> 900 bytes
 assets/base/release/icons/ios/20@2x.png                                | Bin 465953 -> 2304 bytes
 assets/base/release/icons/ios/20@3x.png                                | Bin 7592 -> 5593 bytes
 assets/base/release/icons/ios/29.png                                   | Bin 3237 -> 1940 bytes
 assets/base/release/icons/ios/29@2x.png                                | Bin 7146 -> 5234 bytes
 assets/base/release/icons/ios/29@3x.png                                | Bin 11590 -> 8720 bytes
 assets/base/release/icons/ios/40.png                                   | Bin 465953 -> 2304 bytes
 assets/base/release/icons/ios/40@2x.png                                | Bin 10741 -> 7974 bytes
 assets/base/release/icons/ios/40@3x.png                                | Bin 17323 -> 13049 bytes
 assets/base/release/icons/ios/76.png                                   | Bin 9707 -> 7293 bytes
 assets/base/release/icons/ios/76@2x.png                                | Bin 21943 -> 16141 bytes
 assets/base/release/icons/ios/83.5@2x.png                              | Bin 16249 -> 12324 bytes
 assets/base/release/icons/ios/Icon-60@2x.png                           | Bin 472806 -> 8064 bytes
 assets/base/release/icons/ios/Icon-60@3x.png                           | Bin 477861 -> 11646 bytes
 assets/base/release/icons/ios/iTunesArtwork@2x.png                     | Bin 470815 -> 304313 bytes
 assets/base/release/splash_screen/android/drawable-hdpi/splash.png     | Bin 10072 -> 7424 bytes
 assets/base/release/splash_screen/android/drawable-mdpi/splash.png     | Bin 5500 -> 4026 bytes
 assets/base/release/splash_screen/android/drawable-xhdpi/splash.png    | Bin 18276 -> 13697 bytes
 assets/base/release/splash_screen/android/drawable-xxhdpi/splash.png   | Bin 25187 -> 18942 bytes
 assets/base/release/splash_screen/android/drawable-xxxhdpi/splash.png  | Bin 34015 -> 25646 bytes
 assets/base/release/splash_screen/ios/splash.png                       | Bin 15341 -> 12479 bytes
 fastlane/metadata/android/en-US/images/icon.png                        | Bin 33178 -> 16427 bytes
 fastlane/metadata/android/en-US/images/promoGraphic.png                | Bin 8097 -> 5937 bytes
 fastlane/metadata/android/en-US/images/tvBanner.png                    | Bin 67387 -> 61128 bytes
 ios/Mattermost/0155-keys.png                                           | Bin 2532 -> 2406 bytes
 ios/Mattermost/Images.xcassets/AppIcon.appiconset/20.png               | Bin 594312 -> 1001 bytes
 ios/Mattermost/Images.xcassets/AppIcon.appiconset/20@2x.png            | Bin 596567 -> 2769 bytes
 ios/Mattermost/Images.xcassets/AppIcon.appiconset/20@3x.png            | Bin 599380 -> 4971 bytes
 ios/Mattermost/Images.xcassets/AppIcon.appiconset/29.png               | Bin 595306 -> 1837 bytes
 ios/Mattermost/Images.xcassets/AppIcon.appiconset/29@2x.png            | Bin 599166 -> 4738 bytes
 ios/Mattermost/Images.xcassets/AppIcon.appiconset/29@3x.png            | Bin 602954 -> 7220 bytes
 ios/Mattermost/Images.xcassets/AppIcon.appiconset/40.png               | Bin 596567 -> 2769 bytes
 ios/Mattermost/Images.xcassets/AppIcon.appiconset/40@2x.png            | Bin 601775 -> 6465 bytes
 ios/Mattermost/Images.xcassets/AppIcon.appiconset/40@3x.png            | Bin 608831 -> 11185 bytes
 ios/Mattermost/Images.xcassets/AppIcon.appiconset/76.png               | Bin 601174 -> 5951 bytes
 ios/Mattermost/Images.xcassets/AppIcon.appiconset/76@2x.png            | Bin 613631 -> 13053 bytes
 ios/Mattermost/Images.xcassets/AppIcon.appiconset/83.5@2x.png          | Bin 617068 -> 15030 bytes
 ios/Mattermost/Images.xcassets/AppIcon.appiconset/Icon-60@2x.png       | Bin 608831 -> 11185 bytes
 ios/Mattermost/Images.xcassets/AppIcon.appiconset/Icon-60@3x.png       | Bin 620249 -> 16888 bytes
 ios/Mattermost/Images.xcassets/AppIcon.appiconset/iTunesArtwork@2x.png | Bin 884086 -> 288554 bytes
 ios/MattermostShare/Images/generic.png                                 | Bin 45380 -> 33406 bytes
 ios/SplashScreenResource/splash.png                                    | Bin 15341 -> 12479 bytes
```

### CODE REVIEW

**Comment by enahum** [comment]
@esethna what do you think, 1.18 or 1.19?

**Comment by PeterDaveHello** [comment]
@saturninoabril sure!

**Comment by jasonblais** [comment]
@enahum Does this need dev testing before merge (I noticed it has both labels)

**Comment by enahum** [comment]
@jasonblais Yes! I’ll have someone from my team test this.

**Comment by jasonblais** [comment]
Thanks Elias, removed `Ready to Merge` label until testing is completed

**Comment by enahum** [comment]
@saturninoabril can you test this PR and build the app locally in both beta and non-beta builds.

**Comment by saturninoabril** [comment]
@enahum Sure, will do that.

**Comment by saturninoabril** [comment]
@enahum Built the app and done some quick tests observing icons and images and looks fine to me.

**Comment by PeterDaveHello** [comment]
Sent another one here: https://github.com/mattermost/desktop/pull/981
Let me know if you'd like to have more ;)

**Pull request merged**
