### PR TITLE
fix(MM-60638): Provider Paths

### PR DESCRIPTION
**Pull request by rahimrahman**
#### Summary

See ticket.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-60638
https://mattermost.atlassian.net/browse/MM-60637

#### Checklist

- [ ] Added or updated unit tests (required for all new features)
- [ ] Has UI changes
- [ ] Includes text changes and localization file updates
- [ ] Have tested against the 5 core themes to ensure consistency between them.
- [ ] Have run E2E tests by adding label `E2E iOS tests for PR`.

#### Device Information
This PR was tested on: 
Android Google Pixel 6

#### Release Note

```release-note

```

### CODE REVIEW

**Comment by rahimrahman** [comment]
> Have we tried everything related to files?

I have tried on Android physical device: Google Pixel 6 as many places as I can that uses react-native-file-viewer and react-native-share.

I must admit, there are a few methods I thought I traced down to the proper components (mostly file search results), but I'm not 100%.

Right now, I want @enzowritescode to validate and see if the changes make a different at all.

**Review by enzowritescode — APPROVED** [review]

**Comment by esarafianou** [comment]
@rahimrahman we need 2 dev reviews on top of the security review.

**Comment by rahimrahman** [comment]
@larkox @enahum adding you all for code review.

But I am going to work with @yasserfaraazkhan to identify all the places that uses react-native-share and react-native-file-viewer.  My problem right now is I don't have enough confidence that I'm testing all the instances of Share.open() or FileViewer.open().

**Review by enahum — APPROVED** [review]
looks ok.. just check that you can extract the logs, if that is ok, then consider approved.

**Review by larkox — APPROVED** [review]
Codewise, the changes seem solid, but as has been said before, just make sure share works in both directions (share the logs from mattermost (not sure if we have the ability to share other stuff like images), and share other files to mattermost).

**Comment by rahimrahman** [comment]
I've been able to report problem from MM Beta app.  Didn't work very well from locally running app:

Screenshot 2024-11-05 at 2 29 21 PM


Able to share from the outside of the app into Mattermost:


https://github.com/user-attachments/assets/cd788adc-2e8c-44a7-b38b-86fa0fad1000

**Comment by rahimrahman** [comment]
@yasserfaraazkhan I'm going to continue testing and find out where else react-native-share and react-native-file-viewer is being used, other than Report a Problem (react-native-share).

But if you can run the app and do some file opening and sharing, that would be great too.  Particularly, opening a file and probably downloading it to your local android device (internal or external SD).

**Comment by enahum** [comment]
> @yasserfaraazkhan I'm going to continue testing and find out where else react-native-share and react-native-file-viewer is being used, other than Report a Problem (react-native-share).
> 
> 
> 
> But if you can run the app and do some file opening and sharing, that would be great too.  Particularly, opening a file and probably downloading it to your local android device (internal or external SD).

The gallery, to download and share the files / media

**Comment by rahimrahman** [comment]
> The gallery, to download and share the files / media

When you say gallery, you meant when you click on an image in certain post, and then it opens up Photo/Gallery view, then you have the option to download or share it, right?

**Comment by enahum** [comment]
> > The gallery, to download and share the files / media
> 
> 
> 
> When you say gallery, you meant when you click on an image in certain post, and then it opens up Photo/Gallery view, then you have the option to download or share it, right?

Yes

**Comment by rahimrahman** [comment]
I did find the "Download" from the bottom sheet is not working (on .mp4).  But this is an existing problem, as this demo video is from latest MM mobile app on Android.

https://github.com/user-attachments/assets/c124b0af-ed42-4623-8de9-7baabda8c838

**Comment by enahum** [comment]
@rahimrahman if it is an existing issue then we should just create a separate ticket.

**Review by yasserfaraazkhan — APPROVED** [review]
Thank you @rahimrahman 
I tried sharing multiple file formats from the mm-app to other app. Also from outside to the mm-app.
These flows shared the files successfully

**Comment by rahimrahman** [comment]
Merging but the issue with downloading movie files on MM Android app is on this ticket: https://mattermost.atlassian.net/browse/MM-61694

**Pull request merged**
