### PR TITLE
RN-189/RN-241 Updated emoji appearance

### PR DESCRIPTION
**Pull request by hmhealey**
- Makes non-square emojis render correctly
- Vertically centres emojis on iOS (Android doesn't support this). This looks pretty good on regular text, but is a bit off on headers. It's still much better than it was before.
- Adjusted line height and emoji sizes so that emojis don't push text out of the way

#### Ticket Link
https://mattermost.atlassian.net/browse/RN-189
https://mattermost.atlassian.net/browse/RN-241

#### Checklist
- Has UI changes

#### Device Information
This PR was tested on: iOS Simulator (iPhone 6, iOS 10.3), Nexus 5 (Android 6.0.1)

#### Screenshots
Before (iOS): 
screen shot 2017-09-12 at 11 24 40 am

After (iOS):
screen shot 2017-09-12 at 11 35 13 am

Before (Android):

After (Android):

### CODE REVIEW

**Comment by hmhealey** [comment]
Adding @asaadmahmood since I played with the line height a bit to get this to work

**Comment by enahum** [comment]
waiting the review of @asaadmahmood so we can merge this one

**Comment by asaadmahmood** [comment]
Hey @hmhealey in android, the emojis still don't look vertically centered? Don't we have a vertical-align option that works in both places?

screen shot 2017-09-13 at 6 20 21 am

**Comment by hmhealey** [comment]
@asaadmahmood React Native doesn't allow you to do much with images that are inline with text other than change their size. On iOS, you can push them around with transforms or margins, but Android doesn't support that

**Comment by asaadmahmood** [comment]
@hmhealey paddings on the images doesn't work either?

**Comment by hmhealey** [comment]
They have no effect on Android. I spent some time looking at the native Java code, and I couldn't find any way to override it. It might be possible if we give up on the RN text rendering code entirely for posts, but that's a ton of work

**Comment by asaadmahmood** [comment]
Oh and one minor thing, sorry for approval.
Looks like the large emoticon icon is going down a bit more vertically compared to the other icons in IOS. Can we move it a bit up in the headers?

screen shot 2017-09-13 at 7 57 42 pm

**Comment by hmhealey** [comment]
How about this? 
screen shot 2017-09-13 at 11 19 51 am

**Comment by asaadmahmood** [comment]
Looks beter, I think we can get this in, and experience it live.

**Pull request merged**
