### PR TITLE
Apple Watch App

### PR DESCRIPTION
**Pull request by ccbrown**
#### Summary
The ideal of the Apple Watch Series 3 is to be able to leave your phone behind, but remain reachable and connected. I'm pretty close to being able to do that: I can respond to emails, texts, phone calls, Slack messages, GitHub PRs, and a lot more without having to pull out my phone or even have it with me. But I can't respond to Mattermost messages.

So this is a priority for me. I'm hoping to get this merged and distributed alongside the official iOS app, but even if for whatever reason it doesn't pass PM approval or make it into the codebase, I'm doing this for myself anyways. :)

Features:

* Browse all joined channels including direct and group messages.
* View post threads.
* Create new posts in any previously joined channel.
* Reply to any post or thread.
* Tap notification to open corresponding post thread.
* Add complications to your watch face.

screen shot 2017-09-26 at 11 44 54 pm

screen shot 2017-09-26 at 11 45 10 pm

screen shot 2017-09-26 at 11 45 41 pm

screen shot 2017-09-26 at 11 46 10 pm

screen shot 2017-09-26 at 11 47 03 pm

#### Ticket Link
N/A

#### Checklist
No changes to the existing apps. There are UI changes in the entirely new watch app of course.

#### Device Information
WatchOS 4

#### Screenshots
See above.

### CODE REVIEW

**Comment by ccbrown** [comment]
It's a little rough in some respects. E.g. it doesn't get posts in real-time. But I think it meets the bar for watch apps. It's certainly more capable than Slack's app.

I have it installed on my watch and will be doing some real-world testing.

Can I get some PM weigh-in on this?

**Comment by ccbrown** [comment]
After a work week of real-world use, I'm really happy with this.

I want to make sure the ball keeps rolling with this, so I've created a JIRA ticket: https://mattermost.atlassian.net/browse/PLT-7769

So hopefully we can decide on some next steps when we triage that.

**Comment by enahum** [comment]
@ccbrown I’ve tested this today and it looks pretty good, I believe @esethna is going to be testing this during the next few days, I had to rebase it in order for him to do the testing, you can find the rebase branch `watch` in this repo if you want to use it to update this PR

**Comment by esethna** [comment]
@ccbrown really good work on it. When you have a chance please review my comments above ^. Happy to jump into a conversation on anything if you want to discuss further.

cc// @enahum

**Comment by ccbrown** [comment]
@esethna 

1. It should be possible to make this work without requiring you to open your phone to sync up, but I couldn't get the API to work properly at the time. May have been a watchOS 4 bug, but I'll definitely revisit it.
2. Easy.
3. The watch model would definitely have a big performance impact here. But yeah, we can improve things. Showing only recent DMs would be an easy win.
4. Easy.
5. Easy.
6. We could poll the server more frequently. I don't think we can use websockets on watchOS, but I'd have to look into it more to confirm.
7. Pretty sure that's totally beyond the app's control as that page is a built-in OS thing, but can double check.
8. Push notifications are really hard to test in development... but yes, tapping the notification should open the thread or DM it was posted in.

We should create a ticket for me to iterate on this if we want to prioritize it.

**Pull request closed without merging**
