### PR TITLE
MM-25792 Ensure previous state is cleared when logout

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
Make sure previous redux state is cleared when you logout from a server so there is no conflicting data or data that  does not belong when you switch servers.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-25792

### CODE REVIEW

**Comment by enahum** [comment]
@marianunez @Willyfrog can you please test the build posted here? as you guys reported the issue

**Comment by Willyfrog** [comment]
This one loaded townsquare on login on the new server.
But there was a new problem: when i pressed logout got a screen stating that something went wrong and teams could not be loaded.
(I have the screenshot, but GitHub mobile doesn't let me post it, I'll add another comment with it once I can)

**Comment by Willyfrog** [comment]
Screenshot_2020-06-05-23-11-56-872_com mattermost rnbeta

**Comment by enahum** [comment]
Guillermo, does it happen to you every time? I’m unable to repro this newest issue

**Comment by Willyfrog** [comment]
Not always, but it does reappear
I have a video happening 2 out of 3, I'll send it to you through mattermost

**Comment by marianunez** [comment]
I installed from the links above and was not able to reproduce the original issue.

However, just want to confirm that the build number did not increase and it still shows as build 296.

**Comment by enahum** [comment]
Yes this is a PR build nothing more... so that means build numbers remain the same.

Did you happen to see what Guillermo is reporting?

**Comment by marianunez** [comment]
I did not have any errors switching teams. However, my select team screen doesn't look like Guillermo screenshot above so not sure if we are testing the same thing. 
Screenshot_20200605-192720_Mattermost

**Comment by enahum** [comment]
@migbot plz review

**Pull request merged**
