### PR TITLE
[ICU-629] Add support for DM with deactivated channel (teammate)

### PR DESCRIPTION
**Pull request by saturninoabril**
#### Summary
Add support for DM with deactivated channel (teammate) similar to webapp.
- check whether the use of icon `trash` is appropriate
- check about the position of archived message below (in placed of `PostTextbox`)

#### Ticket Link
Jira ticket: [ICU-629](https://mattermost.atlassian.net/browse/ICU-629)

#### Checklist
- [x] Has UI changes

#### Device Information
This PR was tested on: [IOS and Android emulators, OS versions Iphone6/11.2, Nexus 5/6.0/API23] 

#### Screenshots
Android:
screen shot 2018-01-27 at 12 19 41 am
screen shot 2018-01-27 at 12 20 11 am

IOS:
screen shot 2018-01-26 at 11 53 41 pm
screen shot 2018-01-26 at 11 53 51 pm

### CODE REVIEW

**Comment by stephenkiers** [comment]
I don't really like the trash icon (as you already pointed out). I feel like a user with a slash through them may be more appropriate. (for ref: https://www.iconfinder.com/search/?q=deactivated+user) 

What format are our icons in? If it is an SVG, I could make a SVG icon for you to use in this case. Would that help? If they are icon-fonts or sprites that may be harder.

**Comment by saturninoabril** [comment]
@stephenkiers Here we are using `react-native-vector-icons/FontAwesome`. You'll find more [here](https://oblador.github.io/react-native-vector-icons/), just look at FontAwesome section. I didn't see it first but the closest icon we're using at webapp is the `archive` like below.

screen shot 2018-01-27 at 3 19 53 pm

At webapp, we're using SVG - [ArchiveIcon](https://github.com/mattermost/mattermost-webapp/blob/master/components/svg/archive_icon.jsx). It renders like this,
screen shot 2018-01-27 at 3 24 35 pm

@esethna Could you please help validate which icon is best to use? Thanks!

**Comment by enahum** [comment]
You know tou can use the same one as the webapp right? You can build the component like https://github.com/mattermost/mattermost-mobile/blob/master/app/components/status_icons/away_avatar.js

**Comment by enahum** [comment]
Sorry for the typo in the other post, but just wanted to clarify that we are not only using fontAwesome, also ionIcon, MaterialDesign, Foundation and there are more that we could use.

**Comment by stephenkiers** [comment]
yeah, if there is already a icon in the webapp, I vote for that being used. 

However, creating an icon based on the others is trivial though, and I could easily do for you. If the webapp one is really not representative a custom one may be a better UX.

**Comment by saturninoabril** [comment]
Thanks @enahum & @stephenkiers!
I added an ArchiveIcon using the same SVG from webapp.

Android:
screen shot 2018-01-29 at 6 02 53 am

IOS:
screen shot 2018-01-29 at 6 08 46 am

**Comment by hmhealey** [comment]
Adding @asaadmahmood to review the icon and position although that should be quick since it now matches the web app

**Comment by asaadmahmood** [comment]
Not sure if the trash icon is still being used, but the trash icon is smaller in comparison to the other icons, it should be bigger.
screen shot 2018-01-30 at 8 13 48 pm

**Comment by saturninoabril** [comment]
@asaadmahmood Not sure if there's something I need to do based from your comment. Please help clarify. Thanks!

**Comment by enahum** [comment]
I think @asaadmahmood was looking at the first screenshot and not the updated ones

**Comment by saturninoabril** [comment]
Cool, thanks!

**Pull request merged**
