### PR TITLE
Channel Bookmarks

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
This PR adds the channel bookmarks to mobile

In order to use it needs a server running https://github.com/mattermost/mattermost/pull/25449

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-54432

```release-note
Added channel bookmarks
```

This is the same as #7750

### CODE REVIEW

**Comment by enahum** [comment]
@jupenur that was weird.. anyway, did a rebase locally and force pushed the changes,.. now it all seems to be ok in that respect

**Review by calebroseland — APPROVED** [review]

**Comment by enahum** [comment]
@esarafianou added you as a reviewer for security, feel free to add someone else if you think is best.

**Review by sbishel — APPROVED** [review]
Several reviews here as well 
https://github.com/mattermost/mattermost-mobile/pull/7750

**Comment by enahum** [comment]
Ok given the lift I went ahead and merged

**Pull request merged**
