### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Weblate](https://translate.mattermost.com/projects/mattermost/mattermost-mobile_master/) for mattermost-languages-shipped/mattermost-mobile.

Current translation status:

Weblate translation status

### CODE REVIEW

**Review by cpanato — APPROVED** [review]

**Comment by cpanato** [comment]
@amyblais please confirm if we need to cherry pick to the release branch 1.48

**Comment by amyblais** [comment]
Yes, please.

**Comment by enahum** [comment]
This Pr has 11 file changes and the cherry pick just one, seems odd to me

**Comment by puerco** [comment]
@enahum yes, mattermod does not yet support cherrypicks for PRs merged by rebased or merge commit, I have to send these by manually.

**Comment by enahum** [comment]
@puerco any ETA on the PR submission ?

**Comment by puerco** [comment]
I should open the prs for all translation cherry picks later today. I'm finishing some adjustments to the CP code..

**Pull request merged**
