### PR TITLE
Fixes master branch from crashing when building in release mode

### LINKED ISSUE #2729: Android crash in production mode on master
Submit feature requests to http://www.mattermost.org/feature-requests/. File non-security related bugs here in the following format: 

#### Summary
Android crashes in production mode build only, on Android.
Branch release-1.19 works fine
Development build works fine

Here is the log:
[crash.log](https://github.com/mattermost/mattermost-mobile/files/3098135/crash.log)

#### Environment Information

- Device Name: Oneplus 5t
- OS Version: 9
- Mattermost App Version: master
- Mattermost Server Version: 5.10

#### Steps to reproduce
env BUILD_FOR_RELEASE=true VARIANT=release make run-android  

#### Expected behavior
No crash

#### Observed behavior
Crash on start

#### Possible fixes
No idea

### PR DESCRIPTION
**Pull request by enahum**
Fixes: #2757 and fixes #2729

### CODE REVIEW

**Comment by varungupta85** [comment]
@enahum I am observing a similar error in my app listed in #2757 and I have no idea what is causing it. I am not using mattermost but do you know what was broken in your case that fixed it or how I can go about find more information about this error.

**Comment by enahum** [comment]
@varungupta85 wow you sent me to fight a battle without weapons hehehehe,  there can be a million things really, I would start by trying to understand the errors in the build output  and go from there...

**Comment by varungupta85** [comment]
@enahum I am sorry. I was not sure what all information to provide you. There are no build errors. I only see a run time error when running the app in release mode and the error is exactly the same as reported in #2757 which is as below

```
2020-12-16 09:22:28.909 428-494/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.myapp, PID: 428
    com.facebook.react.common.JavascriptException: TypeError: r(d[2]) is not a function. (In 'r(d[2])(this)', 'r(d[2])' is an instance of Object), stack:
    <unknown>@521:145
    exports@477:81
    <unknown>@522:79
    h@2:1585
    <unknown>@521:139
    <unknown>@600:136
    <unknown>@551:319
    t@546:312
    <unknown>@605:70
    t@546:312
    <unknown>@603:94
    t@543:120
    <unknown>@541:513
    h@2:1585
    <unknown>@540:104
    h@2:1585
    <unknown>@539:185
    h@2:1585
    <unknown>@538:1122
    h@2:1585
    <unknown>@528:544
    h@2:1585
    <unknown>@527:109
    h@2:1585
    <unknown>@526:898
    h@2:1585
    <unknown>@466:207
    h@2:1585
    <unknown>@6:122
    h@2:1585
    d@2:958
    global code@2064:3
    
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:83)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:193)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:764)
```

To give a little more background, I have the app in production for a few years. Recently, we have planned to provide a web app for it and I ported the app to a mono-repo managed using yarn workspaces and created separate packages for the shared logic code. I am able to run the app in debug mode on both iOS and Android but in the release mode, although I am able to create the bundle file, it crashes as soon as it starts with the above error.

Now, I don't have much information about the exact error as it is minified but since guys fixed a very similar looking problem, I thought you may have an idea. I am just desperate for any kind of inputs since I have spent a bunch of time in figuring it out and I haven't found much yet.

Below is my package.json

```
{
  "name": "GalarmApp",
  "version": "3.11.0",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint .",
    "prepare": "cd .. && yarn patch-package"
  },
  "dependencies": {
    "@react-native-community/datetimepicker": "3.0.8",
    "@react-native-community/netinfo": "5.9.9",
    "@react-native-community/push-notification-ios": "1.8.0",
    "@react-native-community/slider": "3.0.3",
    "@react-native-firebase/analytics": "10.2.0",
    "@react-native-firebase/app": "10.2.0",
    "@react-native-firebase/auth": "10.2.0",
    "@react-native-firebase/database": "10.2.0",
    "@react-native-firebase/dynamic-links": "10.2.0",
    "@react-native-firebase/messaging": "10.2.0",
    "@react-native-firebase/storage": "10.2.0",
    "@sentry/react-native": "2.1.0",
    "fast-deep-equal": "3.1.3",
    "fast-memoize": "2.5.2",
    "firebase": "8.2.0",
    "galarm-config": "1.0.0",
    "galarm-ps-api": "1.0.0",
    "galarm-res": "1.0.0",
    "galarm-shared": "1.0.0",
    "i18n-js": "3.8.0",
    "invariant": "2.2.4",
    "libphonenumber-js": "1.9.6",
    "lodash": "4.17.20",
    "moment-timezone": "0.5.32",
    "prop-types": "15.7.2",
    "react": "17.0.1",
    "react-fast-compare": "3.2.0",
    "react-native": "0.64.0-rc.1",
    "react-native-action-button": "2.8.5",
    "react-native-animatable": "1.3.3",
    "react-native-collapsible": "1.5.3",
    "react-native-communications": "2.2.1",
    "react-native-config": "1.4.1",
    "react-native-contacts": "6.0.3",
    "react-native-country-picker-modal": "2.0.0",
    "react-native-device-info": "7.3.1",
    "react-native-dialogs": "1.1.1",
    "react-native-elements": "3.0.0-alpha.1",
    "react-native-fast-image": "8.3.4",
    "react-native-gifted-chat": "github:varungupta85/react-native-gifted-chat",
    "react-native-iap": "5.2.0",
    "react-native-image-crop-picker": "0.35.1",
    "react-native-keyboard-aware-scroll-view": "0.9.3",
    "react-native-keyboard-spacer": "0.4.1",
    "react-native-localize": "2.0.1",
    "react-native-navigation": "6.12.2",
    "react-native-parsed-text": "0.0.22",
    "react-native-permissions": "3.0.0",
    "react-native-radio-buttons": "1.0.0",
    "react-native-sound": "0.11.0",
    "react-native-store-review": "0.1.5",
    "react-native-swiper": "1.6.0",
    "react-native-uuid": "1.4.9",
    "react-native-vector-icons": "7.1.0",
    "react-redux": "7.2.2",
    "redux": "4.0.5",
    "redux-batched-subscribe": "0.1.6",
    "redux-persist": "6.0.0",
    "redux-thunk": "2.3.0",
    "reduxsauce": "1.2.0",
    "reselect": "4.0.0",
    "url": "0.11.0",
    "uuid": "8.3.2"
  },
  "devDependencies": {
    "@babel/core": "7.8.4",
    "@babel/runtime": "7.8.4",
    "@react-native-community/eslint-config": "1.1.0",
    "babel-jest": "25.1.0",
    "eslint": "6.5.1",
    "jest": "25.1.0",
    "metro-react-native-babel-preset": "0.64.0",
    "react-native-codegen": "0.0.6",
    "react-test-renderer": "17.0.1",
    "reactotron-react-native": "2.2.0",
    "reactotron-redux": "2.1.3"
  },
  "jest": {
    "preset": "react-native"
  }
}
```
I tried putting logs but none of the logs are printed, so I feel that it is happening during initialization phase only. If you have any inputs, please share. If you need any other information, please let me know.

**Comment by enahum** [comment]
is your babel config removing the console.logs from your code? maybe you want to disable that for a minute and give it a try? <- We've done this in the past to try and identify where in the code this is happening, most probably there is an `undefined` value somewhere in your code (probably  on init) that is causing it.

Also you may want to give `react-native-exception-handler` a try and see if you can log the unhandled exception.

In our case it might have been veery well identified by some logs in sentry

**Comment by varungupta85** [comment]
@enahum Okay, thanks for the inputs. I will try the react-native-exception-handler. We don't remove console logs but I just override the console log methods to not do anything in production environment. I will also remove that and give it a try. Thanks!

**Pull request merged**
