### PR TITLE
copy directly from v1

### PR DESCRIPTION
**Pull request by jfrerich**
#### Summary
WIP - Initial commit is a direct copy of all files from V1.

#### Checklist

- [ ] Added or updated unit tests (required for all new features)
- [ ] Has UI changes
- [ ] Includes text changes and localization file updates
- [ ] Have tested against the 5 core themes to ensure consistency between them.

#### Device Information
This PR was tested on: 

#### Release Note

```release-note

```

### CODE REVIEW

**Comment by enahum** [comment]
@jfrerich what is this and why? I'm asking cause I really want to understand as this can leave unwanted files and code in the new codebase

**Comment by jfrerich** [comment]
@enahum, this is the start of https://mattermost.atlassian.net/browse/MM-39711 which asks to port the settings from v1 
image

**Comment by enahum** [comment]
Ok two things:
1. Ircc this ticket was assigned to @avinashlng1080 as is dependent of the account screen
2. From my point of view, this is the wrong approach, porting does not mean copy, specially as the port requires to refactor things as needed, add typescript to everything and use functional components.
3. This set of screens even if is to port they can be massively improved, also there are things that we need to remove as they aren't used anymore and the modals implemented here for the different options should be changed to use the new bottom sheet.

I'm ok with having WIP PR's no problem, but at least let's try and keep them as clean as possible.

If you have a strong opionion on this please share it and we can discuss.

**Comment by jfrerich** [comment]
My intention was to do the following:

1. copy directly from v1
2. hook up the `Settings` `onPress` API to show the settings screenshots
3. hook up one of the simpler settings sub-menus (probably `About Mattermost`)
4. convert files in `About Mattermost` from .js to .ts 
5. Repeat for each Settings submenu

**Comment by enahum** [comment]
You could add thing as needed instead of everything in one go, specially cause that will help you avoid old or bad code and make improvements as you port.

Imagine you are porting from another language if you will

**Comment by jfrerich** [comment]
Fair enough.  I was looking at the Jira ticket and it implied to just port from v1.  I was looking at it from get this in asap for gekidou. 

How about I do the following? 
* hook up the settings menu
* hook up only one sub menu (Example: `about mattermost`)
* remove all else in this PR. 
* break the 1 jira ticket for settings into multiple

**Comment by jfrerich** [comment]
This PR will then only contain the `settings` menu hookup and each submenu can be added individually after in separate PRs?

**Comment by enahum** [comment]
You do you, I just prefer another cleaner approach, worst case scenario we close the PR and submit a cleaner one

**Comment by jfrerich** [comment]
I'm going to close this and work on a different ticket.  @avinashlng1080, if you submit a PR that handles the initial opening of the settings screen and want help porting the individual submenu screens, please ping me :)

**Pull request closed without merging**
