### PR TITLE
Sync with App Command Parser with Webapp

### PR DESCRIPTION
**Pull request by larkox**
#### Summary
The main changes are:
- Disallow executing non-leaf commands
- Add Rest field
- Filter empty options on static and dynamic selects

#### Ticket Link
None

#### Release Note
```release-note
App Commands: Add "Rest" field, filter empty options on static and dynamic selects, and prohibit executing non-leaf commands.
```

### CODE REVIEW

**Review by mickmister — APPROVED** [review]
LGTM

**Comment by mickmister** [comment]
The change is scoped to App commands, so if we have a release note we should be clear that this specific to App commands. I'm not sure if we really need a release note for this PR in the first place though

**Comment by larkox** [comment]
@enahum Friendly reminder to review this.

**Review by enahum — APPROVED** [review]

**Comment by enahum** [comment]
@larkox tests failing

**Comment by larkox** [comment]
@enahum The failing test should be the flaky test, if I am not mistaken. I will apply the fix I applied the other PR (increasing the wait time).

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- Non leaf command execution give clear error that a subcommand must be selected
- No issues found with positional arguments
- Regression tested Static and Dynamic selects
- Tested on Android and iOS

LGTM!
Sorry for the delay on this one @larkox

**Pull request merged**
