### PR TITLE
Adding guest accounts feature

### PR DESCRIPTION
**Pull request by jespino**
#### Summary
Adding guest accounts feature

### CODE REVIEW

**Comment by enahum** [comment]
@jespino this build is failing, conflicts need resolving and the build failed with
```
> mattermost-mobile@1.21.0 mmjstool /Users/****/workspace/mm/mobile-build-app-pr
> mmjstool "i18n" "extract-mobile" "--webapp-dir" "tmp/fake-webapp-dir" "--mobile-dir" "."

diff tmp/en.json assets/base/i18n/en.json
420d419
<   "mobile.select_team.guest_cant_join_team": "You don't belongs to any team and as a guest you can't join any team by yourself, you need to be invited or added by som  eone else.",
make: *** [i18n-extract-ci] Error 1
```

**Comment by jespino** [comment]
@enahum merged from master and removed the i18n string

**Comment by enahum** [comment]
@jespino I'll update it again cause master is broken

**Comment by ogi-m** [comment]
@jespino Seeing a couple issues so far:

1. Guest badge
- two different shades of grey instead of one
- badge corners should be rounded to match the [design](https://projects.invisionapp.com/d/main/default/?origin=v7#/console/17561763/364097715/preview)
IMG_6710

2. "This channel has guests" text is not aligned properly
IMG_6709

**Comment by jespino** [comment]
@ogi-m First ticket solved and cherry-picked to 1.22 branch, the rest of the tickets are moved to Jira, please create any new ticket in Jira

**Pull request merged**
