### PR TITLE
Fix Android: Text typed in Jump to... and Search box color

### PR DESCRIPTION
**Pull request by enahum**
#### Ticket Link
https://mattermost.atlassian.net/browse/RN-534

### CODE REVIEW

**Comment by enahum** [comment]
we don't but we could create a function, the whole thing why I had to do this is cause when we had it in the style the prop was being passed as a number

**Comment by hmhealey** [comment]
It would be nice if there was a way to get the actual style from the stylesheet, but I don't think that's possible

**Comment by mkraft** [comment]
@enahum Sorry I wasn't sure, were you going to create a function or leave the duplication?

**Comment by enahum** [comment]
I'm going to leave the duplication and rebase this

**Pull request merged**
