### PR TITLE
[MM-11083] Change App icons for android

### PR DESCRIPTION
**Pull request by sudheerDev**
#### Summary
Change android app icons

#### Ticket Link
[MM-11083](https://mattermost.atlassian.net/browse/MM-11083)

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Has UI changes

#### Device Information
This PR was tested on: [Android pixel2] 

#### Screenshots
screen shot 2018-07-26 at 5 11 09 pm

### CODE REVIEW

**Comment by sudheerDev** [comment]
@enahum How can I change icon playstore?. Can you point me to it?

**Comment by enahum** [comment]
Did you check that these are all the needed resolutions?

The ones you look for should be here https://github.com/mattermost/mattermost-mobile/tree/master/assets/base/release/icons/android

Also make sure they all get replaced by the fastlane script if you added another resolution or changed a file name

**Comment by sudheerDev** [comment]
@enahum 

For release build yes, that is where the icons reside and for beta: https://github.com/mattermost/mattermost-mobile/tree/master/android/app/src/main/res.

I replaced with appropriate icons in all the child folders with the same resolution images(I will cross check this again just to be sure). 

Back to my previous question - There is a playstore icon that needs to be changed as well and how can i change that.

**Comment by enahum** [comment]
@sudheerDev perhaps you are referring to these? https://github.com/mattermost/mattermost-mobile/tree/master/fastlane/metadata/android/en-US/images

**Comment by enahum** [comment]
@sudheerDev is this PR ready ?

**Comment by enahum** [comment]
going to merge this as one review might be enough

**Comment by saturninoabril** [comment]
👍

**Pull request merged**
