### PR TITLE
Replace package and imports for Kotlin files

### PR DESCRIPTION
**Pull request by enahum**
```release-note
NONE
```

### CODE REVIEW

**Comment by pbaveja** [comment]
Hey @enahum, the android build on the main branch is failing in general - not just for kotlin files.
```
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-webrtc:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)
```
Is that an issue you're fixing too? If not, I'll be happy to raise an issue

**Comment by enahum** [comment]
@pbaveja that error is totally different.. you are running out of memory

**Comment by pbaveja** [comment]
> @pbaveja that error is totally different.. you are running out of memory

The error comes with the task `Execution failed for task ':react-native-webrtc:compileReleaseJavaWithJavac'`
Referencing this: https://github.com/react-native-webrtc/react-native-webrtc/issues/666, it leads me to believe that the error is about incompatibility with this package. 

Correct me if I'm wrong

**Comment by enahum** [comment]
@pbaveja I'm not seeing the error you linked. can you share more in terms of what branch are you trying to build?

**Comment by pbaveja** [comment]
> @pbaveja I'm not seeing the error you linked. can you share more in terms of what branch are you trying to build?

I'm building directly from the main branch. I even tried building from the release-2.1 branch. The same webrtc error came.

**Comment by enahum** [comment]
@pbaveja one more question, you are building in debug or release ?

**Comment by pbaveja** [comment]
> @pbaveja one more question, you are building in debug or release mode?

I'm building in release mode

**Comment by enahum** [comment]
@pbaveja last question, what command are you using to build the app ?

**Comment by pbaveja** [comment]
> @pbaveja last question, what command are you using to build the app ?

I'm using `npm run build:android`

**Pull request merged**
