### PR TITLE
Add set status feature

### PR DESCRIPTION
**Pull request by csduarte**
Adds set user status functionality.

## iOS
ios_left_drawer
ios_set_status

## Android
android_left_drawer
android_set_status

@miguelespinoza

### CODE REVIEW

**Comment by enahum** [comment]
@miguelespinoza how will this work with multiple teams?

**Comment by miguelespinoza** [comment]
Just fyi to anyone reading this PR. It's on hold until we have the right side drawer

**Comment by enahum** [comment]
@miguelespinoza you are working on that right side drawer right?

**Comment by enahum** [comment]
closing in favor of a PR based on the right drawer

**Pull request closed without merging**
