### PR TITLE
[MM-19703] Dropdown on the server URL field with servers recently connected to #14605

### PR DESCRIPTION
**Pull request by thegeekybaniya**
#### Summary

This feature provides an easier way for mobile users to switch servers and remember previously used servers from the "Enter a Server" screen.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-server/issues/14605
#### Checklist

- [ ] Added or updated unit tests (required for all new features)
- [x] Has UI changes
- [ ] Includes text changes and localization file updates

#### Device Information
This PR was tested on:  
Nexus 7 API 29
Nexus 2 API 28
#### Screenshots

image
image

### CODE REVIEW

**Comment by thegeekybaniya** [comment]
I will fix and get back to you.

**Comment by enahum** [comment]
@thegeekybaniya can you address the UI issues on iOS?  Also there are some performance issues in the PR, can you try and address them?

**Comment by thegeekybaniya** [comment]
@enahum I have fixed the UI issues on iOS, it was caused by difference in implementation of Index across platforms, I came across a logical problem while fixing that which I am addressing at the moment. Regarding performance issues I have removed all anonymous functions can you point out other performance issues I might have missed. Thanks and regards, my changes will be pushed in a few hours. Thanks!

**Comment by matthewbirtch** [comment]
@thegeekybaniya is this ready to re-review from a UI/UX perspective?

**Comment by thegeekybaniya** [comment]
Yes, @matthewbirtch

**Comment by jasonblais** [comment]
@thegeekybaniya Thanks for your contribution! Let us know if you have any questions about the feedback from @matthewbirtch. cc @enahum

**Comment by enahum** [comment]
@thegeekybaniya gentle ping ;)

**Comment by lindy65** [comment]
Hi @thegeekybaniya - as we haven't heard from you in 11 months, I'll be closing this PR and re-adding the "Up for Grabs" label on https://github.com/mattermost/mattermost-server/issues/14605

//cc @enahum @matthewbirtch

**Pull request closed without merging**
