### PR TITLE
Move constants to it own dir

### PR DESCRIPTION
**Pull request by mfpiccolo**
PR is on top of #11 and #10

### CODE REVIEW

**Comment by thomchop** [comment]
What about separating the action type constants into their own file (by store), and importing through an index file?
So our constants directory would look something like this:
```
- analytics.js
- channel.js
- global.js
- oauth.js
- post.js
- team.js
- user.js
- webrtc.js
- websocket.js
```
(files could be suffixed with `_constants` or `_action_types`)

**Comment by coreyhulen** [comment]
@mfpiccolo needs a rebase

**Comment by coreyhulen** [comment]
otherwise feel free to merge.

**Comment by mfpiccolo** [comment]
@thomchop Yeah I like that idea.  I will make that change.

**Comment by mfpiccolo** [comment]
@thomchop @coreyhulen I just pushed up the change to scope the types in their own files that map to actions.  We can change this to a higher level of scoping like you described later on but I think this will work for now.

**Pull request merged**
