### PR TITLE
MM-21605 Remove border to login option buttons

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
image

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-21605

### CODE REVIEW

**Comment by enahum** [comment]
@metanerd @jaydeland ☝️

**Comment by metanerd** [comment]
It was not related to rate limit. Was caused by a recent mattermod change. Thank you for the headsup!

**Comment by enahum** [comment]
@josephbaylon is not missing for me, maybe the wrong build?

image

**Comment by josephbaylon** [comment]
@enahum I tried the ones just generated on Quality Assurance channel. The background color for Office 365 is still shown as white for me on both iOS and Android. I tried several times to clean install but the same results. It's odd that it's the same on both platforms but I'll ask another QA to test

**Comment by enahum** [comment]
@josephbaylon I'll rebuild it

**Pull request merged**
