### PR TITLE
LongPress Home Navigation switches joinedTeams

### PR DESCRIPTION
**Pull request by chief-nerd**
#### Summary

Adds the functionality to long press the bottom navigation home icon and circle through the joined teams 

#### Checklist

- [ ] Added or updated unit tests (required for all new features)
- [ ] Has UI changes
- [ ] Includes text changes and localization file updates
- [x] Have tested against the 5 core themes to ensure consistency between them.

#### Device Information
This PR was tested on: Android

#### Release Note

```release-note
Added functionality to long press home navigation icon to quickly switch teams
```

### CODE REVIEW

**Comment by chief-nerd** [comment]
Any update?

**Comment by asaadmahmood** [comment]
@chief-nerd Apologies, this completely skipped my radar. I know its quite old, but would it be possible to upload a video for this and how it looks right now.

**Comment by chief-nerd** [comment]
> @chief-nerd Apologies, this completely skipped my radar. I know its quite old, but would it be possible to upload a video for this and how it looks right now.

I can bring the branch up-to-date tomorrow and record a video.

**Comment by chief-nerd** [comment]
I spend 4h now trying to launch the app on the branch ... failed miserably on my new Apple M2 to build because ruby (react native dependency) does not support ARM on 2.7.2.

At least I was able to merge `main`. So it 'should' work again ...

So, I fear the path is blocked for me to record a video (or contribute at all 😭)
If anyone wants/can record a video, it would be appreciated. 

## The behaviour would be as following: 
Press Home Icon -> Goes to Home Page. (existing functionality)
[Primary Change: If Home Icon is pressed `LONG` ->](https://github.com/mattermost/mattermost-mobile/pull/7365/files#diff-4d7a76f9ec93e812a5442cc8fc5998e079040c5acb4f3208889da59a586ada04R192)
 [switch to 'next' team in the array. If at the end -> go to first (cycling)](https://github.com/mattermost/mattermost-mobile/pull/7365/files#diff-4d7a76f9ec93e812a5442cc8fc5998e079040c5acb4f3208889da59a586ada04R195)

**Comment by enahum** [comment]
@asaadmahmood ping

**Comment by asaadmahmood** [comment]
@enahum is it possible for someone internally to record a video of this behaviour?

**Comment by enahum** [comment]
@larkox when you have the time, can you please record a video of this PR?

**Comment by larkox** [comment]
@enahum @asaadmahmood Here is the video

https://github.com/mattermost/mattermost-mobile/assets/1933730/299afdb4-71ca-4154-b4d0-0025c75ac3c8

**Comment by asaadmahmood** [comment]
@enahum @chief-nerd I am not sure if this is super clear or expected.
I would have expected the home to close the sidebar to take me to the place I was in the team.

Or at most, to the first team, not toggle between all teams.

cc @matthewbirtch

**Comment by chief-nerd** [comment]
Yea i also get that thinking. 

Since not super clear, close and prio more important things.

**Pull request closed without merging**
