### PR TITLE
Fix propTypes warnings

### PR DESCRIPTION
**Pull request by enahum**
Fixes prop types warnings in dev mode

### CODE REVIEW

**Comment by enahum** [comment]
@josephbaylon I'm fixing some snapshots here.. any reason why would you want to build the PR using the CI? this should only affect dev environment

**Comment by josephbaylon** [comment]
@enahum I'm testing both. I want to make sure the CI build also still works

**Comment by enahum** [comment]
@josephbaylon be my guest, but changes are only around property types, no changes in release mode should be visible..

**Review by josephbaylon — APPROVED** [review]
LGTM. Warnings are removed from areas affected in the dev environment. Also tested the beta build and affected components continue to work.

**Pull request merged**
