### PR TITLE
Fix joining channels from the find channels screen

### PR DESCRIPTION
**Pull request by larkox**
#### Summary
In the Find Channels screen, we have two different sets of channels: those coming from the database (that we have already joined) and those coming from the server (that we haven't joined yet). We make this distinction in the render by sending different `onPress` functions, whether they need to switch or join the channel.

But we were passing both type of channels to the same function that was only trying to switch, not to join also the channel. This PR fixes that issue.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-56349

#### Release Note
```release-note
Fix issue where it was not possible to join a channel from the "Find channels" screen.
```

### CODE REVIEW

**Review by harshilsharma63 — APPROVED** [review]
👌👌👌

**Review by M-ZubairAhmed — APPROVED** [review]

**Review by yasserfaraazkhan — APPROVED** [review]
able to open join channel from find channel option

**Pull request merged**
