### PR TITLE
[GEKIDOU] Bottom Tab Navigation

### PR DESCRIPTION
**Pull request by avinashlng1080**
Implementing new bottom tab navigation for Gekidou

### CODE REVIEW

**Comment by enahum** [comment]
@avinashlng1080 anything in particular that you want me to look at ?

**Comment by avinashlng1080** [comment]
> @avinashlng1080 anything in particular that you want me to look at ?

Hey @enahum  - nothing in particular at the moment.  Just wanted to share this PR so that we can see the progress made.

**Comment by enahum** [comment]
@deanwhillier added you as I included the changes for the default Themes ;)

**Comment by enahum** [comment]
going to merge this.

**Pull request merged**
