### PR TITLE
Upgrade Dependencies

### PR DESCRIPTION
**Pull request by enahum**
it would be nice to include in 1.46 unless there are any concerns

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Comment by amyblais** [comment]
> it would be nice to include in 1.46 unless there are any concerns

It depends on when this is merged, RC testing is scheduled to start tomorrow (unless there is a delay with cutting v5.38 RC1)

**Review by josephbaylon — COMMENTED** [review]
@enahum While smoke testing, I encountered these 2.

1. Upon first install and login, I was presented with this error. This only happened to me once and cannot reproduce even when I clean install the app again.
rn_image_picker_lib_temp_64b7fec3-0abf-43a3-b752-ea0a9530dbf1


2. The `Threads` indicator is showing on main sidebar for this PR whereas it does not for v1.46 build 365 (both connect to community.mattermost.com)

|PR 5578|v1.46 build 365|
|:--|:--|
|rn_image_picker_lib_temp_7dc74b4f-6609-4e25-8e49-3da2204601ba|rn_image_picker_lib_temp_7f07a836-1bd3-4110-802f-adcc18bc2627|

**Comment by enahum** [comment]
@josephbaylon as for the issues you encountered.
> Upon first install and login, I was presented with this error. This only happened to me once and cannot reproduce even when I clean install the app again.

This looks related to CRT or Custom Statuses introduced in 1.46, I would recommend that this things are tested regardless of the dependencies update as is happening on the current 1.46 release branch and master, not sure if this is CRT or Custom Status, there is a similar ticket opened by @jgilliam17 

> The Threads indicator is showing on main sidebar for this PR whereas it does not for v1.46 build 365 (both connect to community.mattermost.com)

Also not related to this PR, see #5574 which fixes this, I did report it on the cherry-picked PR

**Comment by enahum** [comment]
@anurag6713 ☝️

**Comment by enahum** [comment]
This PR should not be blocked as both issues highlighted are currently in the release branch & master.

cc: @amyblais so you can coordinate the fix with the appropriate teams / contributors

**Review by josephbaylon — APPROVED** [review]
LGTM. Issues encountered are known issues. Also spot tested detox e2e, they seem to be running fine with the upgrade.

**Review by anurag6713 — APPROVED** [review]

**Pull request merged**
