### PR TITLE
Added localization into iOS share extension

### PR DESCRIPTION
**Pull request by Partizann**
#### Summary
Added localization into iOS share extension for all existing UI strings, based on reusing strings from i18n/*.json files.
- Updated Fastfile script to generate iOS-specific Localizable.strings files
- Empty Localizable.strings files for each language were added to iOS project under `MattermostShare` target in order to be included to app package
- Replaced strings with `NSLocalizedString` macros in Swift source files
- Reworked usage of DateFormatters with single static instances in Swift, since creation of each Formatter object is pretty consuming operation
- Removed INFOPLIST_KEY_* records from `MattermostShare` target build settings to prevent overriding of Info.plist values
- Added new translation strings to `share_extension/screens/share.tsx`, which are used in iOS share extension only
- Fixed missing argument in `app/utils/file/index.ts`

#### Checklist
- [ ] Added or updated unit tests (required for all new features)
- [ ] Has UI changes
- [x] Includes text changes and localization file updates
- [ ] Have tested against the 5 core themes to ensure consistency between them.

#### Device Information
This PR was tested on: iPhone simulator iOS 16.2, Android emulator Pixel 3a Android 12

#### Release Note
```release-note
Added localization into iOS share extension
```

### CODE REVIEW

**Review by enahum — APPROVED** [review]
LGTM. 🎉

**Review by larkox — APPROVED** [review]
Great work! Thank you for the contribution!

**Comment by larkox** [comment]
@enahum We may have to create a ticket to make sure `i18n-extract` also looks into these strings. Not sure how easy that is going to be. But we can discuss it after this PR is merged.

**Comment by larkox** [comment]
@yasserfaraazkhan Re: testing

The idea here is mainly do some smoke testing around the iOS share extension, so all texts look normal and nothing breaks. It won't translate yet because we don't have the translations, but please try also with the phone / user in a different language to make sure the "default language" (English) is taken correctly and nothing breaks.

**Comment by Partizann** [comment]
Should I upmerge main to get iOS build done successfully?

**Comment by yasserfaraazkhan** [comment]
> Should I upmerge main to get iOS build done successfully?

@Partizann , that would be a great help

**Comment by lindalumitchell** [comment]
I'm having trouble installing the .ipa on my old test iPhone. Have there been any purges from the registered devices for testing? It's been a while since I've tried this....

Perhaps, since v2.5 has just been approved, we could test this one post-merge when the next test build for v2.6 can happen, while we're sorting out test device issues?

**Comment by larkox** [comment]
@lindalumitchell LGTM, but I will leave the final decision to @yasserfaraazkhan

**Comment by enahum** [comment]
> I'm having trouble installing the .ipa on my old test iPhone. Have there been any purges from the registered devices for testing? It's been a while since I've tried this....
> 
> 
> 
> Perhaps, since v2.5 has just been approved, we could test this one post-merge when the next test build for v2.6 can happen, while we're sorting out test device issues?

Reach out to me so that we can figure out the reason you cannot install it

**Review by yasserfaraazkhan — COMMENTED** [review]
thank you for the changes.

@larkox  please suggest this is the part to be tested on mobile.

Screenshot 2023-06-21 at 1 54 34 AM
Screenshot 2023-06-21 at 2 50 48 AM


I've tested with language

**Review by yasserfaraazkhan — APPROVED** [review]

**Comment by larkox** [comment]
@Partizann Do you mind mergin main into this PR? For some reason the test step didn't went through, and a new commit should help to unstuck it.

**Comment by larkox** [comment]
@Partizann Thank you very much for your contribution!

**Pull request merged**
