### PR TITLE
[Weblate] Fix empty/unchanged translation strings in master. Add Bulgarian language. 

### PR DESCRIPTION
**Pull request by metanerd**
#### Summary
Add Bulgarian language. Add general translation updates. Remove translation items for unchanged/empty strings. 

#### Checklist

- [ ] Added or updated unit tests (required for all new features)
- [x] Has UI changes
- [x] Includes text changes and localization file updates

#### Device Information
This PR was tested on:

### CODE REVIEW

**Comment by enahum** [comment]
This one needs a QA review

**Comment by nevyangelova** [comment]
I can't approve this so it's not blocked but some translations are not correct, after discussing with @metanerd we decide to merge them as they are and involve more Bulgarian contributors who might be interested to look into this.

**Review by nevyangelova — APPROVED** [review]

**Review by enahum — APPROVED** [review]

**Comment by lindalumitchell** [comment]
@enahum is there more context around the QA that you mentioned is needed for this one? Looks like BG was added but also many other changes, and not sure whether I'm meant to build the apps on the PR and verify that localisation still appears to be working?

**Comment by enahum** [comment]
@lindalumitchell is to make sure the new language is working properly (regardless of what the strings say hehehhe)

**Review by lindalumitchell — APPROVED** [review]
LGTM on Android 9 & 11, iOS 12 & 13. Spot-checked desktop app as well and no issues found. 

Note: Shockingly, I could not remember any of the three or four Bulgarian words I had learned while spending a few days there last year, so I could not indeed verify the actual translation strings. ;)

**Review by ctlaltdieliet — COMMENTED** [review]
assets/base/i18n/uk.json seems Russian to me

**Pull request merged**
