### PR TITLE
[MM-31257] Bump max allowed file uploads per post

### PR DESCRIPTION
**Pull request by streamer45**
#### Summary

We can finally go ahead with this. Bumping from 5 to 10 the limit of file attachments per post.
Mobile development newbie here so please let me know if there's any issue or concern with the approach.

#### Ticket

https://mattermost.atlassian.net/browse/MM-31257

#### Release Notes

```release-note
Increased the limit of uploaded file attachments per post from 5 to 10.
```
#### Related PRs

https://github.com/mattermost/mattermost-server/pull/17948
https://github.com/mattermost/mattermost-webapp/pull/8419

### CODE REVIEW

**Review by enahum — CHANGES_REQUESTED** [review]
Overall this looks fine, but I'm seeing that there is no changes made to the iOS native Share Extension to account for the change

**Comment by streamer45** [comment]
@enahum 

Mmm interesting, didn't think this needed native code changes. Do we use a similar constant over there as well that needs updating?

**Comment by enahum** [comment]
@streamer45 I believe there is this, possibly related to another server PR that changes the size of what can be shared https://github.com/mattermost/mattermost-mobile/blob/master/ios/MattermostShare/ShareViewController.swift#L123 

and then there is this https://github.com/mattermost/mattermost-mobile/blob/master/ios/MattermostShare/Info.plist#L37 which sets the amount of files that you can share.. now this is going to be very tricky as we would need to bump it there (hardcoded) and in code we should check for the server version to change the limit programmatically and probably show an error message.

**Comment by enahum** [comment]
Btw welcome to the mobile world :P

**Comment by streamer45** [comment]
@enahum 

Had the pleasure of taking a deeper look at this and have a couple of questions:

- What would happen if we only raised the hard-coded values? I am guessing on unsupported servers the post creation would eventually fail, returning an error. Is it imperative that we add an additional version check in the native code as well? Not sure I fully understand how the JS/TS and native (Swift?) parts interact.
- Is there any way for me to build the iOS app on Linux? I am happy to take a stab at this but without a way of testing my changes it would be just brutal.

**Comment by enahum** [comment]
@streamer45 
> What would happen if we only raised the hard-coded values? I am guessing on unsupported servers the post creation would eventually fail, returning an error. Is it imperative that we add an additional version check in the native code as well? Not sure I fully understand how the JS/TS and native (Swift?) parts interact.

Yes it would fail, but this fails silently.. on iOS the share content context happens in the app you are sharing from and once you decide to share the share extension will disappear from screen and do everything it needs to do in the background, so when it fails there is no bubble up of the error message.

> Is there any way for me to build the iOS app on Linux? I am happy to take a stab at this but without a way of testing my changes it would be just brutal.

Unless you are able to use a Virtual Machine to boot MacOS I hardly doubt it.

If this is not urgent I could try and take a stab at it at the beginning of August

**Comment by enahum** [comment]
@streamer45 another thing that could be done, is that we create a follow up ticket to do add the changes to the iOS Share Extension.

**Comment by streamer45** [comment]
Thanks @enahum. There's no urgency from my side really as server changes are ready and it's just about enabling the clients to attach more files which can be done at any later time. I'll make an attempt just for curiosity's sake but otherwise agree this can be left to a separate ticket just focusing on the native changes.

**Comment by streamer45** [comment]
Gave this a good go really but just setting up everything became a huge time sink. Got the VM running OSX but installing the proper Xcode version just became a bit of a nightmare. I'll have to accept that it's just unfeasible to develop native iOS on Linux :/

**Comment by streamer45** [comment]
Created https://mattermost.atlassian.net/browse/MM-37625

**Review by enahum — APPROVED** [review]
I guess the iOS Share extension stays at a limit of 5 as this won't be controlled by the server version but by an app property that the OS reads

**Comment by enahum** [comment]
@streamer45 please resolve the conflicts

**Comment by amyblais** [comment]
@anurag6713 Kind reminder for PR review.

**Review by anurag6713 — APPROVED** [review]
LGTM! 🎉

**Comment by enahum** [comment]
@furqanmlk kind reminder to review this PR

**Comment by furqanmlk** [comment]
Hi @streamer45 

After five attachments, as soon as I click on image button I get following error, did I miss something here?
Since above related `Server` and `WebApp` PRs are already merged, so I am running server on `master` branch.

image

**Comment by enahum** [comment]
furqanmlk The error should only display after 10 files, but it should display inline, what you are seeing is probably cause you need to updste the assets. Try running `npm i` again or with `node scripts/generate-assets.js` regardless the error should only display once you reached the limit, only the server reporting version 6 and up will allow you to select 10 files, if the server reports a version lower than that, then 5 is your limit

**Comment by streamer45** [comment]
I think the issue is that we haven't yet updated the server version to 6.0 on master so it won't result in the updated limit.
@furqanmlk Could you try on top of https://github.com/mattermost/mattermost-server/pull/18247 (server wise).

Also I've updated this PR with a change that I previously missed to fix the displayed error string.

**Review by furqanmlk — APPROVED** [review]
Thanks @streamer45 
Working as expected 👍 

### Before PR

image


### This PR

image

**Pull request merged**
