### PR TITLE
MM-45221 - Gekidou Settings fixes - part 2

### PR DESCRIPTION
**Pull request by avinashlng1080**
#### Summary
This PR completes the setting func within the v2 app.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-45221

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by koox00 — APPROVED** [review]

**Review by anurag6713 — APPROVED** [review]

**Comment by avinashlng1080** [comment]
@matthewbirtch  I know there's lot of catching up on your side.  Please have a look at this PR when you get some time.

**Review by matthewbirtch — CHANGES_REQUESTED** [review]
Hey @avinashlng1080. I spent some time with making adjustments to styles and committed them - I hope that's ok. It was much easier for me to do this rather than describe all the minor discrepancies in written feedback.

A few other things I wasn't able to address:
1. On the 'Mentions' screen, the label 'Keywords' on the text area is not properly left-aligned. It should be inset from the left edge to align with the text within the input.
image

2. For 'Automatic Direct Message Replies', can we shorten this label to 'Automatic Replies'?

**Comment by matthewbirtch** [comment]
@avinashlng1080 I'm not sure sure what I did with that last merge commit. I hope that didn't screw this branch up :(

image

**Comment by avinashlng1080** [comment]
> @avinashlng1080 I'm not sure what I did with that last merge commit. I hope that didn't screw this branch up :(

Thanks @matthewbirtch  - I appreciate it - sorry you went through that trouble.

No worries, I will fix the branch.

**Review by matthewbirtch — APPROVED** [review]
Looking great now @avinashlng1080. 

I'll approve this based on the UI improvements, but can you add a space before `(default)` under `Notify me about…` on the second option (see screenshot)?
image

Also, given the conversation in [this thread](https://community.mattermost.com/core/pl/fsfa9cnxaig778uzfkwrxkokth), we can create a follow-up ticket if we decide to apply settings immediately

**Pull request merged**
