### PR TITLE
Patch react-native-image-picker to allow selecting video

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
This PR includes an additional patch to the Image Picker on Android that should:
1. Resolve the crash
2. Allow selecting images and videos

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-24387

### CODE REVIEW

**Comment by enahum** [comment]
@chuttam would you say that is ok? I did make it so it opens the file manager but you can only select images/videos.

**Comment by enahum** [comment]
I'm going to look if this can be improved before merging

**Comment by saturninoabril** [comment]
@ogi-m will help test on actual Android device.

**Comment by enahum** [comment]
@chuttam you shared
> Yes, the solution works for me. I'm unsure how many Android distros come with no stock file manager, and so I don't know what would happen in that case.
My File Manager allows me to pick Gallery as an app to pick content, and in Gallery, I could still pick only images. I'm 0/5 on changing this for this patch. Something to perhaps consider in an upcoming release for this behaviour to be more Android-natural.

So even though I made some other changes to the patch to clean up code and make it re-usable and all, what we have now and with the previous commit on this PR is following the guide from Android developers portal https://developer.android.com/guide/components/intents-common#GetFile, so I'm 99% confident this is the right solution. the other 1% is based on the fact that I'm not an Android end user.

**Comment by chuttam** [comment]
I'm :+1: on the changes :shipit:

**Comment by ogi-m** [comment]
Both @DHaussermann and I are seeing the app freeze when using the camera.
1. Tap the camera icon icon below the input box and select "Camera"
2. Take a photo and confirm - app freezes and shows a black screen

@enahum [Video](https://drive.google.com/file/d/12xSCSZvNO_nHXtFNO_D80sKRJh5YFK70/view?usp=sharing)

**Comment by enahum** [comment]
@ogi-m great find, I did not test that.. will check

**Comment by enahum** [comment]
@ogi-m fix is ready.. building

**Pull request merged**
