### PR TITLE
MM-24115 Use Native + BuiltIn emojis instead of systemEmojis

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
Check against native + BuiltIn Emojis instead of the previous systemEmojis no longer used in the mobile app.

This PR also downgrades fusejs to the previous version as the newer one is considerably slower (this will conflict #3806 but this version should be used.

Also this fixes an issue where the keyboard remained opened if we closed the `Add Reaction` screen while searching.

Finally it checks if the config for custom emojis is enabled before searching in autocomplete.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-24115

### CODE REVIEW

**Comment by enahum** [comment]
@josephbaylon I'm not seeing what you are seeing, also by looking at the code I can see how it should not go to the server if custom emojis are not enabled https://github.com/mattermost/mattermost-mobile/blob/b171bdb37ed22ae0d32c79d208fe1936071d141c/app/components/emoji_picker/emoji_picker_base.js#L307

**Comment by josephbaylon** [comment]
> @josephbaylon I'm not seeing what you are seeing, also by looking at the code I can see how it should not go to the server if custom emojis are not enabled
> 
> https://github.com/mattermost/mattermost-mobile/blob/b171bdb37ed22ae0d32c79d208fe1936071d141c/app/components/emoji_picker/emoji_picker_base.js#L307

@enahum I retested on both iOS and Android and still the same results. I tested using mysql.test.mattermost.com

Steps,
1. Login to server
2. Go to a channel and post a message
3. Long tap on the message and select from top emojis (or click on + to go to Add Reaction screen and select an emoji)
4. SSH to mysql.test.mattermost.com and tail -f mattermost/logs/mattermost.log

Observed: Although errors are not logged for emoji `:` search, it is logged for get emoji when user selects emoji from Add Reaction or from top emojis

**Comment by enahum** [comment]
@josephbaylon, top emojis?

**Comment by josephbaylon** [comment]
> @josephbaylon, top emojis?

@enahum top used emojis or recent emojis

IMG_0103

**Comment by enahum** [comment]
hmmm.. ok ok. I'll look into that one.. I may have missed something.. thanks @josephbaylon

**Pull request merged**
