### PR TITLE
[MM-11170] Remove loader and someone text from LHS.

### PR DESCRIPTION
**Pull request by sudheerDev**
#### Summary
 removed loader and someone from LHS

#### Ticket Link
(https://mattermost.atlassian.net/browse/MM-11170)

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Has UI changes
- [x] Includes text changes and localization file updates

### CODE REVIEW

**Comment by sudheerDev** [comment]
@enahum You meant separating both archived and user deleted into a different component to reuse?

**Comment by enahum** [comment]
@sudheerDev definitely, this component is getting out of control and the archived and this new state can definitely be their own components, so yes I'm 5/5 on breaking this thing into smaller components

**Comment by sudheerDev** [comment]
Waiting to hear from eric

**Comment by esethna** [comment]
Commented on the webapp PR. I'm not sure why we are making a special case for this in the UI. If the user is permanently deleted via the API then just remove them from the sidebar.

**Comment by sudheerDev** [comment]
@esethna I removed loader and someone from LHS and made a commit to the existing PR

**Pull request merged**
