### PR TITLE
MM-25820 prevent double tap in post options

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
The current implementation of the post options (when you long press a post) can trigger multiple times if you tap on them repeatedly.

With this PR we prevent that from happening by allowing once single tap every half a second, that gives enough time  for the post options to disappear from the view.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-25820

### CODE REVIEW

**Comment by enahum** [comment]
@josephbaylon if you look closely to your video, you are actually tapping on the post in the center channel.

**Comment by josephbaylon** [comment]
> @josephbaylon if you look closely to your video, you are actually tapping on the post in the center channel.

@enahum I'm more concerned about the edit screen with the buttons.

**Comment by enahum** [comment]
@josephbaylon oh I see what you are saying, there are no buttons shown

**Comment by enahum** [comment]
@josephbaylon issue has been addressed... the same was happening with add reaction with the plus sign... do please re-test android as well.

**Comment by josephbaylon** [comment]
@enahum The double tap issues for both iOS and Android look resolved. However, when further testing iOS I noticed that if the edit modal dragged down (instead of hitting `x` or `Save`), when the channel screen is shown again, user is not able to interact anymore. It only happens on edit modal for Edit message and Add reaction. Not sure if this new issue was introduced but when modal for Flagged Posts or Recent Mentions are dragged down, the succeeding screen can still be interacted with.

**Comment by enahum** [comment]
@josephbaylon  I'll take a look and see if they are related

**Comment by enahum** [comment]
@josephbaylon submitted a fix.. after the test finish to run, you can build it again ;)

**Comment by josephbaylon** [comment]
> @josephbaylon submitted a fix.. after the test finish to run, you can build it again ;)

Cool. I have to trigger the build locally because for some reason the artifacts are not being updated properly when rebuilding using `Build Apps for PR`. I'll retest once the new builds are done.

**Pull request merged**
