### PR TITLE
Fixing mention text color

### PR DESCRIPTION
**Pull request by avasconcelos114**
#### Summary
Changes a mention's text color to use `mentionHighlightLink` instead of `linkColor`

This issue becomes most noticeable when the `linkColor` and `mentionHighlightBg` are set to be the same. This is the theme I used when I noticed the bug:

```
{"sidebarBg":"#327c7e","sidebarText":"#ffffff","sidebarUnreadText":"#ffffff","sidebarTextHoverBg":"#001f7e","sidebarTextActiveBorder":"#001f7e","sidebarTextActiveColor":"#ffffff","sidebarHeaderBg":"#001f7e","sidebarHeaderTextColor":"#ffffff","onlineIndicator":"#00ff00","awayIndicator":"#ffff00","dndIndicator":"#f74343","mentionBj":"#00ffff","mentionColor":"#ffffff","centerChannelBg":"#dcdfe2","centerChannelColor":"#000000","newMessageSeparator":"#f80","linkColor":"#0000ff","buttonBg":"#0000ff","buttonColor":"#ffffff","errorTextColor":"#fd5960","mentionHighlightBg":"#0000ff","mentionHighlightLink":"#ff00ff","codeTheme":"github","mentionBg":"#00ffff"}
```

#### Device Information
This PR was tested on:
- iPhone X (simulator)

#### Screenshots
Before fix:
Screen Shot 2019-10-07 at 2 13 41 PM

After fix:
Screen Shot 2019-10-07 at 2 14 03 PM

Same post on the web app for reference:
image

### CODE REVIEW

**Comment by amyblais** [comment]
This is ok for v1.24 if this is a regression and is not risky.

**Comment by jgilliam17** [comment]
@avasconcelos114 
I am using the same theme you posted earlier and noticing that @ all, @ here, @ channel and keyword mentions are also hard to see. See image.
@enahum wondering if it should be addressed here or not. Can you please advise?
Otherwise, @ name mentions look good on iOS app.
IMG_DFD51F3FB205-1

**Comment by enahum** [comment]
yeah I think it should be part of the same PR

**Comment by avasconcelos114** [comment]
Great catch! I should have thought to test other highlights too :)

Those should be rendering in a consistent way now
image

**Comment by jgilliam17** [comment]
Note:
Part of this PR has been reverted by https://github.com/mattermost/mattermost-mobile/pull/3472
Issue is tracked under [MM-19834](https://mattermost.atlassian.net/browse/MM-19834)

**Pull request merged**
