### PR TITLE
MM-23395: Add websockets support for update group

### PR DESCRIPTION
**Pull request by catalintomai**
#### Summary
Ensuring that when we delete or update a MM group, the websocket event is triggered and we are updating the referenceable groups (et al) in Redux for group-mentions + fixed bug that was updating the groups state with incomplete group metadata(only the id) when mapping a team/channel to a group.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-23395 
Note: this addresses items(events) 1-4 of the ticket - see ticket comments

#### Checklist
- [x ] Added or updated unit tests (required for all new features)
- [ ] Has UI changes
- [ ] Includes text changes and localization file updates

#### Device Information
This PR was tested on: IoS emulator (IPhone 11 Pro Max)

Note: will get back to this after finishing up some other work.

### CODE REVIEW

**Comment by enahum** [comment]
@catalintomai, is this PR only for websockets? Is there going to be more work needed to fetch/sync using a rest API?

**Comment by enahum** [comment]
What about in WebSocket reconnection?

**Comment by enahum** [comment]
is this still a WIP ?

**Comment by catalintomai** [comment]
> is this still a WIP ?

In short, yes.

**Comment by enahum** [comment]
@hahmadia do you know what's up with this? should we close it ?

**Comment by hahmadia** [comment]
@enahum 
We have made a ticket to track what Catalin was originally trying to solve so it be addresssed at a later time and closing this PR in the meantime.

**Pull request closed without merging**
