### PR TITLE
Fix: Use soloader 0.8.0 to fix Android App Bundle & Hermes compatibility.

### PR DESCRIPTION
**Pull request by raghavyadavm**
This PR fixes crash on some Android device when Hermes is enabled https://github.com/facebook/react-native/pull/26759

### CODE REVIEW

**Comment by raghavyadavm** [comment]
The build failed because the library for adding patch fixes to the library doesn't support multiple patches per package https://github.com/ds300/patch-package/issues/43

**Comment by smacgregor** [comment]
I believe the soloader version bump is only needed for projects using both Hermes and Android app bundles.  It looks like Android is always building to an APK:

https://github.com/mattermost/mattermost-mobile/blob/master/fastlane/Fastfile#L546?

Double checking this patch to react native is needed in order to enable Hermes.

**Comment by enahum** [comment]
@raghavyadavm not sure I follow why you say it does not support multi-patches. But in any case we do not build the `ReactAndroid` target as we use the one provided by RN. And it seems that it was reverted on 0.61.4 https://github.com/facebook/react-native/commit/1b39f67896e4724358c7e817c69b5d942eaad058

**Comment by enahum** [comment]
@raghavyadavm do you think this PR is still valid and if so why?

**Comment by raghavyadavm** [comment]
@enahum  SoLoader library below version 0.8.0  had a problem where it loads a 64-bit library instead of the 32-bit library on some devices. This fix was not released in the latest 0.61.x versions because it breaks the Android tests. https://github.com/react-native-community/releases/issues/148#issuecomment-541314874 I am going to close this PR because the build is not successful.

**Pull request closed without merging**
