### PR TITLE
MM-36745 Fix animation for showModalOverCurrentContext

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
There is a bug in RNN so we need to handle the animation options a bit differently

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-36745

#### Release Note
```release-note
Fixed an animation transition when displaying the options menu on iOS
```

### CODE REVIEW

**Review by anurag6713 — APPROVED** [review]

**Review by avinashlng1080 — APPROVED** [review]
LGTM

**Review by josephbaylon — APPROVED** [review]
LGTM. Long press menu dark overlay now fades in instead of slides up.

**Comment by enahum** [comment]
@amyblais was the release branch created after this PR got merged?

**Pull request merged**
