### PR TITLE
MM-35674 Detox/E2E: Add e2e for autocomplete and at-mention

### PR DESCRIPTION
**Pull request by josephbaylon**
#### Summary
- Added tests for MM-T168, MM-T169, MM-T170, MM-T171, MM-T172, MM-T1798, MM-T2349 in
    - `detox/e2e/test/autocomplete/autocomplete.e2e.js`
    - `detox/e2e/test/messaging/at_mention.e2e.js`
- Fixed duplicate name issue
- Added new testIDs, added new helper functions modified `generateRandomUser` to have shorter values, modified `getAtMentionItem` to return child elements and updated affected tests

Note: @anurag6713 I added you in this PR because I had to remove the dupe name in the autocomplete. Not sure if you're already fixing it on another PR but just making you aware that I'm removing the dupe to make the tests pass.

#### Ticket Link
JIRA tickets:
- https://mattermost.atlassian.net/browse/MM-35674

Zephyr cases:
- [MM-T168](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T168)
- [MM-T169](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T169)
- [MM-T170](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T170)
- [MM-T171](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T171)
- [MM-T172](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T172)
- [MM-T1798](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T1798)
- [MM-T2349](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin%3Acom.kanoah.test-manager__main-project-page#!/testCase/MM-T2349)

#### Screenshots
Screen Shot 2021-05-25 at 3 21 24 PM
Screen Shot 2021-05-25 at 2 56 35 PM

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by anurag6713 — APPROVED** [review]
Thanks @josephbaylon 👍

**Review by saturninoabril — APPROVED** [review]
Thanks, LGTM! Tested and passed.

**Comment by amyblais** [comment]
Joseph mentioned that this PR fixes https://mattermost.atlassian.net/browse/MM-36110, so this can be cherry-picked to v1.44. @anurag6713 @enahum

**Comment by enahum** [comment]
@josephbaylon please do a manual cherry-pick for this PR

**Pull request merged**
