### PR TITLE
[MM-24891] [MM-24572] Add ability to specify default value when role not found for selector

### PR DESCRIPTION
**Pull request by fmunshi**
#### Summary
- Currently if the roles for a channel or team are not loaded into the state then any permission check that requires those roles returns false, so setting any kind of default beforehand is pointless since it just gets overridden to be false by the permission check

- This PR adds an optional attribute to the `PermissionsOptions` parameter passed in to all permission checks to specify a default in the case where the roles for the specified resource (team or channel) do not exist.

- Not sure what the best way to test this is but, I just modified the code to think there were no roles in the state and then ensured that the default values are honoured.

#### Ticket Link
- https://mattermost.atlassian.net/browse/MM-24891
- https://mattermost.atlassian.net/browse/MM-24572

#### Checklist
- [x] Added or updated unit tests (required for all new features)
~Has UI changes~
~Includes text changes and localization file updates~

#### Device Information
This PR was tested on:
- iPhone 11 Simulator

### CODE REVIEW

**Comment by enahum** [comment]
Also this PR is not adding a default value for other permissions checks.

**Comment by fmunshi** [comment]
@enahum to answer your questions - the reason for why I have done those things is all related to how we have some pseudo inheritance on role permissions.

For example, there could be a `test_permission` that can be added both to the `channel_user` and `team_admin` role, in that case if we run `haveIChannelPermission(test_permission)` it is required to first check the channel roles and then also the team roles.

There could be a case where the `test_permission` only exists on the `team_admin` role for the current user but the `channel_user` role is not loaded into the state. In that case we would want to return true and not just the default hence why I am doing `return options.default === true || hasPermission;` since the default could potentially be set to false and then this would return false despite the user actually having the permission.

For the same example where the `test_permission` only exists on the `team_admin` role if the `channel` roles are all loaded but the team role is not loaded the permission check would return false if we didnt flag that the team role is not found. 

So even for `haveIChannelPermission` we want to `return default || permission` if the a team role is not found cause there is potential for that specific permission to exist only on a team role.

**Comment by fmunshi** [comment]
Also I did not update _all_ permission checks since it seems we're only running into these issues with channel permissions.
So I have set all the channel moderated permissions (create_post, add_reaction... etc) to be true while leaving channel management permissions to default false if not found since i'm not sure if we want those to default true...

**Comment by josephbaylon** [comment]
@enahum @migbot I'm not sure how to test this PR. Can you please provide some steps to verify the fix?

**Comment by enahum** [comment]
@fmubshi any guidance? I don’t know how to make the roles fail

**Comment by josephbaylon** [comment]
> @fmubshi any guidance? I don’t know how to make the roles fail

cc @fmunshi

**Comment by fmunshi** [comment]
@josephbaylon 

Im not sure how to reproduce it either - I only saw it once on my mobile app and then switching teams fixed it.
I think you could try logging in and out a few times and switching teams a few times and then just running the usual smoke tests?

**Pull request merged**
