### PR TITLE
MM-20326 - Updating markdown table css

### PR DESCRIPTION
**Pull request by asaadmahmood**
#### Summary
MM-20326 - Updating markdown table css

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-20326

#### Checklist

- [x] Has UI changes

#### Device Information
This PR was tested on: Nexus 6P API 25

#### Screenshots
Screenshot 2019-11-26 at 7 53 55 PM

### CODE REVIEW

**Comment by esethna** [comment]
Thanks Asaad! Please see the design doc for the expected placement: https://projects.invisionapp.com/share/Q6S9HX5R5TJ#/screens/366050486

**Comment by asaadmahmood** [comment]
Done @esethna. Please review.
Screenshot 2019-11-27 at 4 13 12 PM

**Comment by enahum** [comment]
Hmmm can you share a screenshot on landscape?

**Comment by asaadmahmood** [comment]
@enahum Here you go.
Screenshot 2019-11-27 at 4 20 00 PM
Screenshot 2019-11-27 at 4 19 55 PM

**Comment by enahum** [comment]
Thanks LGTM and my previous review stands

**Comment by saturninoabril** [comment]
@asaadmahmood Looks good on Android but not on iPhone 11. There are two visible circles
Screen Shot 2019-11-28 at 2 06 14 AM

**Comment by asaadmahmood** [comment]
@saturninoabril Thanks, will have a look.

**Comment by asaadmahmood** [comment]
Done @saturninoabril 
Screenshot 2019-11-27 at 11 53 28 PM
Screenshot 2019-11-27 at 11 52 52 PM

**Pull request merged**
