### PR TITLE
1.45 Release testing bug fixes

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
This PR addresses the bugs found during release testing

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-36908
https://mattermost.atlassian.net/browse/MM-36935
https://mattermost.atlassian.net/browse/MM-36929
https://mattermost.atlassian.net/browse/MM-36928
https://mattermost.atlassian.net/browse/MM-36920
https://mattermost.atlassian.net/browse/MM-36922

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by Willyfrog — APPROVED** [review]
Looks good. I can't test right now, but does this work as well with the Mattermost logo emoji?

**Comment by enahum** [comment]
@Willyfrog the mattermost logo emoji will display as a `:shortcode:` as well as any other custom emoji, only those emoji's with unicode will display with the image in the text field.

**Review by josephbaylon — COMMENTED** [review]
@enahum Verified most of the issues were fixed from the tickets. One thing I noticed on Android is tapping on `Send me a test notification` doesn't crash anymore but it doesn't send a test notification either (option just disables briefly then becomes enabled again). Not sure if this is intended. Lmk

**Comment by enahum** [comment]
@josephbaylon do check the botification drawer is there but low priority my friend

**Comment by josephbaylon** [comment]
@enahum I see. It's indeed in the notification drawer. But once I tap on it, I get a crash. Here's the snapshot:

rn_image_picker_lib_temp_a12b1785-b1de-42d1-a036-3229b0af499e

**Comment by enahum** [comment]
@josephbaylon cool I'll check the crash

**Comment by enahum** [comment]
@josephbaylon fixed

**Review by josephbaylon — APPROVED** [review]
LGTM. Verified original bugs are fixed. Also verified test notification crash is fixed.

**Review by anurag6713 — APPROVED** [review]
🎉 Thanks Elias.

**Comment by amyblais** [comment]
@mickmister Please help prioritize review for today if you can.

**Comment by enahum** [comment]
going to merge this

**Pull request merged**
