### PR TITLE
MM-11232 Fix table column width to better support wide tables 

### PR DESCRIPTION
**Pull request by hmhealey**
This makes it so that the columns in Markdown tables are a fixed width instead of fitting all columns into the available space so that tables with more columns be readable. A few things to note with this:
1. I'm unable to make the tables scroll horizontally in the post view as requested, but you can scroll horizontally once tapping on the table for the full view
2. When viewing the whole table, Android does not support diagonal scrolling so you can only scroll horizontally and then vertically. 
3. I've increased the max height of tables in the post list from 120 to 300 points

As part of this ticket, I've also made a small change to commonmark-react-renderer to make it so that the MarkdownTable component knows the number of rows and columns to be rendered. Those changes are here: https://github.com/mattermost/commonmark-react-renderer/commit/3a2ac19cab725ad28b170fdc1d397dddedcf87eb

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-11232

#### Checklist
- Has UI changes

#### Device Information
This PR was tested on: iOS Simulator (iPhone X, iOS 12.1), Nexus 5 (Android 6.0)

#### Screenshots
New behaviour:
screen shot 2018-12-13 at 6 15 07 pm

Old behaviour:
screen shot 2018-12-13 at 6 16 29 pm

### CODE REVIEW

**Comment by hmhealey** [comment]
@esethna Adding you for review to ensure that the fixed column width and the max height changes look good

**Comment by enahum** [comment]
@hmhealey code looks good, but should we add some tests to this PR?

**Comment by hmhealey** [comment]
The only ones I can think to add is to make sure that it renders the `moreRight` and `moreBelow` when triggered by the state, but I don't know how useful those are. Most of the logic that I'd want to test here would need to be tested manually like checking whether or not RN gives the table the correct dimensions from `onLayout`.

**Comment by hanzei** [comment]
What is the status on the PR? Is the review from @esethna the last missing one?

**Pull request merged**
