### PR TITLE
MM-16398 Fix Team/Channel sidebar dots overlap last item

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
This PR fixes the overlap of the dots and the last item is the team/channel sidebar (LHS)

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-16398

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Added or updated unit tests (required for all new features)
- [ ] All new/modified APIs include changes to [mattermost-redux](https://github.com/mattermost/mattermost-redux) (please link)
- [x] Has UI changes

#### Device Information
This PR was tested on: Android and iOS w/wo safeAreaInsets

#### Screenshots
Screenshot_1563228207

Screenshot_1563228213

Screenshot_1563228222

Screenshot_1563228228

Simulator Screen Shot - iPhone Xs - 2019-07-15 at 18 04 17

Simulator Screen Shot - iPhone Xs - 2019-07-15 at 18 04 22

Simulator Screen Shot - iPhone Xs - 2019-07-15 at 18 04 31

Simulator Screen Shot - iPhone Xs - 2019-07-15 at 18 04 36

### CODE REVIEW

**Comment by asaadmahmood** [comment]
@enahum The dots are too close to the bottom on the initial designs which do not have the black navigation bar at the bottom.
Screenshot 2019-07-16 at 9 49 07 PM

We'd probably want similar spacing as this one from the bottom, this still needs a bit more spacing at the top, maybe 5-10 pixels so the top and bottom spacing are equal.
Screenshot 2019-07-16 at 9 50 56 PM

**Comment by asaadmahmood** [comment]
Allso slightly separate, but the Teams header is not centered, it's slightly to the left.
That's probably because both the side are unbalanced, as there is an icon on the right, but not on the left.
Screenshot 2019-07-16 at 9 51 31 PM

**Comment by enahum** [comment]
@asaadmahmood 
> We'd probably want similar spacing as this one from the bottom, this still needs a bit more spacing at the top, maybe 5-10 pixels so the top and bottom spacing are equal.

the ticket specifies different spacing between top and bottom.

> Allso slightly separate, but the Teams header is not centered, it's slightly to the left.
That's probably because both the side are unbalanced, as there is an icon on the right, but not on the left.
Not part of this ticket, feel free to file a new one ;)

> The dots are too close to the bottom on the initial designs which do not have the black navigation bar at the bottom.
This is bottom: 0, the difference between the iOS one is that the SafeAreaInsets actually add a marginTop of 34pt on portrait and 14pt on landscape but the actual dots are positioned at bottom: 0. If we need to handle them differently when no SafeAreaInsets are present in the device then I'll need to know the margin that needs to be left at the bottom.

**Comment by asaadmahmood** [comment]
Cool, I'll ask Andrew to look at the spacings then and review this instead.

**Comment by enahum** [comment]
@andrewbrown00  Here are the new screenshots based on the feedback

Android phones
Screenshot_1563373522

Screenshot_1563373529

Android Tablets
Screenshot_1563374316

Screenshot_1563374324

iPhone no Safe Area
Simulator Screen Shot - iPhone 6s - 2019-07-17 at 10 14 03

Simulator Screen Shot - iPhone 6s - 2019-07-17 at 10 14 10

iPhone with Safe Area
Simulator Screen Shot - iPhone Xs - 2019-07-17 at 10 09 08

Simulator Screen Shot - iPhone Xs - 2019-07-17 at 10 09 18

iPad no Safe Area
Simulator Screen Shot - iPad (6th generation) - 2019-07-17 at 10 15 12

Simulator Screen Shot - iPad (6th generation) - 2019-07-17 at 10 15 20

iPad with Safe Area
Simulator Screen Shot - iPad Pro (11-inch) - 2019-07-17 at 10 23 50

Simulator Screen Shot - iPad Pro (11-inch) - 2019-07-17 at 10 23 55

**Comment by andrewbrown00** [comment]
@enahum the spacing looks good, thanks for posting. 

**Question**
The dots look off centered in the LHS. Did something change in the way the dots are centered? I know I made a comment for consideration in the jira ticket but it mentioned: 

> Can this be implemented to detect the home bar and center the dots and if the home bar is not present (older and non-iPhones) can we leave the dots centered in the LHS.

**Comment by enahum** [comment]
@andrewbrown00 on iPhones with the SafeArea it should be center in the whole screen, those without safe area it should be centered on the LHS and I think there is an issue there, that I will fix quickly but won't be taking screenshots if that's ok

**Comment by enahum** [comment]
Code updated

**Comment by andrewbrown00** [comment]
@enahum makes sense and that should resolve what I am seeing, thanks man!

**Comment by enahum** [comment]
@andrewbrown00 changes made my friend, feel free to approve if the spacing looks good

**Pull request merged**
