### PR TITLE
Detox/E2E: Server List e2e tests in Gekidou

### PR DESCRIPTION
**Pull request by josephbaylon**
#### Summary
- Added e2e for server list
- Created associated zephyr test cases under `Mobile V2` folder

Mobile V2/Smoke Test: Added step for adding new server
[MM-T4675](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/testCase/MM-T4675)

Mobile V2/Server Login: Added several steps for Server List e2e
[MM-T4691](https://mattermost.atlassian.net/projects/MM?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/testCase/MM-T4691)

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-42406

#### Screenshots
Screen Shot 2022-03-21 at 1 01 44 PM
Screen Shot 2022-03-23 at 9 55 25 AM

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by saturninoabril — APPROVED** [review]
Thanks @josephbaylon! Tested and passed. LGTM.

**Comment by enahum** [comment]
Thanks @josephbaylon but I would add a test that it does not allow you to connect to a server that is already logged in and another were you try and use the same display name of an already existing server with an active session

**Comment by josephbaylon** [comment]
> Thanks @josephbaylon but I would add a test that it does not allow you to connect to a server that is already logged in and another were you try and use the same display name of an already existing server with an active session

@enahum The first one I'll add but the second is already part of MM-T4691_3

**Comment by josephbaylon** [comment]
> Thanks @josephbaylon but I would add a test that it does not allow you to connect to a server that is already logged in and another were you try and use the same display name of an already existing server with an active session

Ok I'll add both

**Comment by josephbaylon** [comment]
@enahum I've added `MM-T4691_6` to cover both cases (and corresponding zephyr entry). Please check

**Review by enahum — APPROVED** [review]

**Pull request merged**
