### PR TITLE
PLT-5857 replace the service folder with mattermost-redux library

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
This PR gets rid of the `service` folder and replaces it with [mattermost-redux](https://github.com/mattermost/mattermost-redux) library in order to use the library as a base for any Mattermost client app like this project and the webapp

#### Ticket Link
https://mattermost.atlassian.net/browse/PLT-5857

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Added or updated unit tests (required for all new features)

#### Device Information
This PR was tested on: [iPhone 6s IOS 10.2.1, Samsung J5 Android 6.0.1]

### CODE REVIEW

**Comment by hmhealey** [comment]
Also, it doesn't affect the PR at all, but why did you choose to keep the internationalization code in the app itself? It's the same library that's used for the webapp so it could be shared between the two

**Comment by enahum** [comment]
Cause it depends on the assets, the config and ultimately I dont want to change the process for translations

**Comment by enahum** [comment]
and now it has conflicts!! @jarredwitt @hmhealey that was a fast review, did you had chance to test it?

**Comment by jarredwitt** [comment]
Working well as far as I can tell

**Pull request merged**
