### PR TITLE
MM-37134 Properly group Android push notifications by channel

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
Groups the Android push notifications by channel

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-37134

#### Release Note
```release-note
Fixed Android push notifications so that they are grouped by channel.
```

### CODE REVIEW

**Review by josephbaylon — APPROVED** [review]
LGTM. Android push notifications are now being grouped by channel.

**Comment by svelle** [comment]
tested and working. takes a few seconds for the messages to group but they are being grouped eventually

**Comment by amyblais** [comment]
@jespino This is being planned for a dot release.

**Comment by amyblais** [comment]
@enahum Feel free to add another dev reviewer to expedite getting this reviewed.

**Review by hmhealey — APPROVED** [review]

**Pull request merged**
