### PR TITLE
Allow user to install mattermost on sd card

### PR DESCRIPTION
**Pull request by MParvin**
Please make sure you've read the [pull request](https://developers.mattermost.com/contribute/getting-started/contribution-checklist/) section of our [code contribution guidelines](https://developers.mattermost.com/contribute/getting-started/).

When filling in a section please remove the help text and the above text.

#### Summary
Cannot install Mattermost when there is no enough space in internal memory, So when add this line
android:installLocation="auto" 
to the manifest file user can install Mattermost on the sd card.
https://developer.android.com/guide/topics/data/install-location

#### Ticket Link
None

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Added or updated unit tests (required for all new features)
- [ ] All new/modified APIs include changes to [mattermost-redux](https://github.com/mattermost/mattermost-redux) (please link)
- [ ] Has UI changes
- [ ] Includes text changes and localization file updates

#### Device Information
This PR was tested on: LG K8 - Android 6.0

### CODE REVIEW

**Comment by MParvin** [comment]
I filled the cla/mattermost form, please check again.
https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true

**Comment by enahum** [comment]
@MParvin Thanks for the contribution, we are currently discussing the security implications this PR may have.

**Comment by hmhealey** [comment]
I've done some reading up on this, and the only the APK itself gets stored on the SD card, so we don't need to worry about private data being readable.

The only potential problem that I can see with doing this is that the app will be killed if the user enables USB mass storage to read files from their computer, but I don't think that's an issue for us. The Android docs have some recommendations for [apps that shouldn't be installed on external storage](https://developer.android.com/guide/topics/data/install-location.html#ShouldNot), but we don't fall under any of those categories.

I also checked a bunch of other apps to see what they do, and most of them don't bother setting this value except for Facebook which also sets the value to `auto`.

Thoughts, @enahum? I'm good with changing this.

**Pull request merged**
