### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Weblate](https://translate.mattermost.com/projects/mattermost/mattermost-mobile_release-1-33/) for mattermost/mattermost-mobile_release-1.33.

### CODE REVIEW

**Comment by enahum** [comment]
@metanerd should we merge this one too ?

**Comment by metanerd** [comment]
@enahum Would be totally for it.

**Comment by enahum** [comment]
@metanerd ok we can merge... 

question: Have we defined the process on what gets merged to master and what gets to the release branches?

**Comment by metanerd** [comment]
@enahum I will use the auto translate tool to translate to the release branch. That's the process for now.

**Comment by enahum** [comment]
@metanerd Ok so let me see if I get this right:
1. Translations are for the master branch
2. Submit a PR to master with the translations
3. Use the auto translate tool to pick the translations that are required for the release branch
4. Submit a second PR to the release branch

yes ?

**Comment by metanerd** [comment]
@enahum Yes! You perfectly described the flow. This is how it is intended.

**Comment by enahum** [comment]
@metanerd thanks

**Pull request merged**
