### PR TITLE
Revert "Channel Bookmarks (#7750)"

### PR DESCRIPTION
**Pull request by enahum**
This reverts commit 2c5c878829f8877d3f5bf8a11685bc55084b2e26.

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by calebroseland — APPROVED** [review]

**Review by jupenur — COMMENTED** [review]
The line counts of the revert and the original PR don't match up and it looks like the culprit is `ios/Mattermost/Info.plist`. What happened there?

**Comment by enahum** [comment]
@jupenur I just pushed a commit to include Info.plist from the main branch which is the expected one

**Review by jupenur — APPROVED** [review]
I'll take your word for it :)

**Comment by enahum** [comment]
> I'll take your word for it :)

sounds good, but just FYI, basically this revert had a dupe of a property called `NSAllowsArbitraryLoads` and the main branch only has one.

**Pull request merged**
