### PR TITLE
[Gekidou MM-46342] Search screen - handle loading spinner in results screen

### PR DESCRIPTION
**Pull request by jfrerich**
#### Summary
This PR changes the loading spinner behavior when results are being fetched.

When the user is in the results screen, don't show the loading spinner over the entire screen. Instead, show the loading in the results under the results header.

This change will reduce the "flickering" of the header when in the results are showing. 

#### When the user is in the `Initial Screen` (modifiers/recents) and performs a search:
Show the loading spinner over the entire screen (under the nav search) until results are available.
After results are available, show the header and results.

#### When the user is in the `Results Screen`:
Show the loading spinner in the screen under the `Results Header` when the user performs any of the following:
  1) file filter change
  2) team picker change
  3) new search in the nav search

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-46342

#### Checklist

- [ ] Added or updated unit tests (required for all new features)
- [ ] Has UI changes
- [ ] Includes text changes and localization file updates
- [ ] Have tested against the 5 core themes to ensure consistency between them.

#### Device Information
This PR was tested on: 

#### Release Note

```release-note

```

### CODE REVIEW

**Review by matthewbirtch — CHANGES_REQUESTED** [review]
Hey @jfrerich a few things I'm seeing:

1. Switching between the `Messages` and `Files` tab seems to be quite delayed. I tested the search 'Test' on community and then switched tabs and found a significant delay in actually switching the tabs
2. When searching from the initial screen, the loading spinner isn't properly centered vertically.
image

3. I do not see a loader when I change the file filters. It should clear the results and show the loader while it applies/fetches the results, right?

4. Can we change the position, size and outline of the badge that sits on the filter icon? It should 8x8, but it looks like you've got it as 12x12. Also, there should be a 2pt border on the outside of the circle shape that is `centerChannelBg` theme color. Notice the difference in position in the screenshot below as well.

image

**Comment by jfrerich** [comment]
@matthewbirtch, can you verify the following items are fixed?

> 2. When searching from the initial screen, the loading spinner isn't properly centered vertically.
> 
> 3. I do not see a loader when I change the file filters. It should clear the results and show the loader while it applies/fetches the results, right?
> 4. Can we change the position, size and outline of the badge that sits on the filter icon? It should 8x8, but it looks like you've got it as 12x12. Also, there should be a 2pt border on the outside of the circle shape that is `centerChannelBg` theme color. Notice the difference in position in the screenshot below as well.

I'll investigate the delays you are seeing `Messages` and `Files` tabs next.

**Comment by matthewbirtch** [comment]
> @matthewbirtch, can you verify the following items are fixed?
> 
> > 2. When searching from the initial screen, the loading spinner isn't properly centered vertically.
> > 3. I do not see a loader when I change the file filters. It should clear the results and show the loader while it applies/fetches the results, right?
> > 4. Can we change the position, size and outline of the badge that sits on the filter icon? It should 8x8, but it looks like you've got it as 12x12. Also, there should be a 2pt border on the outside of the circle shape that is `centerChannelBg` theme color. Notice the difference in position in the screenshot below as well.
> 
> I'll investigate the delays you are seeing `Messages` and `Files` tabs next.

Yep @jfrerich these are fixed

**Comment by jfrerich** [comment]
@matthewbirtch, ticket created to address the following: https://mattermost.atlassian.net/browse/MM-46370
> 1. Switching between the Messages and Files tab seems to be quite delayed. I tested the search 'Test' on community and then switched tabs and found a significant delay in actually switching the tabs

**Review by matthewbirtch — APPROVED** [review]

**Review by avinashlng1080 — APPROVED** [review]

**Review by enahum — APPROVED** [review]

**Pull request merged**
