### PR TITLE
[MM-29225] Linking fix

### PR DESCRIPTION
**Pull request by migbot**
#### Summary
`Linking.canOpenURL` is not working correctly on iOS 14 when Safari is not set as the default browser (might be an [iOS 14 bug](https://developer.apple.com/forums/thread/660241)). With this change we attempt to open the URL and handle an error if one occurs.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-29225

#### Checklist
- [x] Includes text changes and localization file updates

#### Device Information
This PR was tested on:
* iPhone SE, iOS 14

### CODE REVIEW

**Review by enahum — APPROVED** [review]

**Review by josephbaylon — COMMENTED** [review]
@migbot I'm not able to repro the original issue. I tested on iPhone X (iOS 14). I have Safari and Chrome installed. However, I'm not able to make Chrome my default browser. The option `Default Browser App` is not available so that I can set it (see image).

IMG_0288

I did verify, though, that links (valid/invalid) try to open in Safari or default mail client when user tries to load urls from the different scenarios indicated in the code changes.

Not sure if it's related but for invalid permalink scenario, I'm getting the following issue (happens on this PR and on build 328). Changed original valid permalink from
```
https://community.mattermost.com/core/pl/ggdp3xh5qtgffn1p9o61ngs39o
```
to invalid link,
```
https://community.mattermost.com/c/pl/ggdp3xh5qtgffn1p9o61ngs39o
```

IMG_0291

**Review by josephbaylon — COMMENTED** [review]
@migbot I'm finally able to see the `Default Browser App` option when I upgraded my iOS from 14.0 to 14.0.1

For build 328,
- valid links open in chrome
- invalid links display alert
```
Link Error
The link could not be found on this server
```

For this PR,
- valid links open in Chrome
- invalid links attempt to open in Chrome (no alerts)

Also the permalink issue I mentioned [here](https://github.com/mattermost/mattermost-mobile/pull/4860#pullrequestreview-501215383) still exists.

Let me know if the behavior above is correct and if the permalink issue is unrelated and I can approve this PR

**Comment by josephbaylon** [comment]
> @josephbaylon Thanks for the thorough testing! Can you check if the permalink issue you found occurs on build 328?

@migbot Yes it does

**Comment by josephbaylon** [comment]
> OK could you please open a separate ticket for that?

@migbot https://mattermost.atlassian.net/browse/MM-29252

So the rest of the behavior I indicated [here](https://github.com/mattermost/mattermost-mobile/pull/4860#pullrequestreview-501254509) are correct?

**Comment by josephbaylon** [comment]
@migbot I tried but on either build 328 or this PR, the link is not tappable when protocol is invalid
IMG_0292

**Review by josephbaylon — APPROVED** [review]
LGTM. The prompt appears when link contains invalid protocol

Tested on iPhone X (14.0.1) and Pixel 3 XL (11) devices

Ticket for tests: https://mattermost.atlassian.net/browse/MM-29254

**Pull request merged**
