### PR TITLE
Updated `Jump to` to match webapp

### PR DESCRIPTION
**Pull request by cwarnermm**
#### Summary
Updated "Jump to..." to match webapp equivalent UI string.

#### Ticket Link
Working from a Boards ticket.

#### Checklist
- [ ] Added or updated unit tests (required for all new features)
- [x] Has UI changes
- [x] Includes text changes and localization file updates
- [ ] Have tested against the 5 core themes to ensure consistency between them.

#### Device Information
This PR has not yet been tested on iOS or Android.

#### Release Note
```release-note
Updated "Jump to..." to match webapp equivalent UI string.
```

### CODE REVIEW

**Review by josephbaylon — COMMENTED** [review]
Looks good on iOS. However, Android currently has an issue and is being addressed here https://github.com/mattermost/mattermost-mobile/pull/5801

This PR-5797 needs to be rebased from master after PR-5801 is merged.

**Comment by josephbaylon** [comment]
@amyblais Wondering if this will part of v1.48. Just needed to know the timing of when to update affected zephyr cases and rainforest tests.

**Comment by amyblais** [comment]
> @amyblais Wondering if this will part of v1.48. Just needed to know the timing of when to update affected zephyr cases and rainforest tests.

I've added it to the v1.48 milestone and if it gets merged tomorrow before a build is cut, we can include it in v1.48.

**Pull request merged**
