### PR TITLE
[Gekidou] - Custom navigation header

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
This PR adds a custom navigation header to Gekidou.

The header has the ability to:
* Display as Large title
* include a subtitle
* Respond to scrolling events
* display title on normal size
* show a back button
* display one custom component on the left side
* display multiple icons on the right of the title
* Have an integrated search bar

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-39872
https://mattermost.atlassian.net/browse/MM-39755

#### Checklist
- [x] Has UI changes
- [x] Includes text changes and localization file updates
- [x] Have tested against the 5 core themes to ensure consistency between them.

#### Device Information
This PR was tested on: 
* Android 12 Pixel 4
* iPhone X iOS 15.1
* iPhone 12 iOS 15.1
* iPad 11 Pro iOS 15.1

#### Screenshots
image

image

image

image

image

image

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by enahum** [comment]
@Rina-dsg FYI, you won't be able to see all variations of the header as they are in the screenshots by running the app

**Comment by Rina-dsg** [comment]
@enahum 

- This padding seems a bit smaller than in design. It should be 20 pt

Screenshot 2021-11-09 at 20 44 39

**Comment by Rina-dsg** [comment]
Can we pls make subtitle with 80% opacity here?
Screenshot 2021-11-09 at 20 56 53

**Comment by enahum** [comment]
> Can we pls make subtitle with 80% opacity here?
> 
>

@Rina-dsg sure, anything else?

**Comment by enahum** [comment]
@Rina-dsg done

image

**Review by koox00 — APPROVED** [review]
Awesome 💯

**Pull request merged**
