### PR TITLE
V1 dependencies and bump to RN 0.67.2

### PR DESCRIPTION
**Pull request by enahum**
Fixes: #5757

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by josephbaylon** [comment]
@enahum Initial observations:

A. iOS only (does not happen on Android)
1. When user tries to go back to main view from thread view, a blank view appears instead of main view. Workaround is for user to close/re-open app.

B. iOS and Android
1. Deleting post from thread causes a crash

Nothing else seem to stand out but will continue smoke testing the rest

**Comment by enahum** [comment]
@josephbaylon 
> Deleting post from thread causes a crash

CRT or non-CRT? is it the root post or another post in the thread?

**Comment by enahum** [comment]
@josephbaylon 
> When user tries to go back to main view from thread view, a blank view appears instead of main view. Workaround is for user to close/re-open app.

is this CRT? are you talking about global thread view? I cannot reproduce this with CRT disabled, going to a thread and going back to the channel works just fine.

**Comment by josephbaylon** [comment]
@enahum I retested with the latest builds. The first issue (blank view after attempting to go back to main view from thread) should have said **Android only** (instead of iOS only -- I corrected the text above). It also happens on **CRT only** (and not on non-CRT). This issue does not appear on v1.48.2 build 382 CRT/non-CRT.

The second issue looks resolved already and does not crash anymore on either Android/iOS for CRT/non-CRT.

**Comment by enahum** [comment]
@josephbaylon to be clear the blank screen is on Android and it happens for both CRt and non-CRT. But more importantly we are talking about the thread screen and not the global thread view, yes?

**Comment by josephbaylon** [comment]
@enahum The first issue (blank screen) is Android only and CRT only. It happens on **both** global thread (user goes to Thread > taps on a thread > Direct Message Thread) and regular channel (user goes to channel > taps on post > Direct Message Thread) and attempt to go back.

To correct, the second issue is actually an existing issue on CRT mode only even on v1.48.2 (when parent post is deleted on thread view). It only crashes when parent post is deleted and not when reply post is deleted.

**Comment by enahum** [comment]
@anurag6713 can you please look at both CrT issues on this PrE, specially as they seem to be an existing issue in either 1.48 and the upcoming 1.49.

Thanks, let me know once you started to look at it how it goes.

cc: @Willyfrog

**Comment by anurag6713** [comment]
Thank you @enahum, looking into it.

**Comment by anurag6713** [comment]
Issue 1: When CRT on, going back from thread screen is crashing the app.

Reason: In Navigation, We are using `rightButtons` in `topBar`. There is a component with name `ThreadFollow`. It gets mounted on navigating to the THREAD screen.

This component is added to the stack and ongoing back. Log in `componentDidDisappearListener` is receiving only this `componentId` but not `thread` id

Not sure what's causing the issue as we haven't made any changes to it. There is no issue if we use only `text` instead of `component` in `rightButtons`. I'm still looking into this one. 

CC: @enahum

**Comment by enahum** [comment]
@anurag6713 alright keep me posted, I'm not sure exactly what you mean, but if you want me to take a look, point me in the right direction and I'll give it a try

**Comment by anurag6713** [comment]
https://github.com/mattermost/mattermost-mobile/blob/2267f0a408419bf54e9b0f56d2cf3ecbadcbf817/app/screens/thread/thread_base.js#L72-L94

Sorry, this is the code I am talking about.

**Comment by anurag6713** [comment]
@enahum, It's crashing when React Native is `0.67.1`. It's working fine with `0.66.4`.

`0.67.1` - `7.25.1` - Crashing
`0.67.1` - `7.24.x` - Crashing
`0.66.4` - `7.25.1` - Working

**Comment by enahum** [comment]
@anurag6713 yes I believe is caused by this https://github.com/facebook/react-native/pull/30919/files

**Review by josephbaylon — APPROVED** [review]
LGTM. Verified both issues have been resolved in the latest builds.

**Pull request merged**
