### PR TITLE
Fixes crashes and errors in iOS Share Extension and Notification Service

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
For the Share extension we added a small cache to retrieve the session token and also reduce the amount of calls to retrieve it. At the same time, if we fail to retrieve the token we now display an error screen in the Extension asking the user to Retry.

Also, clean some code and addressed all the related sentry reports about the share extension and notification service.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-50004

#### Release Note
```release-note
Fixed some potential crashes in the iOS Share Extension and Notification Service
```

### CODE REVIEW

**Comment by enahum** [comment]
@esethna as you were able to reproduce the issue with the share extension it would be good for you to take it for a spin an report back. I've already triggered the build of the PR.

**Review by avinashlng1080 — APPROVED** [review]

**Comment by enahum** [comment]
Android builds seems to be broken in main cause of an issue with calls. I'm going to look into it

**Review by anurag6713 — APPROVED** [review]

**Pull request merged**
