### PR TITLE
MM-26829 Rename actual_user_id to user_actual_id to be more consistent with the rest of MM telemetry.

### PR DESCRIPTION
**Pull request by Adovenmuehle**
#### Summary
Rename actual_user_id to user_actual_id to be more consistent with the rest of MM telemetry.

#### Tickets
JIRA: https://mattermost.atlassian.net/browse/MM-26829

### CODE REVIEW

**Comment by Adovenmuehle** [comment]
FYI @enelson720

**Comment by enahum** [comment]
@amyblais @esethna please provide a milestone for this PR, discuss it over with @Adovenmuehle if needed.

**Comment by amyblais** [comment]
@Adovenmuehle 
1. What is the level of urgency on this? 
2. If this is included in the next release (v1.33 to be released on July 16th), how risky is this PR and are there any chances of causing new regressions in the release?

**Comment by Adovenmuehle** [comment]
@amyblais

1. I'd call this one Low/Medium priority
2. Risk here is low

**Comment by esethna** [comment]
@amyblais I'd propose v1.34

**Comment by josephbaylon** [comment]
Just noting that this PR is waiting on self-serve dashboard per @Adovenmuehle 
Also, @enahum I just wanted to confirm with you if Rudder is enabled in this PR build.

**Comment by enahum** [comment]
@josephbaylon you need to rebuild it from another branch to have rudder enabled in the PR, the key was added just a couple of days ago for PR builds.

**Comment by josephbaylon** [comment]
@Adovenmuehle Updated build from new branch generated here ([build-pr-4520-1](https://community.mattermost.com/core/pl/mwkf6y4bd7g58mjxr7t8ijm66y))

**Comment by enahum** [comment]
@Adovenmuehle @josephbaylon gentle reminder about this PR

**Comment by josephbaylon** [comment]
@enahum @Adovenmuehle If we want this merged in time for the feature complete today, I can just test this after the RC has been cut if the dashboard doesn't make it in time. The code changes look straightforward. Let me know and I can approve and test later

**Comment by enahum** [comment]
Yes, lets do that

**Comment by Adovenmuehle** [comment]
Works for me.

**Pull request merged**
