### PR TITLE
MM-36640 Bring back permalink view on search/recent mentions/pinned and saved posts

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
When working on the performance improvements the permalink view was mistakenly taken off from search / recent mentions / pinned and saved posts, this brings it back.

Note: This PR downgrades the react-native-navigation library as the one used in 1.44 breaks the permalink view due to a bug in the library. This bug in fact was fixed in the last version but another bug was introduced that breaks our transition to the gallery view.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-36640

#### Release Note
```release-note
Added back the permalink view from search, recent mentions, pinned and saved posts.
```

### CODE REVIEW

**Review by josephbaylon — APPROVED** [review]
LGTM. Tapping item on search results/recent mentions/pinned messages/saved messages opens permalink modal with `Jump to recent messages` button and tapping on that button brings user to recent messages on that channel. Also tested real permalinks still open the modal.

**Review by matthewbirtch — APPROVED** [review]
Works like it used to again.

The highlighted message doesn't get scrolled to properly in the permalink modal, but that's a different, much more complex issue that we've discussed before

**Review by esethna — APPROVED** [review]
Thanks Elias!

**Review by anurag6713 — APPROVED** [review]

**Comment by enahum** [comment]
manual cherry-picked

**Pull request merged**
