### PR TITLE
Show the unsupported alert if server version is available

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
Show the alert for unsupported server versions if the server version is available

### CODE REVIEW

**Comment by esethna** [comment]
@enahum to confirm, this change is to make it so that if the server version is not set it won't show the alert? What are the reasons it would not be set and how often would that occur?

**Comment by enahum** [comment]
@esethna how often, not sure, as we did not catch this during our QA.. probably as it gets set after we already loaded the channel screen.

and yes, if the version is not set at this point we would not show the  alert.

**Comment by esethna** [comment]
@enahum in that case should we wait to load the channel screen before trying to show this alert? I just want to make sure we aren't making a change that will hide the alert for the majority of cases vs fixing a random corner case

**Comment by enahum** [comment]
@esethna that can be counter productive from the perceived performance stand point. In any case I'm inclined to leave it as is where it can have false positives and **show** the alert.

**Comment by esethna** [comment]
What kind of a performance hit are we talking about? I think it's important to get this version detection as accurate as possible (minimize false negatives and false positives) @enahum

**Comment by enahum** [comment]
@esethna changes made.

**Comment by esethna** [comment]
cc// @enahum if we can spin up a test build.

@josephbaylon let's please test this thoroughly (multiple times on various devices and network conditions). Expected here is the same as outlined in the original ticket:

1. Notice appears after the channel screen loads if the server version is <v5.19 and the user is a sys admin only
2. Do not show the notice if the user is coming back from the background (only on cold start of the app)
3. Do not show the notice if the server is v5.19 or great or ever for regular users
4. Notice does not appear multiple times unless the user closes and reopens the app from cold start

cc// @enahum if there's additional cases we should be concerned about?

**Comment by enahum** [comment]
Nothing else than what you outlined.

Not sure why the build is not started by mattermod, @jaydeland do you know?

**Comment by jaydeland** [comment]
@khos2ow - Is Mattermod running properly?

**Comment by khos2ow** [comment]
@jaydeland @enahum there seemed to be some table field missing!! Can you try again now?

**Comment by enahum** [comment]
Thanks @jaydeland @khos2ow it seems to be running now

**Comment by enahum** [comment]
@esethna please confirm

**Comment by esethna** [comment]
1. End users and team admins should never see this specific alert, there is a different alert for them as done in a different ticket (https://mattermost.atlassian.net/browse/MM-26744)

image

@josephbaylon can you confirm which alert team and end users saw?

2. Can you clarify what "alert dismissed" vs "alert not dismissed" means in the table headers? 

System admins should not see the alert if the app is coming from the background

image

**Comment by josephbaylon** [comment]
@esethna 

A. Alerts shown
1. Sysadmin
Screen Shot 2020-07-24 at 10 20 06 AM

2. Team Member (End User) and Team Admin
Screen Shot 2020-07-24 at 10 20 33 AM


B. Alert Dismissed and Alert Not Dismissed
**Alert Dismissed** means the following steps,
1. Launch App and connect to 5.18 server
2. Once logged in, when prompted with alert above, either press `Dismiss` for sysadmin or `Ok` for regular user

**Alert Not Dismissed** means the following steps,
1. Launch App and connect to 5.18 server
2. Once logged in, when prompted with alert above, user does does not dismiss alert


C. Backgrounding app as performed in iOS and Android means minimizing app without closing it, as opposed to closing the app (see Android Notes item 2 and iOS Notes item 2). In the case of the result,
1. Launch App and connect to 5.18 server
2. Once logged in, when prompted with alert above, user does does not dismiss alert
3. Background app (minimize) then re-open (maximize)


Let me know if there are other stuff that are unclear.

**Comment by enahum** [comment]
LGTM too

**Pull request merged**
