### PR TITLE
[MM-19727] Disable scroll and use pan handler for Android

### PR DESCRIPTION
**Pull request by migbot**
#### Summary
On Android, if the ScrollView has scroll enabled then it will handle all gestures initiated in it, so our pan handler in DrawerLayout never fires. To overcome this I disabled scroll for Android if the page index is 1 and then used `scrollTo` to achieve scrolling when swiping/dragging right. When swiping/dragging left on page 1, the drawer can now be closed as the pan handler handles the gesture. On page 0, scroll is enabled so the ScrollView functionality works as before. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-19727

#### Checklist
- [x] Has UI changes

#### Device Information
This PR was tested on:
* Android emulator, 9
* Galaxy S7, 8.1
* iPhone 11 simulator, 13.2

### CODE REVIEW

**Comment by saturninoabril** [comment]
I can test only emulator as I don't have such physical Android device. If necessary on physical device, I can ask other QA to test it.  Please let me know, thanks

**Comment by saturninoabril** [comment]
@ogi-m will help review this on physical device.  Thanks Ogi!

**Comment by ogi-m** [comment]
@migbot Tested on Moto G6/Android 9, and I'm seeing an issue when swiping from Channels page to Teams page. It appears to a bit choppy.
I compared the same user with 13 teams on the PR build and 1.26, and the transition seems a lot smoother on 1.26.

**Comment by enahum** [comment]
@migbot @andrewbrown00 lets discuss this ticket with Matt (don't have his github handle) and determine if we are going to be doing this or not

**Comment by enahum** [comment]
@migbot going to close this one and the ticket can be resolved once #3911 gets merged

**Pull request closed without merging**
