### PR TITLE
adding Persian to the languages

### PR DESCRIPTION
**Pull request by ctlaltdieliet**
#### Summary
Adding Persian as a new supported language to Mattermost
#### Checklist
- [] Added or updated unit tests (required for all new features)
- [ ] Has UI changes
- [x] Includes text changes and localization file updates
- [ ] Have tested against the 5 core themes to ensure consistency between them.

#### Release Note
```release-note
Added Persian as a new supported language to Mattermost
```

### CODE REVIEW

**Comment by ctlaltdieliet** [comment]
Pinging @jasonblais and @cwarnermm

**Review by cwarnermm — APPROVED** [review]
Thank you!

**Review by larkox — APPROVED** [review]

**Comment by ctlaltdieliet** [comment]
> I do not believe we support RTL on mobile, can you please share a video recording of the language being used?

For the webapp/desktop app there is a plugin if I remember well. But RTL on mobile I have no idea...
I'm just a translator so I don't have developer setup for mobile. Can someone build this branch?

**Comment by enahum** [comment]
> > I do not believe we support RTL on mobile, can you please share a video recording of the language being used?
> 
> 
> 
> For the webapp/desktop app there is a plugin if I remember well. But RTL on mobile I have no idea...
> 
> I'm just a translator so I don't have developer setup for mobile. Can someone build this branch?
> 
> 

There is a QA Builds channel in the community server. From the builds you'll only be able to install it on Android

**Comment by ctlaltdieliet** [comment]
Thank you @enahum 
One problem, the language selection for mobile is done on the server. We need a server that supports Persian as well...
Or we need to change the language file from another language to Persian (like French containing the Persian strings).
The fa.json is not included as it would raise a conflict with the automated Weblate commits.
I guess we need support from QA for testing this? @cwarnermm @metanerd  ?

**Comment by metanerd** [comment]
Hi @ctlaltdieliet ! Thank you for your PR! I cannot find the server and webapp PRs to add the Persian language. Please can you provide me a link to those?

**Comment by ctlaltdieliet** [comment]
> Hi @ctlaltdieliet ! Thank you for your PR! I cannot find the server and webapp PRs to add the Persian language. Please can you provide me a link to those?

Hi,
the webapp PR is here.
For server there is no PR. If I remember well: Installing the fa.json file in the i18n-folder will do.

**Comment by metanerd** [comment]
I think we need the `fa.json` file included in this PR otherwise I cannot properly test it. In theory it should work though. These are the same changes we did for the last PRs.

**Comment by ctlaltdieliet** [comment]
> I think we need the `fa.json` file included in this PR otherwise I cannot properly test it. In theory it should work though. These are the same changes we did for the last PRs.

Hi @metanerd 
I've added the fa.json file for testing.

**Comment by ctlaltdieliet** [comment]
> I think we need the `fa.json` file included in this PR otherwise I cannot properly test it. In theory it should work though. These are the same changes we did for the last PRs.

Hi @metanerd 
I've added the fa.json file for testing.

**Comment by enahum** [comment]
Is it working as you would expect?

**Comment by ctlaltdieliet** [comment]
> Is it working as you would expect?

I don't speak Persian but it was looking very good to me. The app was behaving as expected.

**Comment by larkox** [comment]
I don't speak persian neither, but something feels off. Specially on second 15. It is supposed to be read right to left, but the part of the text with less opacity is on the right, and the one with more opacity on the left. I guess this is not exactly as a native speaker would expect it (and I feel it is hard to solve for us).

This should be QAed by someone that knows persian.

**Comment by esethna** [comment]
Closing due to inactivity

**Pull request closed without merging**
