### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Weblate](https://hosted.weblate.org/projects/mattermost-test/mattermost-mobile_release-1-32/) for Mattermost-test/mattermost-mobile_release-1.32.

### CODE REVIEW

**Comment by enahum** [comment]
@metanerd @wget ???

**Comment by metanerd** [comment]
@enahum Yes, I added this.

**Comment by enahum** [comment]
@metanerd on thanks... I do see every single line mark as changed because of identation, is that expected? If so, why?

**Comment by metanerd** [comment]
It seems like weblate handles the translation with this indentation style. Do we have a reason to keep the indentation as it was before? Other than the diff check with mmjstool?

**Comment by enahum** [comment]
No real reason, was just curious

**Pull request closed without merging**
