### PR TITLE
Optimize post header timestamp

### PR DESCRIPTION
**Pull request by koxen**
#### Summary
Optimize post headers, avoid using heavy date formatting code.
Same as in webapp fixed recently.
Note: date header seems to always render dd/mm/yyyy so that's what I replaced it with

#### Ticket Link
[Please link the GitHub issue or Jira ticket this PR addresses.]

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Added or updated unit tests (required for all new features)
- [ ] All new/modified APIs include changes to [mattermost-redux](https://github.com/mattermost/mattermost-redux) (please link)
- [ ] Has UI changes
- [ ] Includes text changes and localization file updates

#### Device Information
This PR was tested on: [Device name(s), OS version(s)] 

#### Screenshots
[If the PR includes UI changes, include screenshots (for both iOS and Android if possible).]

### CODE REVIEW

**Comment by koxen** [comment]
Hm, I see there are two components that pass custom format to FormattedDate:
channel_info_header, date_header.
post header is using default

I think what I can do is just create a fast-path if custom format is null and use react-intl otherwise.

**Comment by enahum** [comment]
@koxen the problem is that the format it depends on the locale so we should try and find a better solution and not just go with dd/mm/yyyy and as you said in your previous comment there are some components that uses their own format so definitely something to take a closer look instead of just go at it ;)

Also you have some eslint problems and would need a rebase

**Comment by koxen** [comment]
@enahum I'd be fine with optimizng only formatted_time.js for now as date is not used when rendering post_list (date is used i.e. when viewing search results)

**Comment by koxen** [comment]
do you see any problems with new formatted_time?

**Comment by enahum** [comment]
@hmhealey please take a look at this

**Pull request closed without merging**
