### PR TITLE
Fix styling when theme is change in another device

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
Update all the styles when the theme is changed in another device

#### Ticket Link
https://mattermost.atlassian.net/browse/RN-544

### CODE REVIEW

**Comment by enahum** [comment]
@hmhealey @mkraft have you guys tested this one?

**Comment by mkraft** [comment]
@enahum Oops didn't notice the label. Testing now.

**Comment by mkraft** [comment]
I changed themes from browser while viewing each mobile view on the iPhone 6 emulator 👍

**Comment by hmhealey** [comment]
I'm seeing the drawer bleeding through some of the components on Android. There's a screenshot on pre-release

**Comment by hmhealey** [comment]
Cool, looks good to me now

**Pull request merged**
