### PR TITLE
Improve Android Cold Start

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
With this PR:
* Make use of an updated version of JavaScriptCore (JSC) engine for Android replacing the one shipped with RN
* Build Android app using Unbundle (Generally it is useful to apps that have large amounts of code that are not needed for a while after startup)
* Make use of inline requires to lazy load libraries, functions and components only when needed
* Refactor entry point
* Updated splash screen layout on Android to use Constraint Layout
* Removed polyfills
* Removed react-native-orientation
* Render the channel list in the drawer once the channel screen has mounted
* Replace a few svg components with png images
* Update RN to use 0.55.4

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-10314

#### Device Information
This PR was tested on: 
* Android 7.0 Samsung J5
* Android 7.1.1 and 8.0 Emulator
* iOS 11.3 iPhone X (simulator) and iPhone 6s

### CODE REVIEW

**Comment by koxen** [comment]
> Removed polyfills
I can't see these being removed in your commits - but don't remove ES6 polyfills - it's causing a bug I mentioned that breaks permissions after some time of inactivity....(dunno why, maybe some logic is getting silently redirected into catch() )

**Comment by miguelespinoza** [comment]
I’m not following why this PR got closed. https://github.com/mattermost/mattermost-mobile/pull/1598

Just to be clear I had a specific goal for that PR apart from cold-start.
`mattermost.js` has become a class for all things to initialize.  A god class if you will.  My intent was to clean up that class in order to introduce:
1. Ease of maintainability
2. Decoupling logic and global state
3. Easier contributions from the community

What I did was decouple all initializing logic into a couple of steps:
1. All listeners and callbacks should be in one file
2. All specific logic (push notification, EMM, error_handling, etc) should be decoupled if possible
   1. A work in progress intent, currently have push_notification and error_handling logic decoupled
3. Global state is easier to maintain when a class is in control `app/app.js`
   1. This allows for easy data management of the cold-start process
   2. Allows for interesting additions like data caching (since state data is controlled by one class it’s easy to add a caching layer to speed up the cold-start process)
4. An Entry component is started by the Navigator in order to show the user that the app is processing/loading data, this accomplishes a couple of things.
   1. User perceives that the app loads 2x faster
   2. Only focuses on running the rehydration logic,  the only critical component of cold-start

Just to show you the progress made with my PR with addition to some other changes and this PRs `RN Unbundling` and `Inline-Require` work, here’s a comparison between the 2 builds and their cold-start process.





@enahum, @saturninoabril, @hmhealey thoughts?

**Comment by hmhealey** [comment]
It's probably a good thing that we're pushing 1.9 out a bit to line up with 5.0. These are a lot of complicated changes

**Comment by enahum** [comment]
@hmhealey this will still have more changes, waiting on @miguelespinoza PR changes and then rebase this one on top of that one, etc.. :P

**Comment by miguelespinoza** [comment]
@hmhealey and @enahum PR https://github.com/mattermost/mattermost-mobile/pull/1598 is ready.

I'll review this shortly to make sure we're not missing anything.   What's the release date for 1.9?

**Comment by enahum** [comment]
closing in favor of smaller PR's

**Pull request closed without merging**
