### PR TITLE
Fixes an issue with channel intro not displaying

### PR DESCRIPTION
**Pull request by csduarte**
#### Summary
Fixes an issue where the channel intro would not display for some channels.

### CODE REVIEW

**Comment by jarredwitt** [comment]
Wait for #665 to be merged.

**Comment by hmhealey** [comment]
That PR has been merged, but this now needs a rebase

**Comment by jarredwitt** [comment]
Will do

**Comment by hmhealey** [comment]
Also, what was the actual cause of the issue? Just curious

**Comment by jarredwitt** [comment]
It was mostly this line https://github.com/mattermost/mattermost-mobile/pull/667/files#diff-f1169187583410c3e06e96f03da9679bR70.

`General.POST_CHUNK_SIZE` was undefined. Also cleaned up the logic and styling.

**Comment by enahum** [comment]
@jarredwitt needs rebase

**Comment by jarredwitt** [comment]
@enahum @hmhealey updated and rebased.

**Pull request merged**
