### PR TITLE
Fix Hamburger and iOS App Icon badge number when marking channel as unread

### PR DESCRIPTION
**Pull request by enahum**
Redux PR: https://github.com/mattermost/mattermost-redux/pull/1015/commits

https://mattermost.atlassian.net/browse/MM-21153

### CODE REVIEW

**Comment by jgilliam17** [comment]
There may be an issue with the Team badge count now (on teams drawer). I am commenting here as it may be related to this fix. 
Teams count is inconsistent, double or more of what hamburger menu shows.

**Comment by enahum** [comment]
Good catch @jgilliam17 it was an oversight for sure

**Comment by jgilliam17** [comment]
@enahum I retested on the [test build](https://community.mattermost.com/core/pl/akpuqqg8jbgwijwqt5fwx9ob5y) linked here, iOS app

- Team icon on Teams drawer is missing notification badge for DMs marked as unread and any new DMs received. Hamburger menu and Mattermost app icon continue to show the correct count.
- Team icon shows red dot notification when user has other unread channels, but not for DMs
- Team icon shows the badge count for standard in-channel mentions, but again not for DMs.

**Comment by enahum** [comment]
@jgilliam17 are you aware that DM's and GM's are not linked to any team so no team badge will be set for DM's and GM's right ?

**Comment by jgilliam17** [comment]
Ah, clearly mistake on my end. 🙂

**Comment by lindalumitchell** [comment]
@enahum I also re-tested Android using [build linked in this post](https://community-release.mattermost.com/core/pl/fhterrzjgfdffk17q9syz1wxyw). Not sure if this could possibly be an issue with Microsoft Launcher config (to allow app icon badge numbers), but I'm not seeing the marked-as-unread count reflected in the app icon badge number. I can see badge numbers on the app icon, but they don't match the hamburger number.

1. DesktopUser sends MobileUser two DMs
2. MobileUser reads DMs and replies to one
3. MobileUser long-presses the first DM and taps Mark as Unread
4. Hamburger shows 2 (not counting own post, as expected)
5. MobileUser puts app in background
6. **No mention badge appears on app icon?** (Should show 2?)
7. DesktopUser sends another DM
8. **MobileUser sees (1) badge on app icon?** (Should show 3?)

Shouldn't the app icon show the same badge number as hamburger, so step 6 above should show (2) and step 8 should show (3)?

**Comment by lindy65** [comment]
I tested twice on Huawei P30 Pro, Android 9 with Microsoft Launcher set up to show numbers for notifications on app badges.  I followed Linda's steps above and got the same results as her.

**Comment by enahum** [comment]
@lindalumitchell and @lindy65 Android does not support setting the app icon badge number manually without a notification.
https://github.com/mattermost/mattermost-mobile/blob/master/app/push_notifications/push_notifications.android.js#L98

**Pull request merged**
