### PR TITLE
MM-31964 Set default value of bool form field to false

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

This PR ensures that a app form field of type `bool` has its original value set to false, if an initial value was not provided.

#### Ticket Link

Fixes https://mattermost.atlassian.net/browse/MM-31964

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by jfrerich — APPROVED** [review]
LGTM!

**Review by catalintomai — APPROVED** [review]

**Review by enahum — APPROVED** [review]

**Comment by DHaussermann** [comment]
Sorry for the delay on this one @mickmister are you able to get this current for me>?

**Comment by mickmister** [comment]
@DHaussermann conflicts resolved

**Comment by DHaussermann** [comment]
@mickmister I don't see the builds appearing for this. Possibly as the build is failing. 
image
Is this something that may be code related or could the issue be elsewhere?

**Comment by mickmister** [comment]
@DHaussermann build is fixed

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- Tested to ensure "unset" boolean comes back as `false`
- Regression tested `true` state
- Briefly regression tested other field types
- Tested on Android and iOS
No issues found

LGTM!

**Pull request merged**
