### PR TITLE
MM-10193 Support safe area in landscape for iOS

### PR DESCRIPTION
**Pull request by imisshtml**
Added SafeAreaView support from React Native and React-Native-Safe-Area where appropriate to handle landscape view cutoff.

#### Summary
Used SafeAreaView and React-Native-Safe-Area to properly set landscape views so that content is not cutoff for iOS.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/10193

#### Device Information
This PR was tested on: 
iPhone X - 12.2
iPhone 6s

### CODE REVIEW

**Comment by imisshtml** [comment]
CLA has been signed.

**Comment by hanzei** [comment]
@imisshtml There are some problems with the code style:
```bash
> eslint --ignore-path .gitignore --ignore-pattern node_modules --quiet .


/home/ubuntu/jenkins/workspace/mm/mattermost-mobile-pr/app/components/safe_area_view/safe_area_view.ios.js
  190:53  error  Trailing spaces not allowed  no-trailing-spaces
  191:54  error  Missing trailing comma       comma-dangle

/home/ubuntu/jenkins/workspace/mm/mattermost-mobile-pr/app/screens/channel_info/channel_info_header.js
  10:17  error  Missing trailing comma  comma-dangle

/home/ubuntu/jenkins/workspace/mm/mattermost-mobile-pr/app/screens/channel_info/channel_info_row.js
  12:17  error  Missing trailing comma  comma-dangle

/home/ubuntu/jenkins/workspace/mm/mattermost-mobile-pr/app/screens/channel/channel.ios.js
  69:1  error  Trailing spaces not allowed  no-trailing-spaces

✖ 5 problems (5 errors, 0 warnings)
  5 errors and 0 warnings potentially fixable with the `--fix` option.
```

**Comment by imisshtml** [comment]
> @imisshtml There are some problems with the code style:
> 
> ```shell
> > eslint --ignore-path .gitignore --ignore-pattern node_modules --quiet .
> 
> 
> /home/ubuntu/jenkins/workspace/mm/mattermost-mobile-pr/app/components/safe_area_view/safe_area_view.ios.js
>   190:53  error  Trailing spaces not allowed  no-trailing-spaces
>   191:54  error  Missing trailing comma       comma-dangle
> 
> /home/ubuntu/jenkins/workspace/mm/mattermost-mobile-pr/app/screens/channel_info/channel_info_header.js
>   10:17  error  Missing trailing comma  comma-dangle
> 
> /home/ubuntu/jenkins/workspace/mm/mattermost-mobile-pr/app/screens/channel_info/channel_info_row.js
>   12:17  error  Missing trailing comma  comma-dangle
> 
> /home/ubuntu/jenkins/workspace/mm/mattermost-mobile-pr/app/screens/channel/channel.ios.js
>   69:1  error  Trailing spaces not allowed  no-trailing-spaces
> 
> ✖ 5 problems (5 errors, 0 warnings)
>   5 errors and 0 warnings potentially fixable with the `--fix` option.
> ```

Thanks @hanzei this has been updated

**Comment by imisshtml** [comment]
[mm_10193_video_review.mov.zip](https://github.com/mattermost/mattermost-mobile/files/3358067/mm_10193_video_review.mov.zip)
http://imisshtml.com/videos/mm_10193_video.mov

Video of changes for review

**Comment by hmhealey** [comment]
It looks like we might be doubling up on the margin in some places. In portrait, without the keyboard open, there's a bunch of extra space below the post textbox. This also makes it so that the user can't view the bottom of the channel as well since it sits behind the post textbox.
Screen Shot 2019-07-04 at 4 01 11 PM
Screen Shot 2019-07-04 at 4 01 11 PM

In landscape, I think we want the content to fill the page a bit better. For example, the navigation bar and the border of the post textbox should probably span the whole screen since it looks kind of empty on the sides. Some of the other screens in your video handled that a bit better, so it's likely just a matter of where exactly you're using the safe area component.
Screen Shot 2019-07-04 at 4 02 30 PM

Also, one other thing I noticed is that the channel list in the sidebar has a small gap at the bottom where the background changes colour. We should make it so that it's a solid colour all the way down there
Screen Shot 2019-07-04 at 4 00 32 PM

**Comment by imisshtml** [comment]
@hmhealey Thanks for the review and suggestions!

The PR has been updated:
SafeViewArea updated for channel screen to render the Post field correctly.
Statusbar updated to extend screen width and pad inner content correctly.

The color on the side menu is preexisting it looks like, can we open a new issue so the fix can be tracked separately?

**Comment by imisshtml** [comment]
[mm_10193_updated.mov.zip](https://github.com/mattermost/mattermost-mobile/files/3364507/mm_10193_updated.mov.zip)

Screen capture of updated screen

**Comment by hmhealey** [comment]
I'm double checking on the coloured section at the bottom of the channel list. Now that I think of it, it might be intended because of the "home button" on the iPhone X.

Looking a the video, there's quite a few places where we still have margins on the left and right where content could stretch across to. Would you be able to take a pass through the app and look for any places where it might not look right?

One that I noticed right away were that the drawers including the channel list now have a gap between them and the edge of the screen. The channel list in the left drawer also shows part of the team list when you're on multiple teams
Screen Shot 2019-07-10 at 9 29 11 AM

There also seems to be an issue with the settings screens where the content appears too large for a moment before squishing to not overlap the notch. I'd also expect the white bars behind each setting item to stretch across the screen in this case even though the content of each item should not overlap with the notch
Screen Shot 2019-07-10 at 9 29 58 AM
Screen Shot 2019-07-10 at 9 30 01 AM

**Comment by imisshtml** [comment]
Closing this PR as we have moved the change into the landscape feature since the scope has expanded beyond MM-10193.

The new PR for the landscape branch can be found here:
https://github.com/mattermost/mattermost-mobile/pull/3003

**Pull request closed without merging**
