### PR TITLE
[MM-40160] Crt gallery fix

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
For some reason unclear to me the Gallery had an undefined height when opening while on CRT mode, regardless of the reason it is better to get those values from the Dimensions module instead of relying on having the values on redux.

In addition this fixes some broken compass icons for the attachment file types.

#### Ticket
[MM-40160](https://mattermost.atlassian.net/browse/MM-40160)

#### Release Note
```release-note
Fixed a crash on CRT when opening the Gallery view from within a thread
```

### CODE REVIEW

**Comment by Willyfrog** [comment]
@enahum added https://mattermost.atlassian.net/browse/MM-40160

**Review by Willyfrog — APPROVED** [review]
do we need to port this fix to v2? or should someone review to port it later?

**Comment by enahum** [comment]
@Willyfrog we haven't ported the gallery yet, so it will be included

**Comment by Willyfrog** [comment]
assigning to @koox00 as he'll be working on porting the gallery, so he is aware of the fix :)

**Review by koox00 — APPROVED** [review]

**Comment by enahum** [comment]
@amyblais please coordinate with @Willyfrog to determine if this should be a dot release for 1.48 or shipped in 1.49

**Comment by enahum** [comment]
@Willyfrog who should be assigned as a QA reviewer ?

**Comment by amyblais** [comment]
> @amyblais please coordinate with @Willyfrog to determine if this should be a dot release for 1.48 or shipped in 1.49

@Willyfrog Is this a new regression in v1.48?

**Comment by Willyfrog** [comment]
I didn't experience it before, but I can't tell if it was due to a better connection or something else.

**Comment by amyblais** [comment]
I'm not opposed to a dot release. Maybe we wait a few days to see if anything else gets reported as users update to v1.48.

**Review by josephbaylon — APPROVED** [review]
LGTM. Tapping on an image that is not loaded does not crash anymore and eventually loads the gallery. Also, the file icons are now showing properly.

**Pull request merged**
