### PR TITLE
MM-22089 set default prevent double tap to 1s for ChannelInfo modal

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
The default for preventing a double tap was set to 300ms, at times this was not enough so this PR bumps the default time to 1s

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-22089

### CODE REVIEW

**Comment by chuttam** [comment]
Happy to approve, but I am mildly concerned that this will hide a root cause that's performance-related. Given that we're already focussing on performance, it may be worth opening an investigation ticket? The 300ms "tap standard" is pretty consistent and well-research, and should ideally be a benchmark setting.

The HOC for `ChannelInfo` listens to a lot of state changes, and via [MM-22582](https://mattermost.atlassian.net/browse/MM-22582) we've seen that there can be a deeper issues to find/fix.

@josephbaylon @enahum Were either of you able to reproduce the issue, before the delay increase?

**Comment by enahum** [comment]
@chuttam I can;'t agree with you more, and no I wasn;t able to reproduce..

**Comment by enahum** [comment]
@chuttam want to keep investigating before merging this ?

**Comment by josephbaylon** [comment]
@enahum @chuttam Although very hard to replicate, I was able to repro it on v1.28 and v1.29. However, it is intermittent and I'm still not sure how fast or slow I should be tapping the header to repro it but I'm able to repro it once every 10 or 15 tries

**Comment by chuttam** [comment]
Yes, @enahum . I'll take a peek at this one.

@josephbaylon Awesome. Do you recall reproducing on both Android and iPhone? What device models?

**Comment by josephbaylon** [comment]
> Yes, @enahum . I'll take a peek at this one.
> 
> @josephbaylon Awesome. Do you recall reproducing on both Android and iPhone? What device models?

@chuttam Tested on Pixel 3 XL (Android 10) physical device. I'm curious what @esethna used to repro the issue as that might yield more consistent result.

**Comment by esethna** [comment]
@josephbaylon I used a Samsung Galaxy S7, reset the cache, then tap the header button continuously

**Comment by josephbaylon** [comment]
> @josephbaylon I used a Samsung Galaxy S7. Good way to repro is to reset the cache, then tap the header button continuously

@esethna Thanks for the info. Reseting the cache didn't make much difference for me as to the frequency I could repro the issue. But @chuttam may be more lucky.

@chuttam I tried replicating it as well on emulator and I was able to but more/less the same frequency as the physical device.

**Comment by chuttam** [comment]
I'm able to replicate the opening of two channel info modals, but **very** rarely and with no consistent reproduction steps.

Since `preventDoubleTap` accepts a delay parameter, I'll go ahead and change the setting from 300ms to 1000ms just for this one action, instead of affecting **all** taps across the app that are wrapped in this debouncer.

**Pull request merged**
