### PR TITLE
Update settings.js

### PR DESCRIPTION
**Pull request by bill2004158**
#### Summary
fix prop type

#### Checklist

- [ ] Added or updated unit tests (required for all new features)
- [ ] Has UI changes
- [ ] Includes text changes and localization file updates

### CODE REVIEW

**Comment by enahum** [comment]
@bill2004158 have you sign the cla?

**Comment by bill2004158** [comment]
@enahum , it seems I have signed cla, and added my id to
https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true

not sure why github showns "needs to sign the CLA".

**Comment by enahum** [comment]
Does not need QA

**Pull request merged**
