### PR TITLE
Update NOTICE.txt

### PR DESCRIPTION
**Pull request by amyblais**
#### Summary
Adding dependencies.

#### Device Information
This PR was tested on: [Device name(s), OS version(s)] 

#### Screenshots

react_native_media_controls license:
screenshot at nov 22 16-29-54

semver license:
screenshot at nov 22 16-40-51

babel-polyfill license:
screenshot_30

### CODE REVIEW

**Comment by jasonblais** [comment]
@amyblais Please help include https://github.com/charliesbox/react-native-media-controls/issues/2 in NOTICE.txt after he has added the license file to his repo.

**Comment by enahum** [comment]
@amyblais you need to rebase this, and let me know when is ready for review and merge please

**Comment by amyblais** [comment]
@enahum What does it mean to rebase (I haven't done it before)?

Also, this is now ready for review (except that I haven't rebased yet).

**Comment by amyblais** [comment]
@jasonblais This is ready for review.

**Comment by enahum** [comment]
I’ll rebase it don’t worry

**Comment by enahum** [comment]
I'll be pushing a whole new branch with this changes as I cannot rebase a branch from your fork

**Pull request closed without merging**
