### PR TITLE
MM-12141 Switching broken image error text to icon.

### PR DESCRIPTION
**Pull request by crspeller**
How it looks (ignore the error bar):
screenshot_20180924-114429

Comparison to how it looks on webapp (Firefox):
image

Not convinced this is an improvement over the current behavior:
screenshot_20180924-115356

If we want it bigger or red I can do that.

### CODE REVIEW

**Comment by asaadmahmood** [comment]
@crspeller 
Should look something like this, attaching it in the center channel along with the svg.

[error-svg.zip](https://github.com/mattermost/mattermost-mobile/files/2420770/error-svg.zip)
image

**Comment by enahum** [comment]
@asaadmahmood can we try and avoid and svg, it is super slow to render SVG's in the mobile app, perhaps a png?

**Comment by crspeller** [comment]
@asaadmahmood Awaiting answer to @enahum question.

**Comment by esethna** [comment]
@crspeller can you please help implement the PNG icons above?

**Comment by crspeller** [comment]
Updated!
It now looks like this:
screenshot_20180927-143022

**Pull request merged**
