### PR TITLE
Make GM Intro message to change based on the notification preferences

### PR DESCRIPTION
**Pull request by larkox**
#### Summary
For the GM as DM feature we updated the intro message for GMs, stating that you will be notified for all messages.

This PR updates that to show a message based on the notification preferences.

#### Ticket Link
Fix Mobile part of https://mattermost.atlassian.net/browse/MM-54541

#### Release Note
None if release on 2.9
```release-note
NONE
```

### CODE REVIEW

**Comment by enahum** [comment]
@larkox what if the current server has not been updated to treat GM's as DM's ?

**Review by enahum — APPROVED** [review]
looks like this is ok regardless of the server version

**Comment by larkox** [comment]
> @larkox what if the current server has not been updated to treat GM's as DM's ?

That is handled outside of the changes. In line 148 of `direct_channel.tsx` we have a check so if the feature is not present, we use the old message.

**Review by matthewbirtch — APPROVED** [review]

**Review by harshilsharma63 — APPROVED** [review]

**Review by yasserfaraazkhan — APPROVED** [review]
working as expected in mobile.

**Pull request merged**
