### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Weblate](https://translate.mattermost.com/projects/mattermost/mattermost-mobile_master/) for mattermost-languages-shipped/mattermost-mobile.

Current translation status:

Weblate translation status

### CODE REVIEW

**Review by metanerd — APPROVED** [review]

**Comment by enahum** [comment]
So this type of PR's are no longer cherry-picksd?

How are we making sure that after we branch, the actual release includes the latests translations?

**Comment by amyblais** [comment]
> So this type of PR's are no longer cherry-picksd?
> 
> How are we making sure that after we branch, the actual release includes the latests translations?

@metanerd ^

**Comment by metanerd** [comment]
Sorry, I got distracted a bit. I will cherry-pick the PRs tomorrow. Thanks for checking!

**Pull request merged**
