### PR TITLE
Mm 32502 guest identification 2

### PR DESCRIPTION
**Pull request by furqanmlk**
#### Summary

Created Guest Experience test cases for RN

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-32502
Test Case ID: MM-T1397 (1.0)
Test Case ID: MM-T1404 (1.0)

Note: Need to add verification for `GUEST` badge

### CODE REVIEW

**Comment by josephbaylon** [comment]
@furqanmlk I pushed some clean up and test IDs. See if you can run locally.

**Comment by furqanmlk** [comment]
Thanks @josephbaylon 
I am able to run the test case and test is passing 👍 

**Except issue after login**  
image

**Test Result**
image

**Review by josephbaylon — APPROVED** [review]
LGTM

**Pull request merged**
