### PR TITLE
[WIP] Make text button color same as attachment color

### PR DESCRIPTION
**Pull request by kingisaac95**
#### Summary
This PR submits code that basically passes down the attachment color to the action button and that color is used to style the button text.

#### Checklist
- [x] Has UI changes

### CODE REVIEW

**Comment by jasonblais** [comment]
Hey @kingisaac95, thank you for the contribution and sorry for the delay in my response.

I'm curious on the proposal for making the text color same as the attachment color - in the attached, there is black text against a dark blue background which is harder to see than white text.

After:

image

Before:

image

**Comment by kingisaac95** [comment]
@jasonblais The button text color is just an example/test. The goal here is to have the interactive elements look similar to the attachment theming. If there's a signer who can make design suggestions, I'm open to that.

**Comment by jasonblais** [comment]
@kingisaac95 Got it, makes sense 👍 

The existing implementation is what was proposed by the design team. I'm wondering if we'd then leave it as-is, because if we try to match it with the attachment theming (e.g. match button background colour with the attachment bar colour), then the text colour may not work well with it.

**Comment by kingisaac95** [comment]
We can leave as is since it's a design team proposal, but I'm open to putting in some work if a change is needed @jasonblais.

**Comment by jasonblais** [comment]
Thanks @kingisaac95! Let's do that, and I'll let you know if the design changes later on.

**Pull request closed without merging**
