### PR TITLE
[MM-52657] AV1 support

### PR DESCRIPTION
**Pull request by streamer45**
#### Summary

PR adds experimental support for receiving [AV1](https://en.wikipedia.org/wiki/AV1)-encoded screen-sharing tracks. The change on this side is minimal as we only need to detect whether we support receiving AV1 or not. This is done through the new `RTCPeer.getVideoCodec` static method.

To simplify further, I also modified some code in `calls-common` to make use of WebRTC globals that can be conveniently registered using the provided `registerGlobals` function.

#### Related PRs

https://github.com/mattermost/mattermost-plugin-calls/pull/795
https://github.com/mattermost/calls-common/pull/34

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-52657

#### Release Note

```release-note
Calls: added experimental support for receiving AV1 encoded screen sharing tracks.
```

### CODE REVIEW

**Review by cpoile — APPROVED** [review]
Tried an old version of mobile with new server, new version of mobile with new server, and just in case: new version of mobile with old server. Everything works. Thank you!

**Review by enahum — APPROVED** [review]

**Comment by DHaussermann** [comment]
Hi @streamer45, 
Does this require testing beyond what receiving video with AV1 on as per this PR here?
https://github.com/mattermost/mattermost-plugin-calls/pull/795

**Comment by streamer45** [comment]
> Hi @streamer45, Does this require testing beyond what receiving video with AV1 on as per this PR here? [mattermost/mattermost-plugin-calls#795](https://github.com/mattermost/mattermost-plugin-calls/pull/795)

@DHaussermann The idea is to run this mobile build against both the latest plugin release and the AV1 PR so we can make sure no regressions related to screen sharing exist.

**Review by DHaussermann — APPROVED** [review]
Tested and passed
- Tested current release of Calls with prod mobile release
- Tested current release of Calls with mobile builds from this PR
- Tested Calls AV1 PR with AV1 enable in combination with these builds and production mobile builds
- Tested Calls AV1 PR with AV1 disable in combination with these builds and production mobile builds

In all cases the Android and iOS clients had no issues receiving the video stream.

LGTM!

**Comment by cwarnermm** [comment]
@streamer45 - Is there product or developer documentation impact expected for this Engineering PR?

**Comment by streamer45** [comment]
> @streamer45 - Is there product or developer documentation impact expected for this Engineering PR?

@cwarnermm There's a new system console config setting to control this functionality that we should likely document.

**Comment by cwarnermm** [comment]
@streamer45 - Can you direct me to those details please? I'm not seeing code in this PR that looks like a new config setting.

**Comment by streamer45** [comment]
> @streamer45 - Can you direct me to those details please? I'm not seeing code in this PR that looks like a new config setting.

@cwarnermm Yeah, it's the linked calls PR -> https://github.com/mattermost/mattermost-plugin-calls/pull/795

**Comment by cwarnermm** [comment]
Thanks, @streamer45!!

**Pull request merged**
