### PR TITLE
MM-38331: fixes opening notification while in threads

### PR DESCRIPTION
**Pull request by koox00**
#### Summary

Opening a notification while in threads didn't pop the threads screen,
this commit fixes that.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-38331

#### Checklist

- [ ] Added or updated unit tests (required for all new features)
- [ ] Has UI changes
- [ ] Includes text changes and localization file updates

#### Device Information
This PR was tested on: 

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by enahum** [comment]
Hey @koox00 a quick look at this and I found myself wondering where is the screen being popped. Also we should test this by being in a different screen as well, maybe in the themes screen as a test

**Comment by koox00** [comment]
> Hey @koox00 a quick look at this and I found myself wondering where is the screen being popped. Also we should test this by being in a different screen as well, maybe in the themes screen as a test

the problem was the selected post, we popped and then opened again, because of no check on collapsedThreadsEnabled...

**Comment by koox00** [comment]
> Also we should test this by being in a different screen as well, maybe in the themes screen as a test

@enahum it seems to work at themes screen as well, both CRT on/off

**Review by enahum — APPROVED** [review]

**Review by jgilliam17 — APPROVED** [review]
Thanks @koox00, please ping me for re-review if changes are requested. 
Tested, looks good to merge.
- Verified, with CRT off, opening a push notification while on the thread screen opens on the channel that notification came from.

**Review by anurag6713 — APPROVED** [review]
🎉

**Pull request merged**
