### PR TITLE
MM-48692 Splash Screen Update

### PR DESCRIPTION
**Pull request by matthewbirtch**
#### Summary
Updates the splash screen for dark mode to align with the new onboarding and server/login screens in dark mode as discussed in https://github.com/mattermost/mattermost-mobile/pull/6768.

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/MM-48692

#### Checklist
- [ ] Added or updated unit tests (required for all new features)
- [x] Has UI changes
- [ ] Includes text changes and localization file updates
- [ ] Have tested against the 5 core themes to ensure consistency between them.

#### Device Information
This PR was tested on: iOS 14 Simulator, iPad Pro Simulator, Andoird 12 emulator

#### Screenshots
<table>
<tr>
<td>
image
</td>
<td>
image
</td>
<td>
image
</td>
</tr>
</table>

#### Release Note

```release-note
Updated splash screen theme colors to align with new onboarding, server and login screens.
```

### CODE REVIEW

**Comment by enahum** [comment]
@matthewbirtch no changes to light mode?

**Comment by enahum** [comment]
Going to check this but I think there are missing assets, will confirm soon

**Comment by matthewbirtch** [comment]
> @matthewbirtch no changes to light mode?

Nope, no changes

**Review by enahum — CHANGES_REQUESTED** [review]
the value of the res in the android and asset folder for `values-night/colors.xml` `splashscreen_bg` needs to be changed

**Comment by matthewbirtch** [comment]
> the value of the res in the android and asset folder for `values-night/colors.xml` `splashscreen_bg` needs to be changed

Ok, can do

**Comment by matthewbirtch** [comment]
> the value of the res in the android and asset folder for `values-night/colors.xml` `splashscreen_bg` needs to be changed

Good catch @enahum. Updated!

**Review by enahum — APPROVED** [review]

**Pull request merged**
