### PR TITLE
MM-52748 : Remove 't' functions for defineMessages in Mobile and update mmjstool version

### PR DESCRIPTION
**Pull request by M-ZubairAhmed**
#### Summary
Removed t function from the define Messages object and updated the mmjstool to the latest.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-52748

#### Checklist

- [ ] Added or updated unit tests (required for all new features)
- [ ] Has UI changes
- [ ] Includes text changes and localization file updates
- [ ] Have tested against the 5 core themes to ensure consistency between them.

#### Device Information
none

#### Screenshots
none

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by enahum — COMMENTED** [review]
Lgtm, just wonder why all the changes in package-lock.json specially about ts

**Comment by M-ZubairAhmed** [comment]
Its because of these changes since the last version
https://github.com/mattermost/mattermost-utilities/compare/010f456ea8be5beebafdb8776177cba515c1969e..043f88c972e38fec90bcce49624761958cc65fe6#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

**Comment by enahum** [comment]
> Its because of these changes since the last version
> 
> https://github.com/mattermost/mattermost-utilities/compare/010f456ea8be5beebafdb8776177cba515c1969e..043f88c972e38fec90bcce49624761958cc65fe6#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

Does it cause conflicts? Do we have two verdions of ts with this change? Should deps be updated in the utilities project?

**Comment by enahum** [comment]
@M-ZubairAhmed I do not feel comfortable with the changes in the lock file

**Review by enahum — APPROVED** [review]

**Review by larkox — APPROVED** [review]

**Pull request merged**
