### PR TITLE
MM-21476 Fix iOS inAppPinCode

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
With the migration to RN 61 a couple of libraries were not being linked correctly as they were not migrated to cocoapods, these libraries are the responsible for enabling inAppPinCode managed configuration.

Also since iOS 13 FaceID is now a required permission, if the permission is not granted the authentication does fallback to pin code.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-21476

### CODE REVIEW

**Comment by adamjclarkson** [comment]
There are a few blockers for me to personally test this (UDID, don't have mobileiron setup). 
@svelle would you be able to zoom me when you test it so I can 1) see how you do it and 2) review approve?

**Comment by enahum** [comment]
@adamjclarkson just validate the string in the code.

In order for you or Sven to test this, we will need to cut the release and use that build with an EMM provider, I did mention on the channel as I don’t really know what the test plan is going to look like

**Comment by saturninoabril** [comment]
Will test after merged.

**Comment by saturninoabril** [comment]
Done cherry-pick into release-1.26 branch

**Pull request merged**
