### PR TITLE
[MM-34823, MM-34825] Use RNN 7.11.3

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
Downgrading RNN to its most recent working version.
Newer RNN has an issue with showing a modal inside a modal and with dismissAllModals.

Not assigning dev review as is just updating the version of a library

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-34823
https://mattermost.atlassian.net/browse/MM-34825

### CODE REVIEW

**Review by josephbaylon — CHANGES_REQUESTED** [review]
@enahum Unfortunately, the issues still persist on this PR build, at least on my local device (iPhone X - 14.4.2)

Do they work on your end?

**Comment by enahum** [comment]
@josephbaylon it totally works for me. I've tested multiple versions an 7.11.3 was the last working version

**Comment by enahum** [comment]
Buuuuuuuuut it looks like I pushed 7.11.4

**Review by josephbaylon — APPROVED** [review]
LGTM. Permalink issues found have been fixed on iOS.

**Pull request merged**
