### PR TITLE
Remove keychain cache to avoid token invalidation problems

### PR DESCRIPTION
**Pull request by larkox**
#### Summary
Remove keychain cache, since it was not being properly invalidated in all instances of the notification service.

#### Ticket Link
Fix https://mattermost.atlassian.net/browse/MM-52991

#### Release Note
```release-note
Fix notifications showing a session expired message when it shouldn't.
```

### CODE REVIEW

**Comment by larkox** [comment]
@EduardoSellanes I would appreciate if you could take a run with this PR and see if the issue is fixed on your side.

**Review by enahum — APPROVED** [review]

**Review by yasserfaraazkhan — APPROVED** [review]
Thank you for the changes.
was able to test it against [spinwick](https://mattermost-pr-24140.test.mattermost.cloud).
after logging back in, the user will see push notifications for new messages.

**Comment by EduardoSellanes** [comment]
@larkox I tested it and works perfect... thanks!

**Comment by larkox** [comment]
@amyblais if we have to add anything to the 2.7 release, it would be great to piggyback this. If the release does not need any fix, we can wait until 2.8

**Pull request merged**
