### PR TITLE
MM-12109 Switch to using server API to determine redirect location

### PR DESCRIPTION
**Pull request by hmhealey**
This matches the web app behaviour and prevents the app from directly contacting any linked address

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-12109

#### Device Information
This PR was tested on: iOS Simulator

### CODE REVIEW

**Comment by hmhealey** [comment]
@enahum Martin just reminded me that this is a new API and filled me in on the conversation about not using it on the mobile app, but I think we can't have the mobile app just contacting every linked URL, similar to how images should ideally go through the proxy.

I'd propose maybe removing this feature on older servers and then using the API on new ones. We can discuss this when you're back in.

**Comment by hmhealey** [comment]
Also, this is more a note to myself, but if we keep using `getShortenedLink` for the time being, we need to add a little something to prevent it from trying to follow non-http links.
```diff
- export async function getShortenedLink(link) {
+ export function getShortenedLink(link) {
+    if (!(/^https?:/).test(link)) {
+        // Only attempt to follow shortened http links
+        return Promise.resolve(link);
+    }
+
     return new Promise(((resolve, reject) => {
```

**Comment by hmhealey** [comment]
Waiting on https://github.com/mattermost/mattermost-redux/pull/632

**Comment by jasonblais** [comment]
@hmhealey Do we have a JIRA ticket tracking these (and Redux) changes for QA? /cc @lindalumitchell

**Comment by hmhealey** [comment]
@jasonblais I'll file one so we can keep track of them

**Pull request merged**
