### PR TITLE
Translations update from Mattermost Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Mattermost Weblate](https://translate.mattermost.com) for [mattermost-languages-shipped/mattermost-mobile-v2](https://translate.mattermost.com/projects/mattermost/mattermost-mobile-v2/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Review by Willyfrog — APPROVED** [review]
/release-note-none

**Review by ctlaltdieliet — APPROVED** [review]

**Comment by ctlaltdieliet** [comment]
@cwarnermm can you aprove this PR as well? We can merge then

**Comment by ctlaltdieliet** [comment]
@lieut-data @cwarnermm 
Can you help approving this PR so it can be merged?

**Review by lieut-data — APPROVED** [review]

**Pull request merged**
