### PR TITLE
[MM-31231] Fix gap between post list and draft input

### PR DESCRIPTION
**Pull request by migbot**
#### Summary
Decrease the `kHeight` value by `bottomSafeArea` when the `kHeight` is not 0 and the keyboard is shown or will be shown.

Note to QA: Please also test transitions back into a screen that initially had the keyboard open, for example, have the keyboard up in the channel screen, press a post to go to the thread screen, then return back to the channel screen. Also include testing with a  Hardware Keyboard.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-31231

#### Device Information
This PR was tested on:
iOS 14.2 devices:
* iPhone SE
* iPhone 11 simulator
* iPhone 12 simulator

iOS 13.7 devices:
* iPhone SE simulator
* iPhone 11 simulator

### CODE REVIEW

**Review by enahum — APPROVED** [review]
LGTM want to see what QA finds on this one.. specially with Hardware Keyboards on an iPad

**Comment by josephbaylon** [comment]
@migbot For physical device (iPhone X 14.2) the gap between post list and draft input looks fixed. However for simulator with keyboad, the gap still appears (see images below)

Note: The transitions look fine for both physical and simulator devices (transition from channel to thread and thread to channel)

**iPhone 11 - 14.2**
|channel|thread|
|:-- |:-- |
|Screen Shot 2020-12-10 at 1 44 15 PM|Screen Shot 2020-12-10 at 1 44 25 PM|

**iPad Pro - 14.2**
|channel|thread|
|:-- |:-- |
|Screen Shot 2020-12-10 at 1 42 20 PM|Screen Shot 2020-12-10 at 1 42 31 PM|

**Comment by enahum** [comment]
sure let me try it

**Comment by enahum** [comment]
ok by me

**Review by josephbaylon — APPROVED** [review]
LGTM. Gap between post list and draft input looks fixed. And transitions work as expected.

@migbot @enahum I went ahead and deleted my workspace, re-downloaded the PR, and re-installed the app and the gap in the post list now looks fixed on simulator. For some reason just doing the `npm run clean` didn't do the trick for me. Sorry for the confusion.

**Comment by enahum** [comment]
Is working for me too

**Pull request merged**
