### PR TITLE
[MM-55649] Fix margin of LatexInline

### PR DESCRIPTION
**Pull request by Paul-vrn**
#### Summary

Modified style properties of latex inline.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost/issues/25561
JIRA: https://mattermost.atlassian.net/browse/MM-55649

#### Checklist

- [ ] Added or updated unit tests (required for all new features)
- [ ] Has UI changes
- [ ] Includes text changes and localization file updates
- [ ] Have tested against the 5 core themes to ensure consistency between them.

#### Device Information
This PR was tested on: 

#### Screenshots

Before:
Screenshot 2023-11-30 at 15 40 53

After:
Screenshot 2023-11-30 at 12 54 44

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by larkox** [comment]
@Paul-vrn This doesn't seem to work in all scenarios. For example, the following text would show as the attached screenshot:
```
hello $\frac{\sqrt{x^n}}{x^2}$ world world world world world world world world world world world world world world $\frac{\sqrt{x^n}}{x^2}$  world world world world world world $test$
```
Screenshot from 2023-12-01 11-46-59

**Comment by larkox** [comment]
@Paul-vrn I was trying on Android emulator.

**Comment by larkox** [comment]
@Paul-vrn I saw your last change, and tried it on the android emulator, and still see the same behavior.

**Comment by cyberjam** [comment]
> > @Paul-vrn This doesn't seem to work in all scenarios. For example, the following text would show as the attached screenshot:
> > ```
> > hello $\frac{\sqrt{x^n}}{x^2}$ world world world world world world world world world world world world world world $\frac{\sqrt{x^n}}{x^2}$  world world world world world world $test$
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Screenshot from 2023-12-01 11-46-59
> 
> @larkox hey, that's weird, what device are you using? I can't reproduce this on my simulator (iphone X or iphone 13).



I reproduced it on the android emulator(14.0). If this issue hasn't been solved yet, I'd like to fix it.
|Android (14.0)|iOS (17.0)|
|---|---|
|image|image|

**Comment by cyberjam** [comment]
> > @Paul-vrn This doesn't seem to work in all scenarios. For example, the following text would show as the attached screenshot:
> > ```
> > hello $\frac{\sqrt{x^n}}{x^2}$ world world world world world world world world world world world world world world $\frac{\sqrt{x^n}}{x^2}$  world world world world world world $test$
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Screenshot from 2023-12-01 11-46-59
> 
> @larkox hey, that's weird, what device are you using? I can't reproduce this on my simulator (iphone X or iphone 13).

Hi @Paul-vrn [This issue(inconsistent inline latex height between android and ios) resolved](https://github.com/mattermost/mattermost-mobile/pull/7742) . It's your turn 😉

**Comment by cyberjam** [comment]
@Paul-vrn This Issue not resolved.

**Comment by cyberjam** [comment]
@Paul-vrn Now, You can resolve [This Issue](https://github.com/mattermost/mattermost/issues/25561)

**Comment by Paul-vrn** [comment]
> @Paul-vrn Now, You can solve [This Issue](https://github.com/mattermost/mattermost/issues/25561)

yes but sorry, I don't have anymore time to work on it, I'm unsigning myself from it

**Comment by cyberjam** [comment]
Ok. Wishing you the best, Paul-vrn!

**Pull request closed without merging**
