### PR TITLE
MM-36532 navigate to channel from any screen when channel link is pressed

### PR DESCRIPTION
**Pull request by enahum**
#### Ticket Link
https://mattermost.atlassian.net/browse/MM-36532

#### Release Note
```release-note
Fixed channel link navigation
```

### CODE REVIEW

**Review by josephbaylon — APPROVED** [review]
LGTM. Tapping on channel link from both main and reply threads now navigates to intended channel.

**Review by anurag6713 — APPROVED** [review]

**Comment by enahum** [comment]
@amyblais @josephbaylon what do you think, should we include this in the 1.44 dot release?

**Comment by josephbaylon** [comment]
@enahum Sure!

**Comment by amyblais** [comment]
> @amyblais @josephbaylon what do you think, should we include this in the 1.44 dot release?

From the ticket I understood that this is not a regression / not super urgent, so it could wait for 1.45, but let me know if you have strong opinion about adding to 1.44.1.

**Comment by enahum** [comment]
@amyblais 
> From the ticket I understood that this is not a regression / not super urgent, so it could wait for 1.45, but let me know if you have strong opinion about adding to 1.44.1.

Yes it is not a regression.. if we include this we will be shipping a dot release for Android and iOS instead iOS only

**Pull request merged**
