### PR TITLE
[MM-40582] Use user_updated event's user to state, to prevent extra GetMe() ping

### PR DESCRIPTION
**Pull request by plant99**
#### Summary

With [user_update event now sending unsanitized user to source](https://github.com/mattermost/mattermost-server/pull/19444), ping to server to get user is redundant.
#### Ticket Link

https://github.com/mattermost/mattermost-server/issues/19361
#### Checklist

- [ ] Added or updated unit tests (required for all new features)
- [ ] Has UI changes
- [ ] Includes text changes and localization file updates
- [ ] Have tested against the 5 core themes to ensure consistency between them.

#### Device Information
This PR was tested on: 

#### Release Note

```release-note
Refactored `user-update` websocket event handler to prevent extra get request to server for unsanitized user.

```

### CODE REVIEW

**Comment by plant99** [comment]
@larkox Hey, since this is my first time working on a react-native environment, it might take me some time to set up the environment. Do you think somebody can put some commits on top of mine, and help out?

Thanks!

**Comment by enahum** [comment]
Hi @plant99 First of all thanks for you contribution, this is great to see.

Something to keep in mind is that people may update their mobile apps way faster than the administrators updating their server versions, so as a policy the mobile app needs to be backwards compatible with every server from the newest to the latest [ESR](https://docs.mattermost.com/upgrade/extended-support-release.html).

As https://github.com/mattermost/mattermost-server/pull/19444 is not even merged yet, this WebSocket Event handler should check that the not sanitized user is being included in the event and execute the new code, otherwise it should keep calling `getMe` as previous servers won't actually include this new data.

> it might take me some time to set up the dev-environment. Do you think somebody can put some commits on top of mine, and help out?

is there anything in particular you need help with?

**Comment by plant99** [comment]
Hi @enahum , that's insightful  (how releases are async), thanks for the feedback. I'll modify the code accordingly.

And nothing particular, really. It will just take me a bit more time to test functionalities either with mobiles, or with emulators. So if someone with an existing mobile dev environment could pull this branch and check, it'd be much faster. But that said, I'll definitely try and set something up ASAP.

**Comment by larkox** [comment]
@plant99 is there anything we can do for you to move this forward?

**Comment by plant99** [comment]
Hi @larkox I’ve been actively at it since yesterday, been trying to setup a mobile dev environment with react-native, xcode. Not having my developer account ready didn’t help. After I fix this, I’ll be working to test my changes and fixing things by Friday. I’ll update here if I fail, the best way forward then would be if someone else more capable can pick this up.


Apologies for the delay.

**Comment by larkox** [comment]
No rush! Just wanted to check in. Happy to know you are still working on it. If you need anything do not hesitate to contact :smile:

**Comment by plant99** [comment]
Sorry, I couldn’t make time for this because of https://github.com/mattermost/mattermost-webapp/pull/9705 , will close that ASAP and come back here.

**Comment by larkox** [comment]
With V2 in beta, I wonder if this still makes sense to do it for V1. What are your thoughts @plant99 ?

**Comment by plant99** [comment]
Hey, @larkox sorry long time no updates on this. I had a chat with @shazm on this a couple of months back. He said that V2 makes these changes 'not-necessary', now I understand that this is V1. Allow me to retract the PR, and please let me know if I should open an appropriate ticket for someone to pick it up.

**Comment by larkox** [comment]
It seems that V2 is already handling this. Take a look at the code here: https://github.com/mattermost/mattermost-mobile/blob/dcfc6e79278ff2fe19a573612272a9b0e13a7df0/app/actions/websocket/users.ts#L35

If you think anything else have to be done, feel free to create a ticket for the Mobile Platform team :smile:

**Pull request closed without merging**
