### PR TITLE
Update Dependencies

### PR DESCRIPTION
**Pull request by enahum**
#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by lindy65** [comment]
Hi @enahum - is there a Jira ticket for this PR?  How do I test it?

**Comment by enahum** [comment]
Hi @lindy65 there is never a ticket about updating the dependencies.

This is affecting all areas of the app, so basically we should run the e2e tests + the tests that are run for release and some additional smoke tests if you want. But I'm afraid this PR cannot be built for RF

**Comment by lindy65** [comment]
Will it be suitable to QA-defer this PR and test post merge then @enahum ?

**Comment by enahum** [comment]
@lindy65 I did some smoke tests, specially around things like navigation and notifications, I guess if the e2e tests pass we can defer the testing for the beta build that includes this PR

**Comment by lindy65** [comment]
Sounds good to me, thanks @enahum 👍

**Comment by larkox** [comment]
@enahum Heads up that e2e tests may not be working. There is already a ticket open about that: https://mattermost.atlassian.net/browse/CLD-5692

**Review by larkox — APPROVED** [review]

**Pull request merged**
