### PR TITLE
Update Readme intro and add logo

### PR DESCRIPTION
**Pull request by BenLloydPearson**
#### Summary
This updates the messaging in the readme intro and adds a Mattermost logo to the top.

#### Ticket Link
n/a

#### Checklist
n/a

#### Device Information
n/a
#### Screenshots
n/a

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by BenLloydPearson** [comment]
@enahum That's a great question. I would say yes. This line would be ideal "An open source platform for secure collaboration across the entire software development lifecycle."

**Comment by enahum** [comment]
@BenCookie95 can you look into the files under `fastlane/metadata` and update them if needed ?

**Comment by BenLloydPearson** [comment]
@enahum @BenCookie95 I took a stab at updating everything I could find in that directory that needs updates.

**Comment by amyblais** [comment]
There is a marketing ticket open.

**Pull request merged**
