### PR TITLE
Fix: render channel links in threads list

### PR DESCRIPTION
**Pull request by space-w-alker**
fixes: https://github.com/mattermost/mattermost/issues/27859

#### Summary
Add channel links to the threads list.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost/issues/27859
Jira https://mattermost.atlassian.net/browse/MM-58314

#### Checklist

- [x] Has UI changes
- [x] Have tested against the 5 core themes to ensure consistency between them.

#### Device Information
This PR was tested on: Android Emulator, Android 12

#### Screenshots
Before:
before_changes

After:
after_changes

#### Release Note
```release-note
Added channel links to threads list
```

```release-note

```

### CODE REVIEW

**Comment by rahimrahman** [comment]
Hi @space-w-alker -- thank you for your first contribution and fix.  I'll help review this with my colleagues.

**Review by enahum — APPROVED** [review]
Lgtm 🎉

**Review by rahimrahman — APPROVED** [review]

**Review by yasserfaraazkhan — APPROVED** [review]

**Comment by hanzei** [comment]
@rahimrahman Can we merge this PR?

**Pull request merged**
