### PR TITLE
translations PR 20190724

### PR DESCRIPTION
**Pull request by enahum**
Ideally this PR should be review by community members for each language.

Note: In the event that you see an english translation instead of the desired language is because this PR was submitted before the translation was made on the Mattermost Translation Server and probably will be submitted for the next PR.

### CODE REVIEW

**Comment by enahum** [comment]
@jasonblais why QA Review?

**Comment by jasonblais** [comment]
@enahum Just following the new process where every PR must have a QA review. I realize they'll likely say 'yes, looks good' and approve

**Comment by enahum** [comment]
@jasonblais I understand the new process, but this is certainly an automated PR that has been going on for more than two years now, and I really don't see a reason to stamp the QA approval, but 0/5 I'll defer to @lindalumitchell to make the decision

**Comment by jasonblais** [comment]
@enahum Yep exactly, agree. But it'll be up to them if they want to be aware of changes in future

**Pull request merged**
