### PR TITLE
Use commonmark & patch it instead of a fork

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
This PR removes the commonmark forks and applies the patch to the libraries shipped in npm

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by hmhealey** [comment]
I'm not reading through the whole patches since they're absolutely massive, but are you sure we want to maintain our forks this way? I didn't realize just how much of both libraries we'd changed. This sort of patch seem helpful for one-off fixes, but they seem like they'll be miserable to maintain in the long run as we update to newer versions of the libraries.

**Comment by enahum** [comment]
@hmhealey 
I'm 0/5 but then we should be doing a better job in updating our forks.. and I would want us to publish them to npm instead of using the repo.

Thoughts?

**Comment by enahum** [comment]
Another reason why the patch is massive is cause it includes dist folder where the library is built

**Comment by enahum** [comment]
@josephbaylon can you please test this PR on markdown and ensure everything is as it should ?

**Review by josephbaylon — APPROVED** [review]
LGTM. Tested the following markdowns based on the files changed:
at_mention
channel_link
emoji
edited_indicator
hashtag
mention_highlight
search_highlight
table
table_row
table_cell

I compared it to v1.44.1 build 360 and all of them look the same and correct.

Let me know if there's anything I missed.

**Comment by enahum** [comment]
@josephbaylon I would test: lists, code blocks, quotes, urls, inline images and every other markdown feature that we have.

**Comment by josephbaylon** [comment]
In addition, I also tested all of formatting found in this link https://community.mattermost.com/help/formatting and compared them with v1.44.1 build 360 and all of them look the same.

**Pull request merged**
