### PR TITLE
Fix cannot search user when pressing space

### PR DESCRIPTION
**Pull request by hpkhanh1610**
#### Summary

- When typing user name in "Search messages & files", pressing space will not show the user list name anymore. Hence cannot search the user we want.

#### Checklist

- [ ] Added or updated unit tests (required for all new features)
- [ ] Has UI changes
- [ ] Includes text changes and localization file updates
- [ ] Have tested against the 5 core themes to ensure consistency between them.

#### Device Information
This PR was tested on:  ios and android.

#### Screenshots

Before fix, cannot search "Adam Caskey" and "le minh son" when pressing space.

https://github.com/mattermost/mattermost-mobile/assets/39702132/91198c0a-78c8-4632-9ec5-bff91ad9e7f8

After fix, pressing space will allow user to continue to search

https://github.com/mattermost/mattermost-mobile/assets/39702132/0f67f7e0-04ee-496f-8a25-e41fe1e78833

#### Release Note

```release-note
Fix cannnot search user when pressing space
```

### CODE REVIEW

**Review by larkox — APPROVED** [review]
LGTM, just wanted to verify that adding more elements to the search doesn't break the autocomplete for others (for example, `from:someuser in:somechannel`).

**Comment by hpkhanh1610** [comment]
> LGTM, just wanted to verify that adding more elements to the search doesn't break the autocomplete for others (for example, `from:someuser in:somechannel`).

Hi, it still works fine.
https://github.com/mattermost/mattermost-mobile/assets/39702132/a074d482-a9df-469e-b464-3c5fc00d348c

**Comment by enahum** [comment]
Can we do the same for channels, i think it has the same problem

**Comment by hpkhanh1610** [comment]
When fixing for channel regex, I found out that there is an app crash when searching channel only (in:channelname), so I also fix that bug as well by adding ".?" in "searchPatterns = matches?.[key]?.map(convertSearchTermToRegex);" since "matches?.[key]" returns null


https://github.com/mattermost/mattermost-mobile/assets/39702132/2d03e123-24e6-4945-b69b-74c1efe2addb

**Comment by hpkhanh1610** [comment]
Hi @enahum @larkox , I see this PR has completed review. Should it be moved to another stage?

**Comment by lindy65** [comment]
Hi @hpkhanh1610 - I can search for messages and files from a user using space between their name/surname.  However, when I switch to files from a user and tap on one of the files, I get the error below.  Not sure whether this is related to your PR?

image

cc @enahum

**Comment by hpkhanh1610** [comment]
> Hi @hpkhanh1610 - I can search for messages and files from a user using space between their name/surname. However, when I switch to files from a user and tap on one of the files, I get the error below. Not sure whether this is related to your PR?
> 
> image
> 
> cc @enahum

Hi @lindy65, I think it's not related to this PR. Can you reproduce it without using my branch to verify it?

**Comment by lindy65** [comment]
Hi @hpkhanh1610 

>I think it's not related to this PR. Can you reproduce it without using my branch to verify it?

Upon further investigation, I'm seeing that perhaps if a channel has been archived (e.g. a playbook run) and the file is from that archived channel, then I get the above error.

Tapping on a file that is in an existing/non-archived channel does not produce the error

@enahum - should I create a ticket for this issue?

**Review by lindy65 — APPROVED** [review]
@hpkhanh1610 - thank you, this is working as expected 👍 

Approving the PR as the issue I found seems not to be related to it

**Comment by enahum** [comment]
> Hi @hpkhanh1610 
> 
> 
> 
> >I think it's not related to this PR. Can you reproduce it without using my branch to verify it?
> 
> 
> 
> Upon further investigation, I'm seeing that perhaps if a channel has been archived (e.g. a playbook run) and the file is from that archived channel, then I get the above error. Also, I'm not 100% sure that the file is from an archived channel but I am assuming so as files from a deleted post wouldn't show up in search, right?
> 
> 
> 
> Tapping on a file that is in an existing channel does not produce the error
> 
> 
> 
> @enahum - do you perhaps know from the error what the issue could be and should I create a ticket for it?

Yes

**Comment by lindy65** [comment]
Have created https://mattermost.atlassian.net/browse/MM-53965 to address the issue I found (not related to this PR)

**Comment by larkox** [comment]
Thanks for the contribution @hpkhanh1610 !

**Pull request merged**
