### PR TITLE
Remove svg usage for user status

### PR DESCRIPTION
**Pull request by koxen**
#### Summary
Replace user status svgs with 72x images.
This improves channel loading time by a lot since react-native-svg is slow.

Note: we are currently checking if it scales nicely on different devices, if it will look poorly I will update the icons to be smaller i.e. 24px.

#### Ticket Link
[Please link the GitHub issue or Jira ticket this PR addresses.]

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Has UI changes

#### Device Information
This PR was tested on: [Device name(s), OS version(s)] 
samsung s7, android 7
@enahum's iphone

#### Screenshots
[If the PR includes UI changes, include screenshots (for both iOS and Android if possible).]

### CODE REVIEW

**Comment by miguelespinoza** [comment]
Got a couple of thoughts:

1. ideally the icon should be all white.  No need to have color since they'll be themed.
2. Which means, we should have default theme colors which are already taking care of in redux I believe (Default theme object from MM)
3. Resolution may be an issue for low-end Android devices, therefore this must be tested on low-end Android devices to see if this change breaks the apps view
* A possible solution: https://github.com/expo/react-native-responsive-image
4. Why not get rid of any other SVG Icons like`OnlineAvatar, AwayAvatar, etc` located in the ChannelDrawer, may further improve the experience

**Comment by hmhealey** [comment]
Looks good on my Nexus 5. Do we have any lower end devices to test on? I don't know if using a simulator would be sufficient for this

**Comment by enahum** [comment]
@asaadmahmood can you help setting the icons to be all white?
@hmhealey I don't think we have, maybe we should just go with it and see what is the response on it and revert it if needed

**Comment by koxen** [comment]
@enahum imo it doesn't matter, I chose some base colors to make it better visible when navigating around in project files.
But I made them white as you wanted.

**Pull request merged**
