### PR TITLE
MM-15161 show icon for bot instead of system icon in ephemeral post

### PR DESCRIPTION
**Pull request by scottleedavis**
#### Summary
show bot icon for ephemeral posts

#### Ticket Link
https://github.com/mattermost/mattermost-server/issues/10640
https://github.com/mattermost/mattermost-webapp/pull/2702

#### Checklist
- [x] Has UI changes

#### Device Information
This PR was tested on: [iPhone X, 12.2 emulator] 

#### Screenshots
Screen Shot 2019-04-25 at 4 52 51 PM

### CODE REVIEW

**Comment by scottleedavis** [comment]
@jasonblais this is no longer WIP.

**Comment by jfrerich** [comment]
@jasonblais  Based on the screenshot posted, and from edits in the code, this looks good.  Do we need one reviewer to validate locally or on a test machine before approving?

**Comment by jasonblais** [comment]
@jfrerich good question, and I'm not sure. @hmhealey what is the typical review process for mobile changes?

**Comment by hmhealey** [comment]
We'd generally test locally if this was a more involved change, but it's pretty straightforward. It would be nice to have some unit tests for this, but I don't think we have any for this component yet, so it would be non-trivial to add ones for this.

**Comment by scottleedavis** [comment]
thank you @hmhealey & @jfrerich !

**Comment by jasonblais** [comment]
Thanks! @hmhealey / @jfrerich this one is good to merge, then

**Comment by jfrerich** [comment]
@jasonblais I haven't performed a merge to master before.  I'd like to it, but would definitely like a walkthrough for the first time.

**Comment by jasonblais** [comment]
Great point. Maybe @hmhealey can help share steps with you tomorrow, and then we document it and include as part of new hire onboarding for future.

**Pull request merged**
