### PR TITLE
MM-49868: Remove mentions of Free OAuth in OpenID-Connect section

### PR DESCRIPTION
**Pull request by plant99**
#### Summary

Remove mentions of Free OAuth since these services are restricted for some users.

Ref: https://github.com/mattermost/mattermost-mobile/pull/7009#issuecomment-1418615392

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-49868

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by kostaspt — APPROVED** [review]

**Review by enahum — APPROVED** [review]
Please coordinate with @amyblais for cherry-picking

**Comment by plant99** [comment]
Hi @amyblais , do we have to do anything for cherry-picking this on cloud mobile.

**Comment by amyblais** [comment]
> Hi @amyblais , do we have to do anything for cherry-picking this on cloud mobile, before merging?

Not for cloud, but if we want this for the next mobile app release (v2.1 on Feb 16th), please cherry-pick this to ``release-2.1`` branch.

**Pull request merged**
