### PR TITLE
Patch react-native-math-view to resolve inconsistent inline latex height between android and ios

### PR DESCRIPTION
**Pull request by cyberjam**
#### Summary

Unlike iOS, height of MathView Component is set on Android.
#### Ticket Link

https://github.com/mattermost/mattermost-mobile/pull/7724#issuecomment-1877842151

#### Checklist

- [ ] Added or updated unit tests (required for all new features)
- [x] Has UI changes
- [ ] Includes text changes and localization file updates
- [ ] Have tested against the 5 core themes to ensure consistency between them.

#### Device Information
This PR was tested on: 

#### Screenshots

|Android (Before)|Android (After)|
|---|---|
|image|image|

Example message text:

```
hello $\frac{\sqrt{x^n}}{x^2}$ world world world world world world world world world world world world world world $\frac{\sqrt{x^n}}{x^2}$  world world world world world world $test$
```
```
Text with formula $\hbar \omega$ inline
```
```
$\sum_{n=0}^{2N-1} x_n \cos \left[\frac{\pi}{N} \left(n+\frac{1}{2}+\frac{N}{2}\right) \left(k+\frac{1}{2}\right) \right]$
```
```
test $test$
```
```
world $\frac{\sqrt{x^n}}{x^2}$  
```

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by enahum — APPROVED** [review]

**Review by larkox — APPROVED** [review]

**Review by yasserfaraazkhan — APPROVED** [review]
🎉 thank you @larkox @cyberjam 


Screenshot 2024-01-18 at 12 35 59 AM
Screenshot 2024-01-18 at 12 35 44 AM
Screenshot 2024-01-18 at 12 34 29 AM
Screenshot 2024-01-18 at 12 34 18 AM

**Pull request merged**
