### PR TITLE
Bump app build number to  454

### PR DESCRIPTION
**Pull request by avinashlng1080**
#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Comment by avinashlng1080** [comment]
@enahum I see PRs getting merged into 'main'. If there's more coming in, I don't mind 'cutting' the build tomorrow.

**Comment by enahum** [comment]
I'll cut it.. currently the build is simply going to fail

**Comment by avinashlng1080** [comment]
> I'll cut it.. currently the build is simply going to fail

Ok

**Review by enahum — APPROVED** [review]

**Comment by enahum** [comment]
also cherry picking for 2.0

As we are cutting a dot release we need to keep the build numbers in sync until the releases

**Pull request merged**
