### PR TITLE
MM-34407 Use Avatars for Sidebar DMs

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
Use DM's Avatars in Sidebar & channel info

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-34407

```release-notes
Added Avatars to the Sidebar DM's & channel info
```

### CODE REVIEW

**Review by matthewbirtch — CHANGES_REQUESTED** [review]
Thanks @enahum, looking good. I'd like to make the tweaks below if we can. Let me know if you have any questions.

1. The status icon needs to be a bit larger (font size for the icon font should be 14.4 - this makes for a 12x12 circle shape for the status)
image

2. The outline on the status should be the sidebar background color (not white) and should be a 2pt outline
3. Can we increase the space between the avatar/icon and the channel name by 5pt?
4. It looks like the alignment between dm channels and regular channels might be slightly off. Can we add 1pt of extra padding on the left side of dm channels to shift everything over slightly?
image
5. For Group messages, can we make some adjustments? 
  - Let's make the container that holds the number 20x20
  - can we adjust the corner radius to 4pt? 
  - can we make the number in the container the fully opaque sidebar text color?
  - can we make he background of the container that holds the number 16% sidebar text color?
  - and then we'll need to make sure the labels for GMs aligns with label for other channel types once you've made the other updates above
image

**Review by josephbaylon — COMMENTED** [review]
LGTM. Sidebar DMs now show avatars with little user status icons.

One minor suggestion below to keep consistent with testID format.

Will retest once UI suggestions have been implemented.

**Comment by enahum** [comment]
@matthewbirtch I get you.. but I those require way more changes than expected as it should consider the avatars on the main channel and thread view as well as the profile screen, etc.. 

If you want all that done, I would argue that this should be done either as a large help wanted ticket or a feature team.

**Comment by enahum** [comment]
Alternatively I can look for some time to do this, but not anytime soon :)

**Comment by matthewbirtch** [comment]
> @matthewbirtch I get you. but those require way more changes than expected as it should consider the avatars on the main channel and thread view as well as the profile screen, etc..
> 
> If you want all that done, I would argue that this should be done either as a large help wanted ticket or a feature team.

I thought these would be pretty minor UI tweaks. I agree we should be consistent between the channel and sidebar avatars, but the avatars in the channel aren't so glaring because the outline around the status is the same as the background color and the avatars are larger in the channel. 

If we can't make these changes on the sidebar, I don't think we should do this at all since the status icons don't work well and things are misaligned.

**Comment by matthewbirtch** [comment]
> @matthewbirtch I get you. but those require way more changes than expected as it should consider the avatars on the main channel and thread view as well as the profile screen, etc..
> 
> If you want all that done, I would argue that this should be done either as a large help wanted ticket or a feature team.

I thought these would be pretty minor UI tweaks. I agree we should be consistent between the channel and sidebar avatars, but the avatars in the channel aren't so glaring because the outline around the status is the same as the background color and the avatars are larger in the channel.

If we can't make these changes on the sidebar, I don't think we should do this at all since the status icons don't work well and things are misaligned.

**Comment by enahum** [comment]
> If we can't make these changes on the sidebar, I don't think we should do this at all since the status icons don't work well and things are misaligned.

@matthewbirtch can you look at this from a large picture and not just the sidebar? What I mean is that if we make the changes we need to make sure those changes are not affecting other places unless we want those changes to apply there as well.

If this changes apply only to the sidebar it is going to mean that I'll be adding code to handle specifically the sidebar while keeping the rest intact. This could get the code messy (not necessarily but).. is that what we want ?

**Comment by matthewbirtch** [comment]
> > If we can't make these changes on the sidebar, I don't think we should do this at all since the status icons don't work well and things are misaligned.
> 
> @matthewbirtch can you look at this from a large picture and not just the sidebar? What I mean is that if we make the changes we need to make sure those changes are not affecting other places unless we want those changes to apply there as well.
> 
> If this changes apply only to the sidebar it is going to mean that I'll be adding code to handle specifically the sidebar while keeping the rest intact. This could get the code messy (not necessarily but).. is that what we want ?

So really, all we're talking about is the avatar and status changes I'm proposing.
- The 2px outline suggested above would be good to apply to the channel as well
- The size of the status icon in the channel is fine as-is since it appears a bit larger in this context

**Comment by enahum** [comment]
> The 2px outline suggested above would be good to apply to the channel as well
today this is done in one component UserStatus.. with the change we'll need to pass a prop down 4 components

> The size of the status icon in the channel is fine as-is since it appears a bit larger in this context
OK, we already have a prop for this size.. just need to change it

I'll make the changes you are asking for.. but I'll do it at some point, thought this was going to be a quick thing, not as detailed.. so I'm moving to something else and at some point I'll come back to this.

**Review by matthewbirtch — APPROVED** [review]
Looks good @enahum!

**Comment by enahum** [comment]
@matthewbirtch I don't think we considered shared channels conflicting with #5241

**Comment by matthewbirtch** [comment]
> @matthewbirtch I don't think we considered shared channels conflicting with #5241

@enahum I don't think there is a conflict, actually. Shared channels simply replace the channel icon with the shared channel icon, while DMs from shared organizations won't show a change to the sidebar item.

**Review by josephbaylon — APPROVED** [review]
LGTM. Sidebar DMs now show avatars with little user status icons.

**Comment by shazm** [comment]
I can see the avatars in the Sidebar and they look pretty good! I do see this TypeError though - unfortunately the stack trace isn't leading me anywhere:


Screen Shot 2021-04-28 at 1 53 53 pm
 

Screen Shot 2021-04-28 at 1 53 41 pm

**Comment by enahum** [comment]
This branch is based on a previous master branch, so to test locally you need to either merge the lastest master or clean everything, fetch deps & recompile.. the TypeError is cause you attempted to run the branch with a different version of MMkV on your local env.

**Review by shazm — APPROVED** [review]
That was it, all good!

**Pull request merged**
