### PR TITLE
RN-298 Fixed profile pictures not being shown when creating new group message channel

### PR DESCRIPTION
**Pull request by hmhealey**
state.entities.users.profilesInChannel wasn't being populated before by the actions that create new group and direct channels.

#### Ticket Link
https://mattermost.atlassian.net/browse/RN-298

#### Device Information
This PR was tested on: iOS Simulator

### CODE REVIEW

**Comment by enahum** [comment]
@hmhealey can you submit this against release-1.3 branch (or change the base of this PR) unless this is not for 1.3 as mentioned in the milestone

**Comment by hmhealey** [comment]
I removed the milestone. I forgot we're releasing 1.3 right now, not 1.2

**Comment by enahum** [comment]
so this goes into master then?

**Comment by enahum** [comment]
@hmhealey please confirm if this PR goes into master or 1.3 release

**Comment by hmhealey** [comment]
@enahum It's for master. I had the wrong milestone.

**Pull request merged**
