### PR TITLE
Update `more unreads` button to new design

### PR DESCRIPTION
**Pull request by rakhi2104**
#### Summary
Update the 'More Unreads' button to match the new design changes.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-server/issues/14141

#### Checklist
- [x] Has UI changes

#### Device Information
This PR was tested on:
- OnePlus 7 running on Android 10

#### Screenshots
more-reads-3

more-reads-2

### CODE REVIEW

**Comment by rakhi2104** [comment]
@matthewbirtch I've made the suggested changes. Can you confirm the Shadows with respect to React Native?

more-unreads-2-1
more-unreads-2-2

**Comment by matthewbirtch** [comment]
Based on the screenshots, it looks like a few more tweaks need to be made:

1. The icon size is a bit smaller than the design
2. The font weight should be semi-bold
3. The shadow is close. I think if we change the shadowRadius to 4, we should be good

I placed the button from the design on to your screenshot to compare

image

I think that's it!

**Comment by enahum** [comment]
@matthewbirtch I think the font weight is a common problem on Android, can you tedt it on iOS and see if it is also present there?

**Comment by matthewbirtch** [comment]
The last review the font weight was incorrect on iOS too. I don't see any further commits to do a new build to test with?

**Comment by rakhi2104** [comment]
I only now realized the font-weight issue. 
In some time I'll push the changes.

**Comment by rakhi2104** [comment]
@matthewbirtch 
- After applying suggested changes
more-unreads-3-1

**Comment by amyblais** [comment]
@chuttam Is there a reason this didn't go through QA review?

Also after a PR is merged, the corresponding Jira ticket should be resolved with the fix version updated.

**Comment by enahum** [comment]
Hi @amyblais this PR has no functional changes just some styles.

It was an honest omition but not critical in any way

**Comment by enahum** [comment]
@josephbaylon feel free to review anyway

**Comment by chuttam** [comment]
> @chuttam Is there a reason this didn't go through QA review?

Whoops. Didn't realise there was no QA review done. I was last on the list to approve. Sorry about that @amyblais ! I'll keep an eye out.

> Also after a PR is merged, the corresponding Jira ticket should be resolved with the fix version updated.

You bet.

**Pull request merged**
