### PR TITLE
MM-13961 Improve gesture to dismiss opened image

### PR DESCRIPTION
**Pull request by avasconcelos114**
#### Summary
This PR replaces the image library being used from `react-native-image-gallery` to `react-native-gallery-swiper`, which is better maintained and makes use of `onSwipeDownReleased` and `onSwipeUpReleased` to better dismiss images

#### Ticket Link
 Fixes https://github.com/mattermost/mattermost-server/issues/13961

#### Device Information
This PR was tested on: 
* iPhone 11 Simulator
* Google Pixel 3XL Simulator

### CODE REVIEW

**Comment by avasconcelos114** [comment]
I took a shot at fixing the [improve gesture to dismiss opened image](https://github.com/mattermost/mattermost-server/issues/13961) issue, what I noticed was that the library was sometimes simply not triggering the `onSwipedVertical` event.

After inspecting the `react-native-image-gallery` library page, I saw [a post recommending people to use another library instead](https://github.com/archriss/react-native-image-gallery/issues/142), which is what I tried to do

So far things seem to be working correctly but I'm not sure if this would be too big of a commitment to move from [the library you guys are maintaining](https://github.com/mattermost/react-native-image-gallery) to this one instead. Another option may be to inspect how this new library implements their image transform events and I could try to make a contribution to your custom lib instead, let me know what route seems more favorable :)

**Comment by enahum** [comment]
@avasconcelos114 a few things 
1. We are not against changing the lib, in fact if it is better maintain getting rid of the fork would be awesome
2. I haven't tested the PR but it seems that it does not changes the opacity as you are dismissing the image?
3. Does it work with other file types as we do now?

**Comment by avasconcelos114** [comment]
Alrighty, I'd like to keep investigating if this library would be able to deliver in the functionality without the need for you guys to maintain the previous one

Just to address your questions:
2. You're right the element doesn't fade in opacity as it gets dismissed, I could probably add an animation for that though
3. I tested with image files and GIFs, but after testing a couple of video files I can see that I'll need to change the implementation of how to render the video elements with this library

Will keep investigating how to make everything work (or if it's even a valid option). It might be good to add a `Work In Progress` tag to this PR for the time being

**Comment by avasconcelos114** [comment]
I've been testing it after the latest batch of changes I made and it looks as though it's been working fine

Any chance I could get someone to help test things out and see if these changes don't break anything I may be missing?

**Comment by avasconcelos114** [comment]
This is great feedback, thank you for taking the time to reviewing this as I wasn't too aware of what were some expected behaviors for the image gallery

I'll see if this library is able to address those (and if doing so requires too many changes to the original library I guess there'd be no point in migrating out of what you're already using)

**Comment by enahum** [comment]
@avasconcelos114 any progress on this one ?

**Comment by avasconcelos114** [comment]
Ah sorry about the lack of follow-up on this one, as it turns out this library isn't all that mature (basically one single maintainer) and would need to be modified to support the zoom behaviors you mentioned (which defeats the purpose of trying to replace your fork), I suppose the better option for the time being is to improve the drag to dismiss behavior in your `react-native-image-gallery` fork, I can try to take a crack at it

**Comment by avasconcelos114** [comment]
welp, I'll go ahead and close this one, sorry it didn't quite accomplish what it set out to do

**Comment by enahum** [comment]
Is fine my friend, I’ve re-opened the ticket

**Pull request closed without merging**
