### PR TITLE
Android: Fix load more messages

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
Loading more messages fix for Android, iOS should still work as expected

#### Ticket Link
https://mattermost.atlassian.net/browse/RN-542

### CODE REVIEW

**Comment by enahum** [comment]
@mkraft did you test it in both platforms before approving?

**Comment by mkraft** [comment]
@enahum No I didn't. I'll try now and reply back here in comments.

**Comment by mkraft** [comment]
@enahum I was able to scroll all the way to the beginning of "private off-topic" channel. I'm back to not being able to login to pre-release on Android emulator so perhaps @hmhealey can try that one?

**Comment by hmhealey** [comment]
I'll pull the branch and see how it feels on my dev phone

**Pull request merged**
