### PR TITLE
MM-56592: Remove deeplink for plugins

### PR DESCRIPTION
**Pull request by sbishel**
#### Summary
Removes a deeplink on '/plugins/' as it wasn't currently being used and was causing some problems.

#### Ticket Link
  Fixes https://mattermost.atlassian.net/browse/MM-56592

#### Checklist

- [X] Added or updated unit tests (required for all new features)
- [ ] Has UI changes
- [ ] Includes text changes and localization file updates
- [ ] Have tested against the 5 core themes to ensure consistency between them.

#### Device Information
This PR was tested on: 

#### Release Note

```release-note
NONE
```

### CODE REVIEW

**Review by calebroseland — APPROVED** [review]
If this is needed in the future, one option may be two separate patterns instead of the one.

```tsx
const pluginMatch = match<{serverUrl: string; id: string}>(`:serverUrl(.*)/plugins/:id(${PLUGIN_ID_PATH_PATTERN})`)(url);
const pluginMatchWithRoute = match<{serverUrl: string; id: string; route: string}>(`:serverUrl(.*)/plugins/:id(${PLUGIN_ID_PATH_PATTERN})/:route(.*)`)(url);
```

**Review by enahum — APPROVED** [review]

**Review by larkox — APPROVED** [review]

**Comment by enahum** [comment]
There soon will be changes to this PR

**Review by jupenur — APPROVED** [review]

**Review by lindy65 — APPROVED** [review]
Thanks @sbishel - this is working as expected, clicking on link opens a browser window.

**Pull request merged**
