### PR TITLE
[MM-48328] Use the width as a dependency instead of dimensions reference

### PR DESCRIPTION
**Pull request by jfrerich**
#### Summary
This PR fixes and issue where rotating a tablet does not recalculate the sceen width. The dimensions reference as a dependency does not change, even though its values do.  use the width as a dependency instead.

#### Checklist

- [ ] Added or updated unit tests (required for all new features)
- [ ] Has UI changes
- [ ] Includes text changes and localization file updates
- [ ] Have tested against the 5 core themes to ensure consistency between them.

#### Device Information
This PR was tested on: 

#### Release Note

```release-note

```

### CODE REVIEW

**Comment by jfrerich** [comment]
Hi, @jgilliam17!  Can you give this PR a shot and see if it resolves the issue you were seeing with files and messages showing side by side in landscape view?

**Comment by larkox** [comment]
@jfrerich The PR is alright and in any case it improves the code, but maybe a more general solution comes from patching RN to properly send a new object when there are changes. I will create a PR to RN and see if it makes sense for them.

**Comment by larkox** [comment]
@jfrerich I was trying to reproduce the problem you were mentioning, and was not able. A code like this always seems to run the `console.log('changed!')` whenever needed. (you can try the code in any visible component)

```
const dimensions = useWindowDimensions();
console.log(dimensions);
useEffect(() => {
    console.log('changed!');
}, [dimensions]);
```

**Comment by jfrerich** [comment]
@larkox, I agree that use effect will show `changed!` when the orientation changes. Unfortunately, I cannot repro the issue either (on the emulator, or my iPad)

During rotation, I see the files results for short time as the dimensions change from orienting the ipad from portrait to landscape, but it doesn't stick with posts and files side-by-side.  It is a weird issue because @jgilliam17 and I have the exact same iPad and build.

**Comment by enahum** [comment]
> During rotation, I see the files results for short time as the dimensions change from orienting the ipad from portrait to landscape

This is expected as device rotation on iPad does not emit the event right away.. not sure if ‘onLayout` triggers faster than the dimensions change

**Review by jgilliam17 — APPROVED** [review]
@jfrerich 
Tested, looks good to merge. Not sure if you need to add more reviewers 
Verified both search tabs are no longer shown at the same time.

**Review by enahum — APPROVED** [review]

**Comment by enahum** [comment]
I'm going to merge as larkrox is out by now

**Pull request merged**
