### PR TITLE
feat: add .m4a file preview

### PR DESCRIPTION
**Pull request by silentyak**
This leverages the video player to play .m4a video files. m4a, mp4, m4v files use the same container format so they are all compatible in all players that support mp4 (just the extensions differ).

Since there is no video track, there is just a black space where the video is, and the audio track will play.

#### Summary

Enable .m4a audio file preview support in Mattermost Mobile, for Android and iOS by using the video player.

#### Checklist

- [X] Added or updated unit tests (required for all new features)
- [ ] Has UI changes
- [ ] Includes text changes and localization file updates
- [ ] Have tested against the 5 core themes to ensure consistency between them.

#### Device Information
This PR was tested on: 

iPhone XR, iOS 15.2.1
Google Nexus 6, Android 7.1.1

#### Release Note
```release-note
Added .m4a audio file preview support via the video player.
```

### CODE REVIEW

**Comment by Willyfrog** [comment]
@silentyak seems that the tests are failing, can you take a look and see how your code is affecting them?

**Review by larkox — APPROVED** [review]
If this is working as described, the changes LGTM.

I wonder if UX has any consideration on how this is being shown (black screen with only audio).
@silentyak Would be possible to share a small video of this working on a device? (Emulator is ok)

**Review by anurag6713 — APPROVED** [review]

**Comment by larkox** [comment]
The test failure seems to be a flaky test due to the daylight saving times. CC @enahum

**Comment by enahum** [comment]
I would also raise the question if it does make sense to add other supported audio files

**Comment by Willyfrog** [comment]
> I would also raise the question if it does make sense to add other supported audio files

Adding eric for review of that question.

**Comment by silentyak** [comment]
> @silentyak Would be possible to share a small video of this working on a device? (Emulator is ok)

I don't have the right setup on this machine to push an updated client from my branch, but here's a screenshot:
IMG_C508B628BE6A-1

The play button will change to a pause button when the audio is played back. You can test this yourself quickly by renaming any `.m4a` file to `.mp4`, then attaching it to a channel, then trying to play it.

The use case is for a user quickly attaching an audio recording since they are in a hurry or can't type since it will take longer. The default audio recorders on iOS and Android both record to `.m4a` by default, and the audio recording can be shared/sent to the Mattermost Mobile app, but no one can play it (without downloading) since there is no audio file preview support for .m4a (nor .mp3 for that matter). Adding this change would at least add preview support the default audio recording format for iOS and Android.

**Comment by larkox** [comment]
Thanks @silentyak . It seems really useful indeed. Let's wait for the greenlight from product, but probably it is fine.
In the meanwhile, I added a QA person to help with testing the feature.

**Comment by jgilliam17** [comment]
Thank you @silentyak 
Just a quick follow up on this
 >The play button will change to a pause button when the audio is played back. You can test this yourself quickly by renaming any .m4a file to .mp4, then attaching it to a channel, then trying to play it.

Is this renaming step going to be necessary going forward?

**Comment by silentyak** [comment]
> Is this renaming step going to be necessary going forward?

No, this was only to test it on the current App Store release how this new feature will behave. Once this feature has been merged in, `.m4a` audio files will now be able to be previewed.

**Comment by jgilliam17** [comment]
The iOS app build here (see links above) doesn't have the ability to preview and play `.m4a` files, only download.  I haven't checked Android yet. Will post Android results soon.

**Comment by silentyak** [comment]
> The iOS app build here (see links above) doesn't have the ability to preview and play `.m4a` files, only download. I haven't checked Android yet. Will post Android results soon.

Not sure what to say, it definitely works on my test build with my change (a very simple change).

**Comment by enahum** [comment]
@jgilliam17 it may very well be cause of https://mattermost.atlassian.net/browse/SEC-839

**Comment by esethna** [comment]
@silentyak thanks for the PR, seems super useful. Adding @matthewbirtch for UX review - I'm wondering if we want a different UX for audio only files, but as a first step I would be okay with taking this as is assuming it's tested and working as described.

@enahum when you say:

> I would also raise the question if it does make sense to add other supported audio files

Are you saying there are other formats can we make previewable with minor code changes like this?

**Comment by enahum** [comment]
I'm not sure, but I believe mp3 is also supported, not sure what other audio formats are.

**Review by matthewbirtch — CHANGES_REQUESTED** [review]
Nice addition @silentyak. When playing audio files, can we make it so the UI doesn't disappear like it does for video? I think that should help. Right now the screen goes completely blank and hiding the UI isn't necessary with audio.

And it would be great if we could also support mp3 audio files. We might also consider AAC or AIFF files, but MP3 would certainly most popular to support.

**Comment by silentyak** [comment]
> Nice addition @silentyak. When playing audio files, can we make it so the UI doesn't disappear like it does for video? I think that should help. Right now the screen goes completely blank and hiding the UI isn't necessary with audio.

I believe this is a misunderstanding of this 'feature' that was added. Take a look at the actual code change (literally a few characters), it's just leveraging the video player to play .m4a audio files, which have the same container format as video files (.mp4, .m4v). The video player doesn't care that it's just an audio file, it treats it as an mp4 container with no video track . I didn't hide or do anything at all, this is your default video player functionality. 

This 'feature' is just that (mime-type mapping), the use case is described here: https://github.com/mattermost/mattermost-mobile/pull/6051#issuecomment-1079110814

To support other audio file types,  a whole new audio-player component that has to be written (probably hundreds of lines, and a week or so of full-time effort, this is out of my arena currently), which you don't have support for at all currently of course. 

At least with this addition (see the link for the use case), it will be usable for people to send memos via the default mobile audio recorders on their phones and not inconveniencing the recipients by requiring them to download it first somewhere (see similar feature on WhatsApp or your favorite chat app, or iMessage etc), then go out of the app to play it.

**Comment by matthewbirtch** [comment]
> > Nice addition @silentyak. When playing audio files, can we make it so the UI doesn't disappear like it does for video? I think that should help. Right now the screen goes completely blank and hiding the UI isn't necessary with audio.
> 
> I believe this is a misunderstanding of this 'feature' that was added. Take a look at the actual code change (literally a few characters), it's just leveraging the video player to play .m4a audio files, which have the same container format as video files (.mp4, .m4v). The video player doesn't care that it's just an audio file, it treats it as an mp4 container with no video track . I didn't hide or do anything at all, this is your default video player functionality.
> 
> This 'feature' is just that (mime-type mapping), the use case is described here: [#6051 (comment)](https://github.com/mattermost/mattermost-mobile/pull/6051#issuecomment-1079110814)
> 
> To support other audio file types, a whole new audio-player component that has to be written (probably hundreds of lines, and a week or so of full-time effort, this is out of my arena currently), which you don't have support for at all currently of course.
> 
> At least with this addition (see the link for the use case), it will be usable for people to send memos via the default mobile audio recorders on their phones and not inconveniencing the recipients by requiring them to download it first somewhere (see similar feature on WhatsApp or your favorite chat app, or iMessage etc), then go out of the app to play it.

Ok, I think this is a product decision then @esethna. Eric, are you comfortable merging this PR with the above in mind?

**Comment by esethna** [comment]
@silentyak got it, thanks for the explanation. Let's merge it as is since it solves a common use case (albeit the UX is not optimized but that can be done in a separate future effort with appropriate designs) cc// @matthewbirtch

**Review by matthewbirtch — APPROVED** [review]

**Comment by jgilliam17** [comment]
I am not able to verify the change on the [test apps](https://github.com/mattermost/mattermost-mobile/pull/6051#issuecomment-1093197384) tested on both Android and iOS and .m4a files are not playing, only download option is available.
Elias mentioned [here](https://github.com/mattermost/mattermost-mobile/pull/6051#issuecomment-1082351131) that this inability to play the file may be caused by another issue. 
@esethna I suggest QA waits for that fix to be merged before testing and approving this PR. Thoughts?

**Comment by esethna** [comment]
Works for me @jgilliam17

**Comment by amyblais** [comment]
@enahum This needs a manual cherry-pick...

**Pull request merged**
