### PR TITLE
Fix Vietnamese language selection

### PR DESCRIPTION
**Pull request by ctlaltdieliet**
#### Summary
When selecting Vietnamese as languagem Ukrainian is shown.
Copy-paste error when adding Vietnamese
#### Ticket Link
https://community.mattermost.com/core/pl/nytjam45tfdsmyg4xyr4hnb6kw
https://mattermost.atlassian.net/browse/MM-56470
#### Checklist
- [ ] Added or updated unit tests (required for all new features)
- [ ] Has UI changes
- [x ] Includes text changes and localization file updates
- [ ] Have tested against the 5 core themes to ensure consistency between them.

#### Release Note
```release-note
NONE
```

### CODE REVIEW

**Review by paul-pham-157 — APPROVED** [review]

**Review by enahum — APPROVED** [review]

**Comment by paul-pham-157** [comment]
Hello @lindy65 please review this PR

**Comment by lindy65** [comment]
Hi @paul-pham-157 - I was out for the holidays and will review this PR today.

**Review by lindy65 — APPROVED** [review]
Thanks @ctlaltdieliet - this is fixed, looks good to me 👍

**Pull request merged**
