### PR TITLE
Style views for SelectServer, Login, SelectTeam, & ChannelsList

### PR DESCRIPTION
**Pull request by thomchop**

### CODE REVIEW

**Comment by thomchop** [comment]
selectserver-ios
login-ios
selectteam-ios
channelslist-ios

**Comment by thomchop** [comment]
@hmhealey Before we merge this, I'd like to display the team name in the channels list. Like we will eventually do at the top of the left sidebar.

**Comment by hmhealey** [comment]
K I'll just mark it WIP for now then so it doesn't get accidentally merged

**Comment by thomchop** [comment]
Good to know. I was wondering what the convention was. I'll use this label in the future. I should probably take a look at the labels being used in the other repos.

**Comment by hmhealey** [comment]
Cool. After that, we usually mark it Needs Dev Review (or Needs PM Review if it's a new feature, but we don't need that in this repo yet). Then once the review is done, we either merge it if the build is also complete or we mark it Ready to Merge if it's waiting on the build.

**Pull request merged**
