### PR TITLE
Update mattermost-redux version to latest

### PR DESCRIPTION
**Pull request by nevyangelova**
#### Summary

As part of https://mattermost.atlassian.net/browse/MM-14661 we need to update the mattermost-redux version.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-14661

#### Checklist

- [ x] All new/modified APIs include changes to [mattermost-redux](https://github.com/mattermost/mattermost-redux) (please link)

### CODE REVIEW

**Comment by enahum** [comment]
What is the difference with https://github.com/mattermost/mattermost-mobile/pull/3947

**Comment by nevyangelova** [comment]
@enahum we’ve updated the version of redux again since the PR you referred and It includes adding mattermost:// to the deep linking urls.

**Comment by enahum** [comment]
@amyblais why the change to 1.30 instead of 1.29? can you please clarify?

**Comment by amyblais** [comment]
@enahum It didn't have a fix version assigned to it so I added it to v1.30 as the redux PR was merged to master https://github.com/mattermost/mattermost-redux/pull/1055.

This seemed to be a feature ticket rather than a bug.

**Comment by enahum** [comment]
@nevyangelova can you please resolve the conflicts?

**Pull request merged**
