### PR TITLE
[MM-18182] Upgrade redux in mobile

### PR DESCRIPTION
**Pull request by devinbinnie**
#### Summary
Upgrading redux in mobile to support changes added in #919

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-18182

#### Checklist
- [x] All new/modified APIs include changes to [mattermost-redux] https://github.com/mattermost/mattermost-redux/pull/919

#### Device Information
This PR was tested on: iOS Simulator, iPhone XS iOS 12.4

### CODE REVIEW

**Comment by devinbinnie** [comment]
@enahum should this go in for v1.23?

**Comment by enahum** [comment]
@devinbinnie I thought this was for 1.23, but it is not a regression, so is fine not to cherry-pick.

The ticket does not have a fix version.

**Comment by enahum** [comment]
And also this contains for some reason localization changes, probably cause of a PR that went in that made some changes there. So I would avoid a full cherry-pick anyway

**Comment by devinbinnie** [comment]
> And also this contains for some reason localization changes, probably cause of a PR that went in that made some changes there. So I would avoid a full cherry-pick anyway

@enahum It's just a reordering, which I assume is supposed to happen. Not sure how it made it in out of order in the first place...

**Comment by enahum** [comment]
Yeah that could happen if two PR's with localizations where submitted and merged at different times, is totally fine.

**Pull request merged**
