### PR TITLE
MM-9801 Upgrade mattermost-redux to latest and add postsInThread to middleware

### PR DESCRIPTION
**Pull request by jwilander**
#### Summary
Upgrade mattermost-redux to latest and add postsInThread to middleware.

@jespino this includes the recently merged advanced permissions changes, can you confirm if that should be an issue or not?

### CODE REVIEW

**Comment by koxen** [comment]
after I merge my app crashes on start
                                                   com.facebook.react.common.JavascriptException: Selector creators expect all input-selectors to be functions, instead received the following types: [function, undefined], stack:

**Comment by koxen** [comment]
I cleaned node_modules, yarn cache, rebuilt and it still crashes

**Comment by jwilander** [comment]
That's annoying. I'll take a look later, got a million other things on my plate right now

**Comment by jespino** [comment]
That looks like a problem with cyclic dependency between selectors.

**Comment by jespino** [comment]
It can be related to this PR #439, or have the same problem

**Comment by koxen** [comment]
the stacktrace is useless though :(

```
Selector creators expect all input-selectors to be functions, instead received the following types: [function, undefined]
getDependencies
    C:\Users\koxen\IdeaProjects\mattermost-mobile2\node_modules\reselect\lib\index.js:53:20
<unknown>
    C:\Users\koxen\IdeaProjects\mattermost-mobile2\node_modules\reselect\lib\index.js:71:39
<unknown>
    C:\Users\koxen\IdeaProjects\mattermost-mobile2\app\screens\more_channels\index.js:20:25
loadModuleImplementation
    C:\Users\koxen\IdeaProjects\mattermost-mobile2\node_modules\metro\src\lib\polyfills\require.js:212:12
guardedLoadModule
    C:\Users\koxen\IdeaProjects\mattermost-mobile2\node_modules\metro\src\lib\polyfills\require.js:146:36
_require
    C:\Users\koxen\IdeaProjects\mattermost-mobile2\node_modules\metro\src\lib\polyfills\require.js:130:20
<unknown>
    C:\Users\koxen\IdeaProjects\mattermost-mobile2\app\screens\index.js:30
loadModuleImplementation
    C:\Users\koxen\IdeaProjects\mattermost-mobile2\node_modules\metro\src\lib\polyfills\require.js:212:12
guardedLoadModule
    C:\Users\koxen\IdeaProjects\mattermost-mobile2\node_modules\metro\src\lib\polyfills\require.js:146:36
_require
    C:\Users\koxen\IdeaProjects\mattermost-mobile2\node_modules\metro\src\lib\polyfills\require.js:130:20
<unknown>
    C:\Users\koxen\IdeaProjects\mattermost-mobile2\app\mattermost.js:51
loadModuleImplementation
    C:\Users\koxen\IdeaProjects\mattermost-mobile2\node_modules\metro\src\lib\polyfills\require.js:212:12
guardedLoadModule
    C:\Users\koxen\IdeaProjects\mattermost-mobile2\node_modules\metro\src\lib\polyfills\require.js:146:36
_require
    C:\Users\koxen\IdeaProjects\mattermost-mobile2\node_modules\metro\src\lib\polyfills\require.js:130:20
<unknown>
    C:\Users\koxen\IdeaProjects\mattermost-mobile2\index.js:7
loadModuleImplementation
    C:\Users\koxen\IdeaProjects\mattermost-mobile2\node_modules\metro\src\lib\polyfills\require.js:212:12
guardedLoadModule
    C:\Users\koxen\IdeaProjects\mattermost-mobile2\node_modules\metro\src\lib\polyfills\require.js:139:45
_require
    C:\Users\koxen\IdeaProjects\mattermost-mobile2\node_modules\metro\src\lib\polyfills\require.js:130:20
global code
    
```

**Comment by koxen** [comment]
actually it's not useless hm

it points to this piece of code in mobile app, which references the recently "fixed" selectors...

```
const joinableChannels = createSelector(
    getChannelsInCurrentTeam,
    getMyChannelMemberships,
    (channels, myMembers) => {
        return channels.filter((c) => {
            return (!myMembers[c.id] && c.type === General.OPEN_CHANNEL);
        });
    }
);
```

**Comment by koxen** [comment]
Here's a diff that fixes the new selectors...

```
diff --git a/app/components/post_body/index.js b/app/components/post_body/index.js
index bcb11f8d..a0accea2 100644
--- a/app/components/post_body/index.js
+++ b/app/components/post_body/index.js
@@ -11,8 +11,8 @@ import {
 } from 'mattermost-redux/constants';
 import {
     getCurrentChannel,
-    getMyCurrentChannelMembership,
 } from 'mattermost-redux/selectors/entities/channels';
+import {getMyCurrentChannelMembership} from 'mattermost-redux/selectors/entities/common';
 import {getPost} from 'mattermost-redux/selectors/entities/posts';
 import {getTheme} from 'mattermost-redux/selectors/entities/preferences';
 import {getCurrentTeamMembership} from 'mattermost-redux/selectors/entities/teams';
diff --git a/app/screens/channel/channel_post_list/index.js b/app/screens/channel/channel_post_list/index.js
index 4854f7f4..e1e1a456 100644
--- a/app/screens/channel/channel_post_list/index.js
+++ b/app/screens/channel/channel_post_list/index.js
@@ -6,7 +6,8 @@ import {connect} from 'react-redux';
 
 import {selectPost} from 'mattermost-redux/actions/posts';
 import {getPostIdsInCurrentChannel} from 'mattermost-redux/selectors/entities/posts';
-import {getCurrentChannelId, getMyCurrentChannelMembership} from 'mattermost-redux/selectors/entities/channels';
+import {getCurrentChannelId} from 'mattermost-redux/selectors/entities/channels';
+import {getMyCurrentChannelMembership} from 'mattermost-redux/selectors/entities/common';
 import {getCurrentUserId} from 'mattermost-redux/selectors/entities/users';
 import {getTheme} from 'mattermost-redux/selectors/entities/preferences';
 
diff --git a/app/screens/more_channels/index.js b/app/screens/more_channels/index.js
index 27b6d45c..88c851f0 100644
--- a/app/screens/more_channels/index.js
+++ b/app/screens/more_channels/index.js
@@ -7,7 +7,8 @@ import {createSelector} from 'reselect';
 
 import {General} from 'mattermost-redux/constants';
 import {getChannels, joinChannel, searchChannels} from 'mattermost-redux/actions/channels';
-import {getChannelsInCurrentTeam, getMyChannelMemberships} from 'mattermost-redux/selectors/entities/channels';
+import {getMyChannelMemberships} from 'mattermost-redux/selectors/entities/common';
+import {getChannelsInCurrentTeam} from 'mattermost-redux/selectors/entities/channels';
 import {getCurrentUserRoles} from 'mattermost-redux/selectors/entities/users';
 import {showCreateOption} from 'mattermost-redux/utils/channel_utils';
 import {isAdmin, isSystemAdmin} from 'mattermost-redux/utils/user_utils';
diff --git a/app/screens/permalink/index.js b/app/screens/permalink/index.js
index 6c7035c3..105543da 100644
--- a/app/screens/permalink/index.js
+++ b/app/screens/permalink/index.js
@@ -6,7 +6,8 @@ import {connect} from 'react-redux';
 
 import {getChannel as getChannelAction, joinChannel, markChannelAsRead, markChannelAsViewed} from 'mattermost-redux/actions/channels';
 import {getPostsAfter, getPostsBefore, getPostThread, selectPost} from 'mattermost-redux/actions/posts';
-import {getMyChannelMemberships, makeGetChannel} from 'mattermost-redux/selectors/entities/channels';
+import {makeGetChannel} from 'mattermost-redux/selectors/entities/general';
+import {getMyChannelMemberships} from 'mattermost-redux/selectors/entities/common';
 import {makeGetPostIdsAroundPost, getPost} from 'mattermost-redux/selectors/entities/posts';
 import {getTheme} from 'mattermost-redux/selectors/entities/preferences';
 import {getCurrentTeamId} from 'mattermost-redux/selectors/entities/teams';
diff --git a/app/screens/thread/index.js b/app/screens/thread/index.js
index 00dd162d..9aa128fd 100644
--- a/app/screens/thread/index.js
+++ b/app/screens/thread/index.js
@@ -7,7 +7,8 @@ import {connect} from 'react-redux';
 import {getTheme} from 'mattermost-redux/selectors/entities/preferences';
 
 import {selectPost} from 'mattermost-redux/actions/posts';
-import {getMyCurrentChannelMembership, makeGetChannel} from 'mattermost-redux/selectors/entities/channels';
+import {makeGetChannel} from 'mattermost-redux/selectors/entities/channels';
+import {getMyCurrentChannelMembership} from 'mattermost-redux/selectors/entities/common';
 import {makeGetPostIdsForThread} from 'mattermost-redux/selectors/entities/posts';
 
 import Thread from './thread';
diff --git a/app/utils/sentry/index.js b/app/utils/sentry/index.js
index 22393881..21b6e93e 100644
--- a/app/utils/sentry/index.js
+++ b/app/utils/sentry/index.js
@@ -9,7 +9,8 @@ import Config from 'assets/config';
 import {getConfig} from 'mattermost-redux/selectors/entities/general';
 import {getCurrentUser} from 'mattermost-redux/selectors/entities/users';
 import {getCurrentTeam, getCurrentTeamMembership} from 'mattermost-redux/selectors/entities/teams';
-import {getCurrentChannel, getMyCurrentChannelMembership} from 'mattermost-redux/selectors/entities/channels';
+import {getCurrentChannel} from 'mattermost-redux/selectors/entities/channels';
+import {getMyCurrentChannelMembership} from 'mattermost-redux/selectors/entities/common';
 
 export const LOGGER_JAVASCRIPT = 'javascript';
 export const LOGGER_JAVASCRIPT_WARNING = 'javascript_warning';
```

now it crashes because of new permission changes...I'll continue working on a fix as it's blocking some of my other work

**Comment by jespino** [comment]
The problem is a cyclic dependency between selectors/entities/users.js and selectors/entities/channels.js, the solution, in other cases has been move the dependent selectors to selectors/entities/common.js. I'm not sure if it is possible in this case.

**Comment by koxen** [comment]
@jespino don't worry it's fine now just imports needed update, now I am working to update it to permissions api changes

**Comment by koxen** [comment]
Fixed diff, the app now fully works:

```diff
diff --git a/app/components/channel_drawer/channels_list/list/index.js b/app/components/channel_drawer/channels_list/list/index.js
index 473b4549..989f2046 100644
--- a/app/components/channel_drawer/channels_list/list/index.js
+++ b/app/components/channel_drawer/channels_list/list/index.js
@@ -28,7 +28,7 @@ function mapStateToProps(state) {
     const directChannelIds = getSortedDirectChannelIds(state);
 
     return {
-        canCreatePrivateChannels: showCreateOption(config, license, General.PRIVATE_CHANNEL, isAdmin(roles), isSystemAdmin(roles)),
+        canCreatePrivateChannels: showCreateOption(state, config, license, General.PRIVATE_CHANNEL, isAdmin(roles), isSystemAdmin(roles)),
         unreadChannelIds,
         favoriteChannelIds,
         publicChannelIds,
diff --git a/app/components/post_body/index.js b/app/components/post_body/index.js
index bcb11f8d..0fc77e00 100644
--- a/app/components/post_body/index.js
+++ b/app/components/post_body/index.js
@@ -11,14 +11,14 @@ import {
 } from 'mattermost-redux/constants';
 import {
     getCurrentChannel,
-    getMyCurrentChannelMembership,
 } from 'mattermost-redux/selectors/entities/channels';
+import {getMyCurrentChannelMembership} from 'mattermost-redux/selectors/entities/common';
 import {getPost} from 'mattermost-redux/selectors/entities/posts';
 import {getTheme} from 'mattermost-redux/selectors/entities/preferences';
 import {getCurrentTeamMembership} from 'mattermost-redux/selectors/entities/teams';
 import {getCurrentUser} from 'mattermost-redux/selectors/entities/users';
 
-import {canManageMembers} from 'mattermost-redux/utils/channel_utils';
+import {canManageMembersOldPermissions} from 'mattermost-redux/utils/channel_utils';
 import {
     isEdited,
     isPostEphemeral,
@@ -46,7 +46,7 @@ function mapStateToProps(state, ownProps) {
     const teamMember = getCurrentTeamMembership(state);
     const channelMember = getMyCurrentChannelMembership(state);
     const {config, license} = state.entities.general;
-    const isUserCanManageMembers = canManageMembers(channel, user, teamMember, channelMember, config, license);
+    const isUserCanManageMembers = canManageMembersOldPermissions(channel, user, teamMember, channelMember, config, license);
     const isEphemeralPost = isPostEphemeral(post);
 
     let isPostAddChannelMember = false;
diff --git a/app/initial_state.js b/app/initial_state.js
index 52097725..c2d4519c 100644
--- a/app/initial_state.js
+++ b/app/initial_state.js
@@ -50,6 +50,10 @@ const state = {
             recent: [],
         },
         typing: {},
+        roles: {
+            roles: {},
+            pending: new Set(),
+        },
     },
     errors: [],
     requests: {
diff --git a/app/screens/channel/channel_post_list/index.js b/app/screens/channel/channel_post_list/index.js
index 4854f7f4..e1e1a456 100644
--- a/app/screens/channel/channel_post_list/index.js
+++ b/app/screens/channel/channel_post_list/index.js
@@ -6,7 +6,8 @@ import {connect} from 'react-redux';
 
 import {selectPost} from 'mattermost-redux/actions/posts';
 import {getPostIdsInCurrentChannel} from 'mattermost-redux/selectors/entities/posts';
-import {getCurrentChannelId, getMyCurrentChannelMembership} from 'mattermost-redux/selectors/entities/channels';
+import {getCurrentChannelId} from 'mattermost-redux/selectors/entities/channels';
+import {getMyCurrentChannelMembership} from 'mattermost-redux/selectors/entities/common';
 import {getCurrentUserId} from 'mattermost-redux/selectors/entities/users';
 import {getTheme} from 'mattermost-redux/selectors/entities/preferences';
 
diff --git a/app/screens/more_channels/index.js b/app/screens/more_channels/index.js
index 27b6d45c..af61871e 100644
--- a/app/screens/more_channels/index.js
+++ b/app/screens/more_channels/index.js
@@ -7,7 +7,8 @@ import {createSelector} from 'reselect';
 
 import {General} from 'mattermost-redux/constants';
 import {getChannels, joinChannel, searchChannels} from 'mattermost-redux/actions/channels';
-import {getChannelsInCurrentTeam, getMyChannelMemberships} from 'mattermost-redux/selectors/entities/channels';
+import {getMyChannelMemberships} from 'mattermost-redux/selectors/entities/common';
+import {getChannelsInCurrentTeam} from 'mattermost-redux/selectors/entities/channels';
 import {getCurrentUserRoles} from 'mattermost-redux/selectors/entities/users';
 import {showCreateOption} from 'mattermost-redux/utils/channel_utils';
 import {isAdmin, isSystemAdmin} from 'mattermost-redux/utils/user_utils';
@@ -36,7 +37,7 @@ function mapStateToProps(state) {
     const channels = joinableChannels(state);
 
     return {
-        canCreateChannels: showCreateOption(config, license, General.OPEN_CHANNEL, isAdmin(roles), isSystemAdmin(roles)),
+        canCreateChannels: showCreateOption(state, config, license, General.OPEN_CHANNEL, isAdmin(roles), isSystemAdmin(roles)),
         currentUserId,
         currentTeamId,
         channels,
diff --git a/app/screens/permalink/index.js b/app/screens/permalink/index.js
index 6c7035c3..105543da 100644
--- a/app/screens/permalink/index.js
+++ b/app/screens/permalink/index.js
@@ -6,7 +6,8 @@ import {connect} from 'react-redux';
 
 import {getChannel as getChannelAction, joinChannel, markChannelAsRead, markChannelAsViewed} from 'mattermost-redux/actions/channels';
 import {getPostsAfter, getPostsBefore, getPostThread, selectPost} from 'mattermost-redux/actions/posts';
-import {getMyChannelMemberships, makeGetChannel} from 'mattermost-redux/selectors/entities/channels';
+import {makeGetChannel} from 'mattermost-redux/selectors/entities/general';
+import {getMyChannelMemberships} from 'mattermost-redux/selectors/entities/common';
 import {makeGetPostIdsAroundPost, getPost} from 'mattermost-redux/selectors/entities/posts';
 import {getTheme} from 'mattermost-redux/selectors/entities/preferences';
 import {getCurrentTeamId} from 'mattermost-redux/selectors/entities/teams';
diff --git a/app/screens/thread/index.js b/app/screens/thread/index.js
index 00dd162d..9aa128fd 100644
--- a/app/screens/thread/index.js
+++ b/app/screens/thread/index.js
@@ -7,7 +7,8 @@ import {connect} from 'react-redux';
 import {getTheme} from 'mattermost-redux/selectors/entities/preferences';
 
 import {selectPost} from 'mattermost-redux/actions/posts';
-import {getMyCurrentChannelMembership, makeGetChannel} from 'mattermost-redux/selectors/entities/channels';
+import {makeGetChannel} from 'mattermost-redux/selectors/entities/channels';
+import {getMyCurrentChannelMembership} from 'mattermost-redux/selectors/entities/common';
 import {makeGetPostIdsForThread} from 'mattermost-redux/selectors/entities/posts';
 
 import Thread from './thread';
diff --git a/app/utils/sentry/index.js b/app/utils/sentry/index.js
index 22393881..21b6e93e 100644
--- a/app/utils/sentry/index.js
+++ b/app/utils/sentry/index.js
@@ -9,7 +9,8 @@ import Config from 'assets/config';
 import {getConfig} from 'mattermost-redux/selectors/entities/general';
 import {getCurrentUser} from 'mattermost-redux/selectors/entities/users';
 import {getCurrentTeam, getCurrentTeamMembership} from 'mattermost-redux/selectors/entities/teams';
-import {getCurrentChannel, getMyCurrentChannelMembership} from 'mattermost-redux/selectors/entities/channels';
+import {getCurrentChannel} from 'mattermost-redux/selectors/entities/channels';
+import {getMyCurrentChannelMembership} from 'mattermost-redux/selectors/entities/common';
 
 export const LOGGER_JAVASCRIPT = 'javascript';
 export const LOGGER_JAVASCRIPT_WARNING = 'javascript_warning';
```

**Comment by jwilander** [comment]
@koxen feel free to make a new PR with your changes

**Pull request closed without merging**
