### PR TITLE
Manual cherry pick of #5404

### PR DESCRIPTION
**Pull request by josephbaylon**
Cherry pick of #5404 on release-1.44.

/cc @enahum

### CODE REVIEW

**Comment by enahum** [comment]
@josephbaylon it looks like no file changes are included in this PR

**Comment by josephbaylon** [comment]
@enahum @amyblais Looks like the fix is already part of release-1.44 branch. Closing this PR.

**Comment by amyblais** [comment]
Ah I'm sorry, makes sense, v1.44 release branch was just cut today based off master.

**Pull request closed without merging**
