### PR TITLE
MM-22090 Fix iOS photo/camera denied permissions

### PR DESCRIPTION
**Pull request by enahum**
#### Summary
Shows the Open settings dialog on iOS when trying to access the camera/photos and the permission where previously denied

#### Ticket Links
https://mattermost.atlassian.net/browse/MM-22090

### CODE REVIEW

**Comment by chuttam** [comment]
Is there no similar issue with Android too?

**Comment by enahum** [comment]
Nope, Android was already handled from the native side

**Comment by enahum** [comment]
Feel free to create a ticket for this if you want. Not really needed as it is a missing part of the newly added post draft as it was supposed to be already there.

As for the unit tests, I guess we can add them tomorrow.

**Comment by enahum** [comment]
@josephbaylon, I believe you found a bug in the actual OS. Can you try again but ensure that you have photos already in your device?

**Comment by enahum** [comment]
As in without the permission assign the OS should not even let you browse the image library and it does. Interesting find, not our doing.

**Comment by enahum** [comment]
@josephbaylon unit tests added.

I've also renamed a few files so they match the convention.

**Comment by enahum** [comment]
@josephbaylon this should be fixed. building the PR

**Pull request merged**
