### PR TITLE
Add Swipe up&down on TeamList to change teams

### PR DESCRIPTION
**Pull request by chief-nerd**
#### Summary
Add Swipe up and down on the Team List to easily change teams

#### Checklist
- [ ] Added or updated unit tests (required for all new features)
- [ ] Has UI changes
- [ ] Includes text changes and localization file updates
- [x] Have tested against the 5 core themes to ensure consistency between them.

#### Device Information
This PR was tested on: Android Pixel 6, API 33

#### Release Note
```release-note
Added a swipe gesture to the team list to easily change teams with an up & down swipe
```

### CODE REVIEW

**Comment by larkox** [comment]
Adding UX and PM review before code review, to make sure we want this feature in.

In the meantime... Does this have any conflict with a long list of teams? Keep in mind some people may have many teams (>10), and the list should be able to scroll. So the swipe may conflict with the scroll.

**Comment by itao** [comment]
@chief-nerd Would you mind attaching a demo video, especially in the case with scroll as @larkox mentioned?

**Comment by enahum** [comment]
Imho this will conflict with future plans to be able to sort the teams with a drag and drop gesture to match the web application behavior

**Comment by chief-nerd** [comment]
@enahum ... imho both are possible:

Swipe = to quickly switch through teams
Long press + drag&drop = reorder ... similar how iOS & Android do the reordering of apps.

**Comment by asaadmahmood** [comment]
A demo video will help, I'm not sure how to test this otherwise. @chief-nerd

**Pull request closed without merging**
