### PR TITLE
just a test

### PR DESCRIPTION
**Pull request by cpanato**
do not merge

just a test for mattermod

### CODE REVIEW

**Comment by cpanato** [comment]
`Build Mobile Apps` label detected. Will generate the app if build succeeds (checks pass and no conflicts with base branch).

**Comment by cpanato** [comment]
[test link](itms-services://?action=download-manifest&url=https://releases.mattermost.com/mattermost-mobile-pr/PR-2251/PR-2251.plist)

**Comment by cpanato** [comment]
[itms-services://?action=download-manifest&url=https://releases.mattermost.com/mattermost-mobile-pr/PR-2251/PR-2251.plist](itms-services://?action=download-manifest&url=https://releases.mattermost.com/mattermost-mobile-pr/PR-2251/PR-2251.plist)

**Comment by mkraft** [comment]
[itms-services://?action=download-manifest&url=https://releases.mattermost.com/mattermost-mobile-pr/PR-2251/PR-2251.plist](itms-services://?action=download-manifest&url=https://releases.mattermost.com/mattermost-mobile-pr/PR-2251/PR-2251.plist)

**Comment by mkraft** [comment]
[iOS build link](itms-services://?action=download-manifest&url=https://releases.mattermost.com/mattermost-mobile-pr/PR-2251/PR-2251.plist)

**Comment by mkraft** [comment]
https://tinyurl.com/y7qyq3bh

**Pull request closed without merging**
