### PR TITLE
[MM-18434] Patch react-native's splitLayoutProps

### PR DESCRIPTION
**Pull request by migbot**
#### Summary
Without `transform` in `OUTER_PROPS`, the refresh control component would not include `transform: {scaleY: -1}` in its style and so pulling down, rather than up, on a scroll view would trigger a refresh.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-18434

#### Device Information
This PR was tested on:
* Android 8.0 emulator

### CODE REVIEW

**Comment by enahum** [comment]
Test failing

**Comment by enahum** [comment]
@migbot I think you need to add the circleCI config.yml file to the feature branch..

**Comment by hmhealey** [comment]
Any thoughts on trying to push this change upstream?

Also, while I'm still not a fan of patching libraries, I like that new method of doing the patches since it looks more reliable than just grepping and such. We might want to look at replacing some of the other patches with that

**Comment by hmhealey** [comment]
Ah, I didn't realize this is just a temporary patch. Truly temporary patches are definitely the best ones 😄

**Pull request merged**
