### PR TITLE
Fix upload permissions and centralize download permissions

### PR DESCRIPTION
**Pull request by larkox**
#### Summary
The logic about the checking if files can be uploaded was wrong. I fixed it and added some tests for it.

I also piggybacked some changes about the download logic, to centralize it, and added also tests.

#### Ticket Link
Fix https://mattermost.atlassian.net/browse/MM-50448

#### Release Note
```release-note
Fix bug where "enableMobileUploadFiles" setting was not working correctly.
```

### CODE REVIEW

**Review by enahum — APPROVED** [review]
should be cherrypicked to 2.1

**Comment by larkox** [comment]
@furqanmlk Adding you as one of the QA from the core teams. If you find someone else should be testing this, feel free to reassign.

**Comment by enahum** [comment]
We should be cutting 2.1 not later than Wednesday

**Comment by enahum** [comment]
@furqanmlk please do prioritize this PR as I need to merge it ASAP!!

**Review by furqanmlk — COMMENTED** [review]
@larkox 
I am still able to upload and download files when settings are 
`"EnableMobileUpload": false,`
` "EnableMobileDownload": false,`
Please see the attached recording.
am I missing something? 

https://user-images.githubusercontent.com/6909890/218847118-2ca82798-eb9d-4a21-bc60-24ba8e7a52f2.mp4

**Comment by enahum** [comment]
@furqanmlk have you made the changes to the config file directly instead of using the admin console? and if so, once you made the change, did you restarted the server? and if so, have you restarted the app (just in case)? if you use the browser to get the client config what values do you get for those settings?

**Comment by furqanmlk** [comment]
> @furqanmlk have you made the changes to the config file directly instead of using the admin console? and if so, once you made the change, did you restarted the server? and if so, have you restarted the app (just in case)? if you use the browser to get the client config what values do you get for those settings?

@enahum 
1. Changed following config.json settings 
`"EnableMobileUpload": false,`
` "EnableMobileDownload": false`
2. Restarted server `make restart-server`
3. Close the Mobile app and relaunched
4. Verified values are still `false` at `http://localhost:8065/api/v4/config`

image

**Comment by enahum** [comment]
@furqanmlk the results of the `http://localhost:8065/api/v4/config/client?format=old` endpoint

**Comment by furqanmlk** [comment]
> http://localhost:8065/api/v4/config/client?format=old

image

There is no closing bracket

**Comment by enahum** [comment]
> There is no closing bracket

Oh there is, and there are a bunch more values there

**Comment by furqanmlk** [comment]
> > There is no closing bracket
> 
> Oh there is, and there are a bunch more values there

Sorry there was another option to view source
`{
   "AboutLink": "https://docs.mattermost.com/about/product.html",
   "AndroidAppDownloadLink": "https://mattermost.com/mattermost-android-app/",
   "AndroidLatestVersion": "",
   "AndroidMinVersion": "",
   "AppDownloadLink": "https://mattermost.com/download/#mattermostApps",
   "AsymmetricSigningPublicKey": "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEgHSlZxPm5K2ZHY2ueOPhY0t5xlhxFZSyN9o/7wVby4RgJKnMRRu821pOzRMMEOHFWwV0pKFdyYFTSpE18ofYUQ==",
   "BuildBoards": "true",
   "BuildDate": "n/a",
   "BuildEnterpriseReady": "true",
   "BuildHash": "079449e30af683c5c8115b91e53661372b86da30",
   "BuildHashBoards": "08ce9a753d77eca18ae385ac09dceb246f955254",
   "BuildHashEnterprise": "3e48c65107e6b77d422dc2f67e846ecb8d2ee665",
   "BuildHashPlaybooks": "none",
   "BuildNumber": "dev",
   "CWSURL": "",
   "CustomBrandText": "",
   "CustomDescriptionText": "",
   "DefaultClientLocale": "en",
   "DiagnosticId": "j9wd6fn14py58egkk9kbq5qyja",
   "DiagnosticsEnabled": "true",
   "EmailLoginButtonBorderColor": "#2389D7",
   "EmailLoginButtonColor": "#0000",
   "EmailLoginButtonTextColor": "#2389D7",
   "EnableAskCommunityLink": "true",
   "EnableBotAccountCreation": "true",
   "EnableComplianceExport": "false",
   "EnableCustomBrand": "false",
   "EnableCustomEmoji": "false",
   "EnableDiagnostics": "true",
   "EnableFile": "true",
   "EnableGuestAccounts": "true",
   "EnableLdap": "false",
   "EnableMultifactorAuthentication": "false",
   "EnableOpenServer": "true",
   "EnableSaml": "false",
   "EnableSignInWithEmail": "true",
   "EnableSignInWithUsername": "true",
   "EnableSignUpWithEmail": "true",
   "EnableSignUpWithGitLab": "false",
   "EnableSignUpWithGoogle": "false",
   "EnableSignUpWithOffice365": "false",
   "EnableSignUpWithOpenId": "false",
   "EnableUserCreation": "true",
   "EnforceMultifactorAuthentication": "false",
   "FeatureFlagAnnualSubscription": "false",
   "FeatureFlagAppsEnabled": "true",
   "FeatureFlagBoardsDataRetention": "false",
   "FeatureFlagBoardsFeatureFlags": "",
   "FeatureFlagBoardsProduct": "true",
   "FeatureFlagCallsEnabled": "true",
   "FeatureFlagCommandPalette": "false",
   "FeatureFlagEnableInactivityCheckJob": "true",
   "FeatureFlagEnableRemoteClusterService": "false",
   "FeatureFlagGlobalDrafts": "true",
   "FeatureFlagGraphQL": "true",
   "FeatureFlagInsightsEnabled": "true",
   "FeatureFlagNormalizeLdapDNs": "false",
   "FeatureFlagOnboardingAutoShowLinkedBoard": "true",
   "FeatureFlagOnboardingTourTips": "true",
   "FeatureFlagPeopleProduct": "false",
   "FeatureFlagPermalinkPreviews": "true",
   "FeatureFlagPluginApps": "",
   "FeatureFlagPluginCalls": "",
   "FeatureFlagPluginFocalboard": "",
   "FeatureFlagPluginPlaybooks": "",
   "FeatureFlagPostPriority": "true",
   "FeatureFlagReduceOnBoardingTaskList": "false",
   "FeatureFlagSendWelcomePost": "true",
   "FeatureFlagTestBoolFeature": "false",
   "FeatureFlagTestFeature": "off",
   "FeatureFlagThreadsEverywhere": "false",
   "FeatureFlagUseCaseOnboarding": "true",
   "FeatureFlagWorkTemplate": "false",
   "FeatureFlagWysiwygEditor": "false",
   "FileLevel": "INFO",
   "GitLabButtonColor": "",
   "GitLabButtonText": "",
   "GuestAccountsEnforceMultifactorAuthentication": "false",
   "HasImageProxy": "true",
   "HelpLink": "https://mattermost.com/default-help/",
   "IosAppDownloadLink": "https://mattermost.com/mattermost-ios-app/",
   "IosLatestVersion": "",
   "IosMinVersion": "",
   "LdapLoginButtonBorderColor": "",
   "LdapLoginButtonColor": "",
   "LdapLoginButtonTextColor": "",
   "LdapLoginFieldName": "",
   "NoAccounts": "false",
   "OpenIdButtonColor": "",
   "OpenIdButtonText": "",
   "PasswordMinimumLength": "5",
   "PasswordRequireLowercase": "false",
   "PasswordRequireNumber": "false",
   "PasswordRequireSymbol": "false",
   "PasswordRequireUppercase": "false",
   "PluginsEnabled": "true",
   "PrivacyPolicyLink": "https://mattermost.com/privacy-policy/",
   "ReportAProblemLink": "https://mattermost.com/default-report-a-problem/",
   "SamlLoginButtonBorderColor": "",
   "SamlLoginButtonColor": "",
   "SamlLoginButtonText": "",
   "SamlLoginButtonTextColor": "",
   "SiteName": "Mattermost",
   "SiteURL": "http://127.0.0.1:8065",
   "SupportEmail": "",
   "TelemetryId": "j9wd6fn14py58egkk9kbq5qyja",
   "TermsOfServiceLink": "https://mattermost.com/terms-of-use/",
   "Version": "7.8.0",
   "WebsocketPort": "80",
   "WebsocketSecurePort": "443",
   "WebsocketURL": ""
}`

**Comment by enahum** [comment]
@furqanmlk based on what you pasted, the problem is the config the server is returning, not sure what server are you using and what is your setup, but that config definitely has a log of missing key values

**Comment by furqanmlk** [comment]
> @furqanmlk based on what you pasted, the problem is the config the server is returning, not sure what server are you using and what is your setup, but that config definitely has a log of missing key values

I am using local setup. let me re-try

**Comment by enahum** [comment]
I just tested it on my local setup and is working just fine for me

**Comment by furqanmlk** [comment]
> I just tested it on my local setup and is working just fine for me

hmm
I am getting `True` values for
`EnableMobileFileDownload: "true",`
`EnableMobileFileUpload: "true",`

I restarted the server and restarted the mobile app

image

image

**Comment by enahum** [comment]
@furqanmlk maybe you are using the config from the database and not the file? perhaps use the admin console to set them
image

**Comment by furqanmlk** [comment]
thanks @enahum 

I dont know why it is not taking effect from `config.json` 

### Disabled Downlaod
image


### Disabled Upload
image

**Review by furqanmlk — APPROVED** [review]

**Pull request merged**
