### PR TITLE
MM-32828 Copy temp file if isMediaDocument contentUri is null

### PR DESCRIPTION
**Pull request by enahum**
#### Ticket Link
https://mattermost.atlassian.net/browse/MM-32828

### CODE REVIEW

**Comment by gigawhitlocks** [comment]
@enahum would you like me to build the app from this branch and test it on my device? The code looks good but I won't really know for sure if it's effective unless I test it

**Comment by enahum** [comment]
@gigawhitlocks Yup, I can build the PR.

**Comment by gigawhitlocks** [comment]
Tested and it works! Thank you @enahum !

**Review by gigawhitlocks — APPROVED** [review]

**Review by josephbaylon — APPROVED** [review]
LGTM. Do not have Pixel 4a but smoke tested on Pixel 4 XL (11) emulator device and PDF upload works there.

**Pull request merged**
